### ISSUE TITLE
"chat_del_user" does not delete user from supergroup

### ISSUE THREAD

**Issue by ihoru** [vysheng/tg#1010]
1001013547045 - supergroup chat id
119364341 - user chat id (he is really in list of members)
I get in response: FAIL: 71: RPC_CALL_FAIL 400: PEER_ID_INVALID

$ bin/telegram-cli -e 'chat_del_user chat#1001013547045 user#119364341'
Telegram-cli version 1.3.3, Copyright (C) 2013-2015 Vitaly Valtman
...
FAIL: 71: RPC_CALL_FAIL 400: PEER_ID_INVALID

> All done. Exit

I think, the reason is that 1001013547045 - is big integer.

**Comment by jack-peterson1** [comment]
use channel_del_user

**Comment by jack-peterson1** [comment]
use channel_kick_user

**Comment by ihoru** [comment]
@jack-peterson1 test branch does not work well after rebuild. I've got this at the end of execution:
> SIGNAL received
hbin/telegram-cli(print_backtrace+0x20)[0x46ed80]
bin/telegram-cli(termination_signal_handler+0x64)[0x46ee04]
/lib/x86_64-linux-gnu/libc.so.6(+0x36d40)[0x7f37cdeffd40]
bin/telegram-cli(tgl_message_get+0x13)[0x4ad573]
bin/telegram-cli(bl_do_msg_update+0x11)[0x4b0ac1]
bin/telegram-cli[0x4a13cb]
bin/telegram-cli(tglq_query_result+0x10f)[0x4981ff]
bin/telegram-cli[0x490aea]
bin/telegram-cli[0x4b600b]
/usr/lib/x86_64-linux-gnu/libevent-2.0.so.5(event_base_loop+0x754)[0x7f37cf3a9f24]
bin/telegram-cli(net_loop+0xa6)[0x470306]
bin/telegram-cli(loop+0x187)[0x471607]
bin/telegram-cli(main+0x2e5)[0x46d5e5]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f37cdeeaec5]
bin/telegram-cli[0x46d6f5]
