### ISSUE TITLE
Load History Crash

### ISSUE THREAD

**Issue by ziadkiwan** [vysheng/tg#1013]
Hello,

When i try to launch the telegram through 
./bin/telegram -k tg-server or
 when i attempt to history one of specific conversion the telegram crash's with the following error:

`> telegram-cli: tgl/structures.c:997: tglf_fetch_message_media_new: Assertion '0' failed.
SIGNAL received
h./bin/telegram-cli(print_backtrace+0x2f)[0x46f8bf]
./bin/telegram-cli(termination_signal_handler+0x64)[0x46f954]
/lib/x86_64-linux-gnu/libc.so.6(+0x352f0)[0x7f6eae0d02f0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37)[0x7f6eae0d0267]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7f6eae0d1eca]
/lib/x86_64-linux-gnu/libc.so.6(+0x2e03d)[0x7f6eae0c903d]
/lib/x86_64-linux-gnu/libc.so.6(+0x2e0f2)[0x7f6eae0c90f2]
./bin/telegram-cli(tglf_fetch_message_media_new+0x266)[0x4a8e36]
./bin/telegram-cli[0x4ae1a9]
./bin/telegram-cli[0x4aee4e]
./bin/telegram-cli(bl_do_create_message_new+0x2c5)[0x4b0235]
./bin/telegram-cli(tglf_fetch_message_new+0x16b)[0x4a971b]
./bin/telegram-cli(tglf_fetch_alloc_message_new+0x3d)[0x4ab09d]
./bin/telegram-cli[0x4976c9]
./bin/telegram-cli(tglq_query_result+0x10f)[0x499b2f]
./bin/telegram-cli[0x49393e]
./bin/telegram-cli[0x4b4e8b]
/usr/lib/x86_64-linux-gnu/libevent-2.0.so.5(event_base_loop+0x7fc)[0x7f6eafaa3a0c]
./bin/telegram-cli(net_loop+0xa4)[0x470ea4]
./bin/telegram-cli(loop+0x195)[0x472275]
./bin/telegram-cli(main+0x2d3)[0x46e103]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f6eae0bba40]
./bin/telegram-cli(_start+0x29)[0x46e219]
`

Thank you.

**Comment by ledazinha** [comment]
see #904
