### ISSUE TITLE
Search Group Chats?

### ISSUE THREAD

**Issue by Quinncuatro** [vysheng/tg#1037]
I may be overlooking something, but I can message out to groups I'm a part of, but it doesn't seem like I can search for group names. Using "contact_list" will bring up the list of my friends, but I can't find an equivalent for groups.

**Comment by jeremija** [comment]
I'm wondering about the same thing - is there a way to get a list of (and history) of group chats? How do I send a message to a group chat if I don't know it's ID (name doesn't seem work).

**Comment by Quinncuatro** [comment]
Your edit is right, so far. I'm hoping they change that. Every once in a while my buddies and I change the name of one of our chat groups. I'd love to be able to search through active chat groups so I know I'm messaging the right people.

**Comment by Cojad** [comment]
have you try dialog_list yet?

**Comment by Quinncuatro** [comment]
Hadn't thought of that, but it does exactly what I need. :)

**Comment by Cojad** [comment]
It does take me a while to discovery this command<dialog_list>. I was looking for command name like chat_list. I think it's name dialog instead of chat because not all message happened in chat(like channels). But I think you will get used to it.

**Comment by Quinncuatro** [comment]
Yeah, it's really easy enough. But that's a huge help.
