### ISSUE TITLE
methods resolve_username or contact_search not work

### ISSUE THREAD

**Issue by ufuran** [vysheng/tg#1088]
Help me pls!!!
```
> resolve_username papercomics
> contact_search papercomics
>

```

**Comment by nico202** [comment]
Бу-----ый сам---тик (--for privacy)
works for me. Some info about version/system/etc?

**Comment by ufuran** [comment]
send commands for info please.

**Comment by ufuran** [comment]
oh, it's ban telegram for search...

**Comment by dldamilola** [comment]
@ufuran tell me please where can I read about this "search ban"? Seems to me I get this in tg but not in desktop/mobile clients.
