### ISSUE TITLE
Problems when Channel name have space or blank character

### ISSUE THREAD

**Issue by BokenCLS** [vysheng/tg#1111]
Hi,

I want to use the command:
> channel_get_members channelname

But if "channelname" is "School Group":
> channel_get_members School Group

The interpreter take as two arguments. I was try to escape with \ or quoted with " and ' but anything combinations it appears work fine.

How can I use a channel name if have blank character?

Regards.

**Comment by codefuhrer** [comment]
Replace spaces with underscores:
```shell
channel_get_members School_Group
```

**Comment by BokenCLS** [comment]
It doesn't work with underscore.

**Comment by BokenCLS** [comment]
Show this error message:
FAIL: 38: can not parse arg #1

**Comment by BokenCLS** [comment]
That's good. It works....

Thank you very much.
Regards.

**Comment by codefuhrer** [comment]
First you need to load all channels into the memory:
```channel_list```
