### ISSUE TITLE
RPC_CALL_FAIL 400: PERSISTENT_TIMESTAMP_INVALID

### ISSUE THREAD

**Issue by perlokan** [vysheng/tg#1131]
Hi,
The program ran very well before the following change.
I closed the active session from Telegram (from another device), for changing the telephone number.
After this command:  bin/telegram-cli -k tg-server.pub -W 
I received this error:
"login problem: error #71 (RPC_CALL_FAIL 400: PERSISTENT_TIMESTAMP_INVALID)
login failed
login error #71: RPC_CALL_FAIL 400: PERSISTENT_TIMESTAMP_INVALID
you can relogin by deleting auth file or running telegram-cli with '-q' flag"
I tried with bin/telegram-cli -q
It asked me the new telephone number but, after that, I continue to receive the same error.

**Comment by perlokan** [comment]
Hi,
I solved:
rm -rf ~/.telegram-cli
telegram-cli -W

**Comment by clooner** [comment]
Hello
I made a spam robot.
But that is more than 200 other members of the group does not work.
Help me please
Thanks
