### ISSUE TITLE
Can not run telegram-cli

### ISSUE THREAD

**Issue by saniks** [vysheng/tg#1146]
Debian-8.5.0-i386
Installed telegram-cli

`#git clone --recursive https://github.com/vysheng/tg.git && cd tg
#apt-get install libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev libevent-dev libjansson-dev libpython-dev
#./configure
#make`

After compiling in the terminal:
`gcc objs/main.o objs/loop.o objs/interface.o objs/lua-tg.o objs/json-tg.o objs/python-tg.o objs/python-types.o libs/libtgl.a -L/usr/local/lib -L/usr/lib -L/usr/lib  -rdynamic -ggdb -levent -ljansson -lconfig -lz -levent   -lreadline -llua5.2  -lm -ldl -lssl -lcrypto  -ldl -lpthread -lutil -o bin/telegram-cli`

How to run a telegram? Command "bin/telegram-cli" or "telegram-cli" returned `bash: /bin/telegram-cli: no such file or directory `

**Comment by saniks** [comment]
sorry `./bin/telegram-cli`

**Comment by FAIZAN35718** [comment]
./telegram

**Comment by Faizan35618** [comment]
Cannot run below command after mame command in terminal
./telegram or ./telegram.h it says permisson denied and says no such file or directory
