### ISSUE TITLE
Register new Phone using Deamon

### ISSUE THREAD

**Issue by Creapix89** [vysheng/tg#1147]
Hello!
Excellent work, thank you very much for developing this great tool. I have a question, I was able to connect with PHP without any problem, can send and receive messages excellently, but I tried to register new mobile phone from my website and I have failed. When the telegram-cli system prompts the phone number, I can not successfully enter the number. Is there any method to accomplish this task?

regards

**Comment by ledazinha** [comment]
One possibility is using a tool like [Expect](http://linux.die.net/man/1/expect). You can create a shell script to execute the client, analyse its output and give it the appropriate values for registration. Then, you can execute this script from PHP. You can find some info on how to use Expect [here](http://www.admin-magazine.com/Articles/Automating-with-Expect-Scripts),  and [here](http://www.thegeekstuff.com/2010/10/expect-examples).
Another much more complicated possibility (which I ended up doing) is to use [react/child-process](https://github.com/reactphp/child-process) to execute the client as a separate process, listen its stdout, match the output against specific strings and write the values to its stdin. It's too complex and I think that for your use case the first alternative is better.

**Comment by Creapix89** [comment]
thank you very much @ledazinha I already could successfully generate code. regards

**Comment by will-code-for-pizza** [comment]
> One possibility is using a tool like [Expect](http://linux.die.net/man/1/expect). You can create a shell script to execute the client, analyse its output and give it the appropriate values for registration. Then, you can execute this script from PHP. You can find some info on how to use Expect [here](http://www.admin-magazine.com/Articles/Automating-with-Expect-Scripts), and [here](http://www.thegeekstuff.com/2010/10/expect-examples).
> Another much more complicated possibility (which I ended up doing) is to use [react/child-process](https://github.com/reactphp/child-process) to execute the client as a separate process, listen its stdout, match the output against specific strings and write the values to its stdin. It's too complex and I think that for your use case the first alternative is better.

Is there any example for registering phone number during 1st start of telegram-cli ???

Thanx

**Comment by Paulchen232** [comment]
What is your problem? You can tell us the number witch you us. You kann change the last numbers with "X".
