### ISSUE TITLE
PEER_FLOOD while using Telegram Cli.

### ISSUE THREAD

**Issue by belykhk** [vysheng/tg#1166]
Hello.
I use sh script that i use to notify my clients in telegram via telegram-cli.
Recently i got error message while script is running.

`send_text $user $textmessage
FAIL: 100: RPC_CALL_FAIL 400: PEER_FLOOD`

After that, i can't send any messages to anyone, who don't got my number in their contact list, but can send to who add my number in contact list.

Problem is still exists after 7 hours of wait.

Script is based on usage of echo's, look's like that

```
#!/bin/bash
list=file.csv 
message=text.txt
while read lines
do
    lines2=$(echo $lines | tr -d '.' | tr -s ' ' ';') #there is some preparations to clean csv file
    echo "lines2=$lines2"
    set - $lines2
    IFS=";"
    phone=$4
    name=$2
    surname=$1
    (sleep 3; echo "add_contact "$phone" "$name"_"$surname; sleep 3; echo contact_list; sleep 3; echo "send_text "$name"_"$surname" "$message; sleep 3; echo "safe_quit") | $HOME/tg/bin/telegram-cli -k tg-server.pub -W
done < $list
```

How can i avoid that?

**Comment by vidoq1** [comment]
After u've got that error. 
when trying to add user to a group/megagroup/channel same error appears
PEER_FLOOD
