### ISSUE TITLE
.ula

### ISSUE THREAD

**Issue by harvybob** [vysheng/tg#1168]
What language is ula in? i want to add a bit more programming into the code, make input case insensitive etc, im guessing its bash, but want to check?

also will the client software ignore comments?

**Comment by LukeLR** [comment]
What do you mean with .ula? There's Lua, a scripting language you can use to write code that is executed upon every message received etc. The client itself is C.

**Comment by harvybob** [comment]
Luke, that's exactly what I ment and thanks for pointing out that it is it's own language! Should have looked a bit harder before I asked! Thanks.

**Comment by LukeLR** [comment]
It is not it's own language, both lua and C are well-known programming languages ;)
