### ISSUE TITLE
TelegramCLI not logging ?

### ISSUE THREAD

**Issue by db91595** [vysheng/tg#1187]
i am start with "screen ... -L /tmp/Telegram.log -l 1" or "... -L /var/log/Telegram.log -l 1"
and the CLI not create any of this log-files. what is my error/fault.
i hope you understand me, english is not my mother-speak :-(

**Comment by sibrat** [comment]
screen -dm -S tg -L ./telegram-cli
placement of logfile defined in /home/user/.screenrc:
`logfile /home/user/tg-logs/screenlog.log`
`log on`

**Comment by db91595** [comment]
hi sibrat - thank's for help !!!
NOW my TG logging :-)
Please: how is the Donate-Button for "Telegram-Cli" ?
