### ISSUE TITLE
production

### ISSUE THREAD

**Issue by farzamvat** [vysheng/tg#1214]
Hi,
Is it safe to use this in production?

**Comment by juanremi** [comment]
yes it is

**Comment by farzamvat** [comment]
when cli process is running more than 20hr it's taking 95% of cpu , for this reason i mean "safe", suppose i want to run n instances of this process, so i think safe is a good word

**Comment by farzamvat** [comment]
Thanks alot

**Comment by farzamvat** [comment]
Hello,
Do you know how can i logout from cli?
Thanks
