### ISSUE TITLE
#FeatureRequest  Showing messages like "more"

### ISSUE THREAD

**Issue by lucas59356** [vysheng/tg#1215]
My suggestion is if the command get a big output it represents like the command "more", It will be very practical for some people. And thanks for the geeky alternative of the telegram client :D.

**Comment by LDVSOFT** [comment]
You probably don't want to use `more` utility directly but use a preferred `pager`, like `less`.

**Comment by lucas59356** [comment]
Yes, but my suggestion mean a native feature or a integration for this
"effect". I am using cygwin and i have a habit to use "more" :).

Lapshin Dmitry <notifications@github.com> escreveu no dia terça, 25/10/2016
às 08:41:

**Comment by purplesrl** [comment]
there is no more, but there are the "limit" and "offset" variable to some commands like history

history Contact 10 50
dialog_list 10 50
