### ISSUE TITLE
unable to make on Ubuntu 14.04

### ISSUE THREAD

**Issue by fnc12** [vysheng/tg#1217]
Steps:

cd ~/Desktop/
git clone https://github.com/vysheng/tg
cd tg
./configure
make

output: 

```
make: *** No rule to make target `tgl/scheme.tl', needed by `auto/scheme.tl'.  Stop.
```

What to do?

**Comment by bahitoss** [comment]
I have the same

**Comment by pylipp** [comment]
Same here!

**Comment by andersennl** [comment]
Same here using raspbian.

**Comment by l1m3** [comment]
Thanks @andersenni ! You really helped me out

**Comment by duncanturk** [comment]
this issue may be closed or?

**Comment by fnc12** [comment]
yes
