### ISSUE TITLE
24/7 active connection?

### ISSUE THREAD

**Issue by rmnoff** [vysheng/tg#1226]
So I run telegram-cli on my VPS and there is one more script on python, which randomly checks history of 15 channels every 15-40 sec. There is a delay between each history command like 8-10 sec. I set it for 24 hours, but after 6 hours it stopped doing anything. Is there any suggestions why it happened?

**Comment by Ilhicas** [comment]
Maybe some sort of connection lost, recovery with telegram-cli is a pain.
