### ISSUE TITLE
Can telegram servers distinct this client from the others?

### ISSUE THREAD

**Issue by insiderq** [vysheng/tg#1237]
Basically the question is in the topic

Is there something like user-agent or something else that can help telegram servers to understand that this is console client rather than web-client or standard gui client?

**Comment by LukeLR** [comment]
Yep, there is. When developing a client, you have to register for an API key, and in that registration, you enter what kind of client it is. The end-user usually gets in contact with that when he authenticates that client, then the security message from telegram says: "We detected a new login, device: xy IP: xy". But there is no distinguishment made between clients on the server side (as far as we know).

**Comment by insiderq** [comment]
Thanks

**Comment by taa1** [comment]
@insiderq -- may I inquire as to why you're asking? I'm wondering if it is related to my current issue with the Telegram protocol where toast notifications only seem to be generated on clients when the sender is different than the receiver, requiring the use of two cell phone accounts. I'd like to use telegram-cli on a headless Raspberry Pi to send messages to "self" but the current Telegram clients quietly receive such messages -- no toast notification to get my attention. I realize that normally you would want messages to "self" to be muted like this, but I wish there was a way to override the behavior that doesn't require a second cell phone number, and that doesn't require creating a bot.

**Comment by insiderq** [comment]
@taa1 well, mine issue was different and honestly, i do not understand yours, but i have figured out how to fake this to telegram and i can tell you how to do this. Can you PM me?
