### ISSUE TITLE
telegram-cli 1.4.1 crashes on xubuntu

### ISSUE THREAD

**Issue by fret2buzz** [vysheng/tg#1240]
![telegram-cli 1.4.1](http://i.imgur.com/Xpc9Btx.png)
telegram-cli 1.4.1 crashes on xubuntu

While telegram-cli 1.0.5 works as expected
![telegram-cli 1.0.5](http://i.imgur.com/EmU5Im9.png)

**Comment by cher-nov** [comment]
@fret2buzz @vysheng

I have the same issue on Xubuntu 16.04.1 LTS 32-bit (i386).
But it began working for me since I've commented [line 101 of mtproto-utils.c](vysheng/tgl/blob/ffb04caca71de0cddf28cd33a4575922900a59ed/mtproto-utils.c#L101) and rebuilt.

**Comment by fjleon1980** [comment]
same problem on debian 8

`> telegram-cli: tgl/mtproto-utils.c:101: BN2ull: Assertion `0' failed.
SIGNAL received
h./telegram-cli(print_backtrace+0x27)[0x80a9817]
./telegram-cli(termination_signal_handler+0x81)[0x80a98b1]
linux-gate.so.1(__kernel_sigreturn+0x0)[0xb7777d1c]
linux-gate.so.1(__kernel_vsyscall+0x10)[0xb7777d40]
/lib/i386-linux-gnu/i686/cmov/libc.so.6(gsignal+0x47)[0xb7245367]
/lib/i386-linux-gnu/i686/cmov/libc.so.6(abort+0x143)[0xb7246a23]
/lib/i386-linux-gnu/i686/cmov/libc.so.6(+0x276c7)[0xb723e6c7]
/lib/i386-linux-gnu/i686/cmov/libc.so.6(+0x27777)[0xb723e777]
./telegram-cli[0x80f5a7e]
./telegram-cli[0x80ca212]
./telegram-cli[0x80cd672]
./telegram-cli[0x80f4bd3]
/usr/lib/i386-linux-gnu/libevent-2.0.so.5(event_base_loop+0x73d)[0xb772236d]
./telegram-cli(net_loop+0xac)[0x80aadbc]
./telegram-cli(loop+0x196)[0x80ac086]
./telegram-cli(inner_main+0x17)[0x80a8da7]
./telegram-cli(main+0x2f0)[0x80a7f10]
/lib/i386-linux-gnu/i686/cmov/libc.so.6(__libc_start_main+0xf3)[0xb7230a63]
./telegram-cli[0x80a801d]
`
