### ISSUE TITLE
How to get the load_photo name in lua to resend the photo

### ISSUE THREAD

**Issue by apulidoc** [vysheng/tg#1253]
Hi,

Im trying to resend the images that i receive in a private user chat to a channel with lua scripts... I can load the photos that i receive but i dont know how to get the name of the downloaded photo to resend.

im using load_photo(msg.id, ok_cb, false) but which is the name ?

Is there any workaround to resend photos that i receive?

**Comment by AndyLiebe** [comment]
I need this too!!!

**Comment by apulidoc** [comment]
Hi again,

Im still fighting to solve my problem...

Im trying to get the name of the file with an a function like this...

function on_msg_receive (msg)

	if started == 0 then
		return
	end

	if msg.out then
		return
	end

	if ( msg.to.peer_id == channelID ) then

		if ( msg.media == nil ) then
			send_msg ( 'ChannelName' , msg.text , ok_cb, false )
		else

			if ( msg.media.type == 'photo' ) then
				vari = load_photo( msg.id , ok_cb , false )
				
				if ( vari == true ) then
					enviafoto()
				end
			end
		end

	end
end

With this, i can to load the photo received from a specific channel to my ubuntu in /home/xxxxxx/Downloads

In addition, i have the function "enviafoto()" where im trying get the filename from the file that ive loaded to use the lua function "send_photo"


`
 function enviafoto() 

 	comando = "find /home/xxxxxx/Downloads/ -type f -print" -- getting the file route

 	os.execute(comando .. " > /home/xxxxx/archivos") -- sending the route to an archive 

 	local ruta = "" 

 	for f in io.lines("/home/xxxxx/archivos") do -- looping through the archive to the name 
 		if f:sub(-4) == ".jpg" then 
 			ruta = f 
 		end 
 	end 

 	print(ruta) 
 	send_msg ( 'ChannelName' , 'Trying to send a photo' , ok_cb , false )
 	send_photo( 'ChannelName', ruta , ok_cb ) 
 	os.remove(ruta) -- remove the file return true 
 end
`

When i send the first photo nothing happens, when i send the second photo, the script returns the first file! like if the command 'send_photo' executes after my function 'enviafoto()'

Can anyone help me? Sorry for my bad english.

**Comment by apulidoc** [comment]
Solved.

I had to call my function enviafoto from cb_function as param of send_photo.

read README-LUA
