### ISSUE TITLE
having issues with "make"

### ISSUE THREAD

**Issue by l1m3** [vysheng/tg#1255]
When I try to set up telegram through command-line, I get the following issue:

`make: *** No rule to make target 'tgl/scheme.tl', needed by 'auto/scheme.tl'.  Stop.`

Does anyone know what the problem is and / or how to solve it?

Thanks for your time, 
 - l1m3

**Comment by Derpford** [comment]
Issue closed without solution? I am having the same error.

**Comment by Derpford** [comment]
Nevermind, found possible solution in #1217
