### ISSUE TITLE
Can't install telegram-cli on Debian Stretch (Testing)

### ISSUE THREAD

**Issue by roshangm1** [vysheng/tg#1256]
```
tgl/crypto/rsa_pem_openssl.c: In function ‘TGLC_rsa_new’:
tgl/crypto/rsa_pem_openssl.c:41:6: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’
   ret->e = unwrap_bn (TGLC_bn_new ());
      ^~
tgl/crypto/rsa_pem_openssl.c: In function ‘TGLC_rsa_n’:
tgl/crypto/rsa_pem_openssl.c:52:1: error: control reaches end of non-void function [-Werror=return-type]
 RSA_GETTER(n);
 ^~~~~~~~~~
tgl/crypto/rsa_pem_openssl.c: In function ‘TGLC_rsa_e’:
tgl/crypto/rsa_pem_openssl.c:53:1: error: control reaches end of non-void function [-Werror=return-type]
 RSA_GETTER(e);
 ^~~~~~~~~~
cc1: all warnings being treated as errors
Makefile.tgl:20: recipe for target 'objs/crypto/rsa_pem_openssl.o' failed
make: *** [objs/crypto/rsa_pem_openssl.o] Error 1

```

Getting this error after doing `make`.

**Comment by parazitt** [comment]
yes sadly, i have similar problem.

**Comment by parazitt** [comment]
i have some problem like this.
you can fix it by add --disable-openssl  flag:
./configure --disable-openssl 
then you can make easily.

**Comment by roshangm1** [comment]
That worked but I had to install libgcrypt11-dev to do ./configure. Thanks.

**Comment by antosamalona** [comment]
How to add it in rules file?

**Comment by steadfasterX** [comment]
thx this works for me on debian stretch..
Does this workaround have any disadvantages?

**Comment by elFua** [comment]
On armv8 (raspberry pi, 32bit) it compiles successfully after `./configure --disable-openssl` and installing `libgcrypt20-dev`, but after launching it uses 100% CPU and does nothing.

**Comment by sufehmi** [comment]
This is the solution : 

[(https://github.com/freifunk-gluon/gluon/issues/973#issuecomment-265911151)]

**Comment by xbsd** [comment]
Excellent 

> This is the solution :
> 
> [freifunk-gluon/gluon#973 (comment)](https://github.com/freifunk-gluon/gluon/issues/973#issuecomment-265911151)

Excellent, thanks ! The fix in our case was to install `libssl1.0-dev` (`sudo apt-get install libssl1.0-dev`)

**Comment by Pulkit12083** [comment]
> i have some problem like this.
> you can fix it by add --disable-openssl flag:
> ./configure --disable-openssl
> then you can make easily.

what are the ramifications of --disable-openssl? Security ramifications or otherwise?
