### ISSUE TITLE
Unable to install on Mac OS X

### ISSUE THREAD

**Issue by MarcoBuster** [vysheng/tg#1270]
Hi! 
When I try to install tg-cli on Mac OS X, I have this error (while doing `make`)
```
main.c:904:3: error: use of undeclared identifier 'rl_catch_signals'
  rl_catch_signals = 0;
  ^
1 error generated.
make: *** [objs/main.o] Error 1
```
How I can fix it?

**Comment by ailinykh** [comment]
Try [this script](https://github.com/vysheng/tg/issues/879#issuecomment-251276231) it is works well for me
