### ISSUE TITLE
to get list of shared medias of a channel

### ISSUE THREAD

**Issue by mbande** [vysheng/tg#1283]
any way to filter messages by media type (photos, videos, links, etc) as Telegram App/Desktop do.

**Comment by pazis** [comment]
Look at the CLI commands:

load_audio <msg-id> Downloads file to downloads dirs. Prints file name after download end
load_document <msg-id> Downloads file to downloads dirs. Prints file name after download end
load_document_thumb <msg-id> Downloads file to downloads dirs. Prints file name after download end
load_file <msg-id> Downloads file to downloads dirs. Prints file name after download end
load_file_thumb <msg-id> Downloads file to downloads dirs. Prints file name after download end
load_photo <msg-id> Downloads file to downloads dirs. Prints file name after download end
load_video <msg-id> Downloads file to downloads dirs. Prints file name after download end
load_video_thumb <msg-id> Downloads file to downloads dirs. Prints file name after download end

**Comment by mbande** [comment]
@pazis i dont want to load a special media, i want to list of them without loading all history
as "Shared Media" section (below Channel Info) in Telegram Desktop do
