### ISSUE TITLE
Error "can't open file" when using send_file

### ISSUE THREAD

**Issue by julien-h** [vysheng/tg#1312]
Hi,

I always get the same error when trying to send a file : 

> send_file MyName ~/Desktop/test.png 
> FAIL: 9: Can not open file: m

Someone knows how to fix it ?

**Comment by ManuCart** [comment]
I used it with lua and tg as bot and for me it's working
```
if (msg.text=='/photo') then
os.execute("cd ~/scripts && bash take-photo")
local file_path = '/media/hdd/photo.jpg'
send_photo(msg.from.print_name, file_path, ok_cb, false)
send_msg (msg.from.print_name, 'Be patient photo come on', ok_cb, false)
end
```

**Comment by M-Becerra** [comment]
That's because you used `~/Desktop/test.png` instead of `/home/$USER/Desktop/test.png`, telegram-cli doesn't accept `~/` abbreviation.

**Comment by julien-h** [comment]
Ah ! Thanks. Is it documented somewhere ? I did look around before asking but didn't find anything.

**Comment by M-Becerra** [comment]
@julien-h I have no idea if it's documented anywhere, I just supposed the `~/` could be problematic, tried without it, and worked. 

If you do find some documentation about it, please give me a hint :D

**Comment by Skovorp** [comment]
I tried `send_file AM /Users/ksc/Desktop/abcdef.mov` but I'm still getting `FAIL: 9: Can not open file: m`
