### ISSUE TITLE
Compilation error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’

### ISSUE THREAD

**Issue by matthiasbock** [vysheng/tg#1338]
Hi,

I am trying to compile latest commit 6547c0b21b977b327b3c5e8142963f4bc246187a,
but get the following error:

<pre>
$ ./configure && make
...
gcc -I. -I. -I./tgl -g -O2  -I/usr/local/include -I/usr/include -I/usr/include -I/usr/include/lua5.2  -DHAVE_CONFIG_H -Wall -Werror -Wextra -Wno-missing-field-initializers -Wno-deprecated-declarations -fno-strict-aliasing -fno-omit-frame-pointer -ggdb -Wno-unused-parameter -fPIC -iquote ./tgl -c -MP -MD -MF dep/crypto/sha_openssl.d -MQ objs/crypto/sha_openssl.o -o objs/crypto/sha_openssl.o tgl/crypto/sha_openssl.c
gcc -I. -I. -I./tgl -g -O2  -I/usr/local/include -I/usr/include -I/usr/include -I/usr/include/lua5.2  -DHAVE_CONFIG_H -Wall -Werror -Wextra -Wno-missing-field-initializers -Wno-deprecated-declarations -fno-strict-aliasing -fno-omit-frame-pointer -ggdb -Wno-unused-parameter -fPIC -iquote ./tgl -c -MP -MD -MF dep/crypto/sha_altern.d -MQ objs/crypto/sha_altern.o -o objs/crypto/sha_altern.o tgl/crypto/sha_altern.c
gcc -I. -I. -I./tgl -g -O2  -I/usr/local/include -I/usr/include -I/usr/include -I/usr/include/lua5.2  -DHAVE_CONFIG_H -Wall -Werror -Wextra -Wno-missing-field-initializers -Wno-deprecated-declarations -fno-strict-aliasing -fno-omit-frame-pointer -ggdb -Wno-unused-parameter -fPIC -iquote ./tgl -c -MP -MD -MF dep/crypto/aes_openssl.d -MQ objs/crypto/aes_openssl.o -o objs/crypto/aes_openssl.o tgl/crypto/aes_openssl.c
tgl/crypto/rsa_pem_openssl.c: In function ‘TGLC_rsa_new’:
tgl/crypto/rsa_pem_openssl.c:41:6: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’
   ret->e = unwrap_bn (TGLC_bn_new ());
      ^~
tgl/crypto/rsa_pem_openssl.c: In function ‘TGLC_rsa_n’:
tgl/crypto/rsa_pem_openssl.c:52:1: error: control reaches end of non-void function [-Werror=return-type]
 RSA_GETTER(n);
 ^~~~~~~~~~
tgl/crypto/rsa_pem_openssl.c: In function ‘TGLC_rsa_e’:
tgl/crypto/rsa_pem_openssl.c:53:1: error: control reaches end of non-void function [-Werror=return-type]
 RSA_GETTER(e);
 ^~~~~~~~~~
cc1: all warnings being treated as errors
Makefile.tgl:20: recipe for target 'objs/crypto/rsa_pem_openssl.o' failed
make: *** [objs/crypto/rsa_pem_openssl.o] Error 1
</pre>

I found a similar issue here: https://github.com/curl/curl/issues/763
Does the problem maybe have to do with an incompatible OpenSSL library version?
My libssl-dev version is 1.1.0e-1 (Debian).

Cheers, Matthias

**Comment by matthiasbock** [comment]
The problem is located in the submodule https://github.com/vysheng/tgl/commit/ffb04caca71de0cddf28cd33a4575922900a59ed.
I am therefore closing this issue and re-opened it there.

**Comment by gabrielbandeira80** [comment]
1 - apt-get install libgcrypt11-dev
2 - ./configure --disable-openssl
3 - make
