### ISSUE TITLE
chat_info for supergroup "FAIL: 38: can not parse arg #1"

### ISSUE THREAD

**Issue by eteamin** [vysheng/tg#1350]
Create a group (for example "hello"), upgrade it to a supergroup, invoke a link, use the link to join to the channel using another account in telegram-cli. Then in the telegram-cli acount using `chat_info hello` or `chat_add_user hello someone" results in 
"FAIL: 38: can not parse arg #1"

**Comment by BillyHalley** [comment]
what I learned is that supergroups are considered channels, so you have to use `channel_info <channel>` and `channel_invite <channel> <user>`, I suppose, 
I never tried adding users to supergroups, but i tried channel_info and it works:
```
> channel_info #######
Channel [megagroup] ####### (#######):
	about: #######
	3 participants, 3 admins, 1 kicked
```
i redacted the possible sensible information about my chat group 

you can see it yourself looking at `dialog_list` 's output, there you can see which are chats, channels or users

**Comment by ntcong** [comment]
any idea what changed recently? I tried creating a supergroup and its peer_type is chat. Channel_info command has no effect
