### ISSUE TITLE
Cannot enter phone number and name, error

### ISSUE THREAD

**Issue by welljsjs** [vysheng/tg#1357]
Hi, 

I just tried to set up telegram on my RPi, but after typing "bin/telegram-cli -k tg-server.pub, following message appears: "change_user_group: can’t find the user telegramd to switch to
>Telegram-cli version 1.4.1, Copyright(c) 2013-2015 Vitaly Valtman
>[…]
>I: config dir=[/root/.config/telegram-cli]
>\>telegram-cli: tgl/mtproto-utils.c : 101: BN2ull: Assertion ‚0‘ failed.
>SIGNAL received."

After it, I am not asked to enter any number or name. 
Could you help me? Thanks a lot!

**Comment by jonisc** [comment]
Had the same issues.
First adduser telegrams and then see  #1070
