### ISSUE TITLE
Search Example

### ISSUE THREAD

**Issue by salamsalamhavji** [vysheng/tg#1398]
Hi, Please write an example for search query?
"search 1504654943 15046981413 HelloWorld" is correct?

**Comment by NabiKAZ** [comment]
YES!  
You can just test it!!!  
>search [peer] [limit] [from] [to] [offset] pattern      Search for pattern in messages from date from to date to (unixtime) in messages with peer (if peer not present, in all messages)

**Comment by salamsalamhavji** [comment]
Tnx
