### ISSUE TITLE
Support persian in telegram cli arguments

### ISSUE THREAD

**Issue by amirbagh75** [vysheng/tg#1422]
hi.
why telegram cli doesnt suport persian in arguments ?
for example when i use this command : channel_get_members تست
i see this returned : FAIL: 38: can not parse arg #1
how i can fix it ?

**Comment by NabiKAZ** [comment]
You must use channel ID instead of channel name. also need start with `@`. for example:
channel_get_members @InjaGhatie

**Comment by elahevenus** [comment]
telegram cli barname jodast? yeki rahnamayi mikone..man kheili lazem daram

**Comment by elahevenus** [comment]
va ye soale dige kasi balade userhaye ye kanale dige ro hack kone?

**Comment by NabiKAZ** [comment]
@elahevenus 
پیشنهاد میکنم در اینجا انگلیسی مکاتبه کنید، البته مطمئن نیستم قانونی در این مورد وجود داشته باشه.
ضمناً برای موضوعات جدید، issue جدید باز کنید و زیر issue های نا مرتبط پیام ارسال نکنید.
×××
تلگرام CLI در واقع یک اینترفیس غیررسمی برای تلگرام رسمی هست که این امکان رو فراهم میکنه تا تحت خط فرمان از تلگرام استفاده کنید و به سرورهای تلگرام وصل میشه.

**Comment by amirbagh75** [comment]
thanks !

**Comment by elahevenus** [comment]
این صفحه رو خوندم اما نمیدونم cli v,  رو از کجا بیارم؟
  
|  
|   
|   
|   |    |

   |

  |
|  
|    |  
vysheng/tg
 tg - telegram-cli  |   |

  |

  |

 
 

    On Saturday, October 21, 2017 10:43 PM, amirhossein baghaie <notifications@github.com> wrote:
 

 Closed #1422.—
