### ISSUE TITLE
libconfig.so.9: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by polpetone** [vysheng/tg#1448]
System: Arch-Linux
Next to Last Update on 15.11.17
Last Update on 28.11.17 
Installed Telegram-Cli: `aur/telegram-cli-git r1128.6547c0b-1 [installed] (132) (1,63)`

Since today (last update, 2017-11-28) i got following Issue/Failure when starting the telegram-cli: 
`telegram-cli: error while loading shared libraries: libconfig.so.9: cannot open shared object file: No such file or directory.`

On my system i have following libconfig: 
`ls -la /usr/lib | grep libconfig`                                                                                                                                                               

 `
   libconfig.so -> libconfig.so.11.0.1
   libconfig++.so -> libconfig++.so.11.0.1
   libconfig.so.11 -> libconfig.so.11.0.1
   ibconfig++.so.11 -> libconfig++.so.11.0.1
   libconfig.so.11.0.1
   libconfig++.so.11.0.1
`
I'm not sure about the libconfig versions. So obviously i don't have the `ibconfig.so.9` anymore.  
Is there any approach about this ?

**Comment by figue** [comment]
You need to rebuild completely, so:

makepkg -sicf

**Comment by lfehn** [comment]
I have the same issue. Where would I need to execute this "makepkg -sicf"?

**Comment by figue** [comment]
Just clone the repo in your desired build directory:
`git clone https://aur.archlinux.org/telegram-cli-git.git`
then "cd telegram-cli-git"
and finally: makepkg -sicf

**Comment by polpetone** [comment]
Thanks a lot, this solved the issue.
