### ISSUE TITLE
-bash: bin/telegram-cli: No such file or directory

### ISSUE THREAD

**Issue by rileym217** [vysheng/tg#1593]
I keep getting the above issue when I try and run the bin/telegram-cli -k tg-server.pub command. Any pointers?

**Comment by Paulchen232** [comment]
In witch folder you have it installed. Normely you start it with ~/tg/bin/telegram-cli.

**Comment by rileym217** [comment]
I am still having the issue. My current directory was ~/tg/. I followed directions exactly as you have them. I am running this on Rasbian

**Comment by Paulchen232** [comment]
Exist there `bin`.

**Comment by Paulchen232** [comment]
Have du `make`

**Comment by rileym217** [comment]
Can you clarify on that?

**Comment by rileym217** [comment]
![Error1](https://user-images.githubusercontent.com/49655362/56156558-1fc6fd80-5f83-11e9-8ef2-0a59da5c2d2e.PNG)

**Comment by rileym217** [comment]
This is what I get and what I am running
![Error1](https://user-images.githubusercontent.com/49655362/56156635-45540700-5f83-11e9-9b9e-962b0bd1e25c.PNG)

**Comment by rileym217** [comment]
I have done my make

**Comment by rileym217** [comment]
![Error2](https://user-images.githubusercontent.com/49655362/56156734-76ccd280-5f83-11e9-9ffa-8a13f26d893d.PNG)
This is what I get after running my make

**Comment by Paulchen232** [comment]
`make` Ist Not ready. So you can not start it. 

Try `apt-get install libssl-dev`

**Comment by rileym217** [comment]
I did that and I am still getting the error

**Comment by Paulchen232** [comment]
Error with `make`?

**Comment by rileym217** [comment]
Correct same screenshot as before

**Comment by Paulchen232** [comment]
Works `./configure`.

**Comment by Paulchen232** [comment]
Try this:
`sudo apt-get install libssl1.0-dev`
Then do `make`
If `make` not works you can not start.

**Comment by rileym217** [comment]
I got it working. Thanks for your help
