### ISSUE TITLE
How to read msg-id and delete message after reading

### ISSUE THREAD

**Issue by hollysheep** [vysheng/tg#1612]
I use telegram-cli to send commands from my Android to my raspberry pi. Because im not familiar with lua i send the message to a shell script and use a lot of if-else to choose what to do with the message. Sometimes it would be a good idea to delete the message directly after reading the message and Sendung it to my shell script. I know i have to Start telegram-cli with Option -N and can delete the message with delete_msg <msg-id>.

But i cant include this command in my shell script because the msg-id isn't sent to the shell script. Only the message Text is sent. How can i do this?

**Comment by Paulchen232** [comment]
I think you can in lua the last message delete with:
`delete_msg(msg.id, ok_cb, false)`

**Comment by hollysheep** [comment]
I want to do this with my shell script. I have this line in my actions.lua

os.execute("/home/pi/.telegram-cli-script " .. msg.text)

This sends the message Text to the shell script. In the shell script i use some if-else-commands to decide what to do. In some chases i want to delete the message and for that i need the id. I can send the message id to the script when i replace msg.text with msg. id in actions.lua. but how can i send both, the Text ans the id?

The most if-commands will ignore the id, but some of then will use it together with the Text.

**Comment by Paulchen232** [comment]
What you need to decide if you want delete the message. Because in shell script I think it is bad to delete. but if you can get the the big number (msg.id) in the shell then you can delete the message with 
`-e 'delete_msg <big number>'` in the shell.

**Comment by Paulchen232** [comment]
With .. you can add a variable.

**Comment by hollysheep** [comment]
I tried this

os.execute("/home/pi/.telegram-cli-script " .. msg.text .. msg.id)

but then i only get the id and not the message text.

**Comment by Paulchen232** [comment]
OK, write in the line before "os.execute(.." ´print("*"..msg.text.."*")` to see in telegram-cli the text.

**Comment by Paulchen232** [comment]
I have change my answer.

**Comment by Paulchen232** [comment]
With `print` it work not.

**Comment by Paulchen232** [comment]
I think there is anything in the shell wrong.

**Comment by Paulchen232** [comment]
I have test it. And it Work.
os.execute("/home/pi/tg/telegram-cli-script " .. msg.text .. " " .. msg.id)
telegram-cli-script:
`#!/bin/bash`
`echo $1 $2`
you see it in telegram-cli.
os.execute: with and without .. " "

**Comment by hollysheep** [comment]
Yes, works for me. Can i set something like a separator between the 2 values? At the separator is "space". Ive tried " | " instead of " " but this doesnt work.

**Comment by hollysheep** [comment]
Is the Ordner of the characters in the message id always the same? Lets say i have an id with first 10 numbers and then 3 letters. Can i be sure that all id have the same pattern?

**Comment by Paulchen232** [comment]
No, that is a hex-number. A | ist a "pipe". Look in Google or startpage.com what that in the shell mean.

**Comment by Paulchen232** [comment]
If you ready with this issues close it.
![github](https://user-images.githubusercontent.com/24520281/61111953-0ef72c80-a48b-11e9-92c9-3d97fa69ee90.jpg)
