### ISSUE TITLE
stuck after 6 run following

### ISSUE THREAD

**Issue by alix59** [vysheng/tg#1626]
Hello
I make a script with telegram-cli and he need multiple msg command from console
"telegram-cli -W -e 'command'"
but after 6 execution , telegram-cli is stuck
(my english is bad because i am french)

how to remove spam limit?

**Comment by Paulchen232** [comment]
Perhaps if you need not so often the command make this:
```
-e '<command>
<command>
<command>'
```
So you need a real line break.

**Comment by alix59** [comment]
yes i know
but he don't work on python3.6
my script check history of channel and if have new message , he send in other channel
`import os,time
from subprocess import STDOUT, check_output

sourcename = str(input("Nom exacte du channel privé: "))
name = sourcename.replace(" ","_") 
backupname = str(input("Nom exacte du channel de reception : "))
backupname = backupname.replace(" ","_")
backup = ""
test = 0

while 1:
        output = os.popen('telegram-cli -W -e "history '+name+'"').read()
        output = output.replace("> > \n","")
        output = output.replace("\n> ","")
        output = output.replace("[K\x1b","")
        output = output.replace("\x1b[0m\n\x1b[K> > All done. Exit\nhalt\n","")
        output = output.split("\n\x1b[36;1m")

        for x in range(1,len(output)-1):
                if backup.find(output[x]) ==  -1 and output[x].find(sourcename) != -1:
                        backup = backup+output[x]
                        sending = str(output[x].replace("\x1b[0m \x1b[36;1m",""))
                        sending = sending.replace("\x1b[0m\x1b[34;1m","")
                        sending = sending.replace("'"," ")
                        sending = sending.replace('"'," ")
                        sending = sending.replace("\x1b[0m","")
                        sending = sending.replace("»»»",">")
                        b = sending.find(sourcename)
                        sending = sending[b+len(sourcename):]
                        sending = sending.replace("(","")
                        sending = sending.replace(")","")
                        sending = sending.replace(">","")
                        out = os.popen('telegram-cli -W -e "msg '+backupname+' '+sending+' "').read()'

**Comment by Paulchen232** [comment]
Sorry, but I don`t understand this.
Try this with a lua script.

**Comment by alix59** [comment]
I already tested lua
but is not work for this action

`output = os.popen('telegram-cli -W -e "history '+name+'"').read()`#check history of the channel one

`out = os.popen('telegram-cli -W -e "msg '+backupname+' '+sending+' "').read()`#if have new message,the message is sent to the channel two

but after four call, (even manualy) , telegram-cli not work and get stuck

if you want try this six time in your Unix console
telegram-cli -W -e "dialog_list"

**Comment by Paulchen232** [comment]
It go not too.

But look on README-PY.md
and this 
[eonjza/pytel](https://github.com/leonjza/pytel?files=1)
You do not use ''telegram-cli -W -e ...'

**Comment by alix59** [comment]
finally i used telepot and telegram-cli
i used telegram-cli every 30 second and send all message with telepot
