### ISSUE TITLE
not able to build : tgl/queries.c:2091:10

### ISSUE THREAD

**Issue by somthingIswentWrong** [vysheng/tg#1633]
Hello everyone,

I get problems to build telegram on the raspbian buster lite (Linux raspberry 4.19.75+ #1270 Tue Sep 24 18:38:54 BST 2019 armv6l GNU/Linux).
My git clone is from today (2019-12-25).

During compilation I get these errors:

tgl/queries.c: In function _tgl_do_send_photo:
tgl/queries.c:2091:10: error: cast between incompatible function types from void (*) (struct tgl_state *,void*,int,struct tgl_message *) to void (*)(struct tgl_state *,void*,int) [-Werror=cast-function-type] ((void (*)(struct tgl_state*,void*,int)callback) (TLS,callback_extra,0);

The same in 
line 2108 and 2141

any hints?

**Comment by Paulchen232** [comment]
Have you this:
cc1: all warnings being treated as errors

**Comment by somthingIswentWrong** [comment]
Hello Paulchen,
unfortunately I didn't save the complete error output but I solved my problem like the Fedora guys:

First of all removed the configure and the Makefiles from the last try.
Then I had to install libgcrypt20-dev and libssl-dev
`apt-get install libgcrypt20-dev libssl-dev`
, do configure with this command
`./configure --disable-openssl --prefix=/usr CFLAGS="$CFLAGS -w"`
and at least ` $ make`
See also issue #1537

**Comment by kenjey01** [comment]
> Hello Paulchen,
> unfortunately I didn't save the complete error output but I solved my problem like the Fedora guys:
> 
> First of all removed the configure and the Makefiles from the last try.
> Then I had to install libgcrypt20-dev and libssl-dev
> `apt-get install libgcrypt20-dev libssl-dev`
> , do configure with this command
> `./configure --disable-openssl --prefix=/usr CFLAGS="$CFLAGS -w"`
> and at least ` $ make`
> See also issue #1537

Thank you! It works. I had the same errors. My os is Debian 10 and gcc version is v8.3.

**Comment by DimitriBolt** [comment]
> Hello Paulchen,
> unfortunately I didn't save the complete error output but I solved my problem like the Fedora guys:
> 
> First of all removed the configure and the Makefiles from the last try.
> Then I had to install libgcrypt20-dev and libssl-dev
> `apt-get install libgcrypt20-dev libssl-dev`
> , do configure with this command
> `./configure --disable-openssl --prefix=/usr CFLAGS="$CFLAGS -w"`
> and at least ` $ make`
> See also issue #1537

It works!!! Thanks.

**Comment by Pulkit12083** [comment]
> Hello Paulchen,
> unfortunately I didn't save the complete error output but I solved my problem like the Fedora guys:
> 
> First of all removed the configure and the Makefiles from the last try.
> Then I had to install libgcrypt20-dev and libssl-dev
> `apt-get install libgcrypt20-dev libssl-dev`
> , do configure with this command
> `./configure --disable-openssl --prefix=/usr CFLAGS="$CFLAGS -w"`
> and at least ` $ make`
> See also issue #1537

Is this sound? What are the effects of using `--disable-openssl`? I've seen this solution cited at a bunch of places by people running into this issue but there's no discussion over why this works? and if this is a secure way to build telegram.

@Paulchen232 can you confirm if it's a good idea to use this solution?

**Comment by nuclimedia** [comment]
> > Hello Paulchen,
> > unfortunately I didn't save the complete error output but I solved my problem like the Fedora guys:
> > First of all removed the configure and the Makefiles from the last try.
> > Then I had to install libgcrypt20-dev and libssl-dev
> > `apt-get install libgcrypt20-dev libssl-dev`
> > , do configure with this command
> > `./configure --disable-openssl --prefix=/usr CFLAGS="$CFLAGS -w"`
> > and at least ` $ make`
> > See also issue #1537
> 
> Is this sound? What are the effects of using `--disable-openssl`? I've seen this solution cited at a bunch of places by people running into this issue but there's no discussion over why this works? and if this is a secure way to build telegram.
> 
> @Paulchen232 can you confirm if it's a good idea to use this solution?

It works for me!
Robust code, using it for 7 years!
