### ISSUE TITLE
Can i specify config path?

### ISSUE THREAD

**Issue by cs-usst** [vysheng/tg#1636]
Can i specify a custom path for configuration?

**Comment by Paulchen232** [comment]
Look there:
pi@raspberrypi:~/.telegram-cli $ cat config
# This is an empty config file
# Feel free to put something here

wait-dialog-list = true;

profil1 = {config_directory = ".telegram-cli/1";
msg_num = true;
wait-dialog-list = true;
};

**Comment by Paulchen232** [comment]
For that path use the the argument `-p profil1`

**Comment by cs-usst** [comment]
> For that path use the the argument `-p profil1`

Thanks. Before asking I tried -c argument but it didn't work. It turns out that -c and -p combined work for me.

**Comment by Paulchen232** [comment]
Telegram CLI Arguments
https://github.com/vysheng/tg/issues/1636#event-2928017682
