### ISSUE TITLE
Is it possible to send multiple messages in command mode?

### ISSUE THREAD

**Issue by cs-usst** [vysheng/tg#1637]
I want to send different messages to different user in command mode, is it possible to do that using only one line of code?
for example I want to combine these three commands into one:
```
telegram-cli -W -e "msg User1 1"
telegram-cli -W -e "msg User1 2"
telegram-cli -W -e "msg User2 3"
```

**Comment by Paulchen232** [comment]
You can do it with a real line break:
telegram-cli -W -e 'msg User1 1
msg User1 2
msg User2 3'

**Comment by cs-usst** [comment]
> You can do it with a real line break:
> telegram-cli -W -e 'msg User1 1
> msg User1 2
> msg User2 3'

It works perfectly. Thanks
