### ISSUE TITLE
Send message to chat with a title containing several words

### ISSUE THREAD

**Issue by nautics889** [vysheng/tg#1645]
How to send message to peer that has several words in his name/it's title separated by spaces?
I couldn't found existing topic with this issue, probably there is something related in readme, but i didn't manage to find. 
I tried to wrap name in quotes like this:
`msg 'Firstname Lastname' test `
but it didn't work.

**Comment by ByteWoofer** [comment]
Tab autocomplete revealed to me that spaces are automatically replaced with underscores. 

For example:

Messaging a user "The Wolf" can be done by `msg The_Wolf <message>`
