### ISSUE TITLE
Run command on start

### ISSUE THREAD

**Issue by Fealo** [vysheng/tg#1648]
Is it possible to run a command on start without quitting afterwards (as happens with the -e option). 
Such as running a chat_with_peer command right out of the terminal?

**Comment by Paulchen232** [comment]
You can `chat_with_peer`only use in the normal way. With [tab] is a bit lighter.

**Comment by Fealo** [comment]
Alright, so there is no comparable option to -e that doesn't quit afterwards?

**Comment by Paulchen232** [comment]
no

**Comment by Fealo** [comment]
Also no way to access the command line
