### ISSUE TITLE
Delete and restore message

### ISSUE THREAD

**Issue by MrShoxruxbek** [vysheng/tg#1657]
restore_msg nor working. I am tring to restore but output shows me error:
FAIL: 38: can not find command 'restore_msg'.

And then How Can I delete message. command msg not works with message. If I give id of the message then it deletes message, Problem is It does not show id of message. what should I do.

**Comment by Paulchen232** [comment]
The command restore_msg is away.
You see the id with the option -N.

**Comment by MrShoxruxbek** [comment]
> The command `restore_msg` is away.
> You see the id with the option -N if you send a message.
