### ISSUE TITLE
Can I restore deleted message from my chat. I read you can restore messages within 1 hour. does not it?

### ISSUE THREAD

**Issue by MrShoxruxbek** [vysheng/tg#1658]

**Comment by qezz** [comment]
This would be very interesting functionality. Could you provide a link to this information?

**Comment by MrShoxruxbek** [comment]
restore_msg <msg-seqno> - restores delete message. Impossible for secret chats. Only possible short time (one hour, I think) after deletion

**Comment by MrShoxruxbek** [comment]
Here is the link:

**Comment by MrShoxruxbek** [comment]
> This would be very interesting functionality. Could you provide a link to this information?

Here is the link which I read the information.
https://github.com/vysheng/tg/blob/master/README.md

I got it from README.md in this repository.

**Comment by qezz** [comment]
@MrShoxruxbek did this help https://github.com/vysheng/tg/issues/1657 ? You could also check the https://github.com/vysheng/tg/issues/1522
