### ISSUE TITLE
make order error

### ISSUE THREAD

**Issue by Winorlose4** [vysheng/tg#1670]
tgl/crypto/rsa_pem_openssl.c:41:6: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’
   ret->e = unwrap_bn (TGLC_bn_new ());
      ^~
tgl/crypto/rsa_pem_openssl.c: In function ‘TGLC_rsa_n’:
tgl/crypto/rsa_pem_openssl.c:52:1: error: control reaches end of non-void function [-Werror=return-type]
 RSA_GETTER(n);
 ^~~~~~~~~~
tgl/crypto/rsa_pem_openssl.c: In function ‘TGLC_rsa_e’:
tgl/crypto/rsa_pem_openssl.c:53:1: error: control reaches end of non-void function [-Werror=return-type]
 RSA_GETTER(e);
 ^~~~~~~~~~

**Comment by Winorlose4** [comment]
ubuntu OS

**Comment by Paulchen232** [comment]
#1653

**Comment by Winorlose4** [comment]
,

Paulchen232 <notifications@github.com> 于 2020年7月27日周一 04:15写道：
