### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by raghavgururajan** [vysheng/tg#1697]
@vysheng 
I am packaging tgl into [Guix](https://guix.gnu.org). But there has been 324 commits to master since 1.3.1 pre-release. Could you make a new release tag please?

**Comment by banderlog** [comment]
it is abandoned thing

**Comment by banderlog** [comment]
Similar projects:
+ https://github.com/erayerdin/tgcli (python, active)
+ https://github.com/shelomentsevd/telegramgo (go, abandoned)

**Comment by raghavgururajan** [comment]
@banderlog 
Sorry to hear to that.
Thanks for the links.
