### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by jsfdez** [vysheng/tg#173]
Hello,

Currently I'm working on porting tg-cli to Windows Command Line. Are you interested on it?

At the current stage is building without problems and I'm debugging it to fix some problems related (I think) with WSAPoll & poll differences.

**Comment by robocop249** [comment]
Another +1 for windows

**Comment by them3gabyte** [comment]
+1 For windows port

**Comment by jsfdez** [comment]
I created a command line utility (works on Windows). You can check it here: https://github.com/jsfdez/telegram-qt

It's based on telegram-qt from @Kaffeine .

It allows to send messages to a phone number or a group from commandline.

**Comment by Walkman100** [comment]
> Visual Studio 2013

I don't see an `SLN`, nor a `.CXproj` file. How do I compile it? Does it have to be compiled on Linux?

**Comment by Kaffeine** [comment]
Walkman100: The files was been removed (I'm not sure why). Try to checkout commit ad8fb266078a978c1e045cb68c319396410d1074 (it is HEAD^^^ ATM).

**Comment by Walkman100** [comment]
Thanks, worked for me :+1:

**Comment by Ramizak** [comment]
I'd be happy to see some Step by Step guide ( could use images too ) for compiling from the beginning ( such as cmake and ,,, to the end) I'd really appreciate it

**Comment by jsfdez** [comment]
Hello,

to build with Visual Studio you need to create the project solution with *qmake -tp vc -recursive*.

There are 2 dependencies can be resolved manually or with nuget for Visual Studio: OpenSSH and Zip. The easy way it's using nuget.

**Comment by Ramizak** [comment]
I'm just getting incompatibility error for it.
Just installed NuGet tool also installed SDK Update 4 for Visual Studio 2012 
but still there is migration issues and errors : 

	Message
telegram-qt\TelegramQt.vcxproj: The application which this project type is based on was not found. Please try this link for further information: http://go.microsoft.com/fwlink/?prd=12395&pver=11&sbp=ProjectTypeDeprecated&plcid=0x409&clcid=0x409&ar=MSDN&sar=ProjectCompatibility&o1=8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942

**Comment by jsfdez** [comment]
VS2012 has an very old compiler. Only VS2013 is supported.

**Comment by Ramizak** [comment]
thanks for info/ I will download VS2013 now.

**Comment by khansotudeh** [comment]
can run this lib with nodejs or php or Python in windows????
