### ISSUE TITLE
'[] is typing ...'

### ISSUE THREAD

**Issue by kenniki** [vysheng/tg#340]
Is it possible to implement a command that sends 'started typing' and one that sends 'stopped typing'? 

I'd like to use that to make some kind of 'working' display for the Telegram bot I'm currently developing as a wrapper around telegram-cli.

**Comment by luckydonald** [comment]
Are the new ones, like 'User is uploading a photo' implemented?
(See the [SendMessageAction](https://core.telegram.org/type/SendMessageAction))
This, being a scripting feature it would be enough to have one command with documented parameters, like:
``` shell
send_action [action-number] [keep] <peer>
```
With ``action-number``:    

``0``: 	Cancel all previous actions 
``1``: 	User is typing
``2``: 	User is recording a video
``3``: 	User is uploading a video
``4``: 	User is recording a voice message
``5``:  	User is uploading a voice message
``6``:  	User is uploading a photo
``7``:  	User is uploading a file
``8``:  	User is selecting a location to share
``9``:  	User is selecting a contact to share

And ``keep`` (default is 1): 
 
``0``:  	Status will vanish after some seconds (like it does at the moment)
``1``:  	Status will stay until ``send_action 0`` is called to cancel

**Comment by luckydonald** [comment]
Also in my opinion it does not make sense at all to stop the ``send_typing`` command.
This does not make sense for projects.
This will need threading, and a command pipeline- even in the simplest projects:
Receive a message, send typing to show we are working on it, calculate our stuff.
Then be done with calculation, stop typing, send result.

But instead we need to set up some thread, to call ``send_typing`` regularly. Over and over again.

**Comment by luckydonald** [comment]
And like asked above, @vysheng , I still wonder what is the library vs. the client?

**Comment by luckydonald** [comment]
Added that, It just have to be approved.

**Comment by luckydonald** [comment]
The pull request is outdated.
I am still interrested in the feature, to be able to optionally append a status integer.
@vysheng: Would that feature get included?
I'd create a new pull request for the current code.

**Comment by sladec** [comment]
+1

**Comment by luckydonald** [comment]
This is merged, maybe @kenniki can close this issue?

**Comment by kenniki** [comment]
Will do!
