### ISSUE TITLE
Not working on mac os x

### ISSUE THREAD

**Issue by farhaanbukhsh** [vysheng/tg#369]
I tried running it on mac .I use homebrew everytime I am able to run ./configure but It is saying make requires a target  and then ./telegram -k tg-server.pub this comand is not able to execute. Please look into the issue

**Comment by noma4i** [comment]
Just built tg but after accepting phone number it's just doing nothing:

Telegram-cli uses libtgl version 1.2.0
I: config dir=[/Users/noma4i/.telegram-cli]
phone number: +61xxxxxxxxx
>

and thats all.

any ideas?

**Comment by vysheng** [comment]
Try latest version, fixed this bug today (at least hope so)

**Comment by noma4i** [comment]
latest commit in my build is ca6942724a11029858f1aced8b7fb1be2dc90eae "fixed indents"

**Comment by vysheng** [comment]
nope, I fixed it about one hour ago.

**Comment by vysheng** [comment]
commit 1977eb

**Comment by noma4i** [comment]
yep. It works )
