### ISSUE TITLE
Receivin messages

### ISSUE THREAD

**Issue by nfgferreira** [vysheng/tg#372]
Hello, folks. Thanks for this very helpful software. I installed it in a virtual machine and it used to transmit messages for days without a glitch. I am using a socket (-P option) in order to do that.

Now I want to receive messages in my VM  and I am not sure what is the best way to do that. I browsed the internet and found that page: https://mattze96.safe-ws.de/blog/?p=658. It shows there is a on_msg_receive callback function that can be used in order to do what I want. I guess that I can substitute the example code by some socket transmission, but I am not sure that is the best track to follow (I have not written a single Lua line in my whole life up to now).

Is there any more straightforward way to pull received messages from telegram-cli to a local client other than creating a Lua script?

Thanks in advance.

**Comment by vysheng** [comment]
use main_session command. All updates will be redirected to this socket

**Comment by nfgferreira** [comment]
Thank you, sir.

I am afraid I did not understand quite right your answer though. To which socket the messages will be directed to?

I ended up implementing a Lua callback, which was not a big pain after all. It looks like this:
```lua
function on_msg_receive (msg)
    if msg.date < now then
        return
    end
    if msg.out then
        return
    end
    local socket = require("socket")
    local ip = assert(socket.dns.toip("127.0.0.1"))
    local udp = assert(socket.udp())
    assert(udp:sendto('[' .. msg.from.print_name .. ']' .. msg.text, ip, 11000))
end
```
