### ISSUE TITLE
Compiling telegram

### ISSUE THREAD

**Issue by kalacy** [vysheng/tg#379]
I wanted to compile a new telegram application.   I followed the following steps - 

1. git clone https://github.com/vysheng/tg.git
2. sudo apt-get install libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev
3. cd tg
4. ./configure

Got error "configure: error: no libevent found"

5. sudo apt-get install libevent-dev
6. make

Get error "make:   *** No rule to make target 'tgl/scheme.tl' needed by 'auto/scheme.tl'. Stop"

Any ideas why I can't compile telegram.

Thank You

**Comment by ivansabik** [comment]
Worked for me also with

```shell
$ git clone --recursive https://github.com/vysheng/tg.git
$ ./configure --disable-json
```
Thanks!

**Comment by ivansabik** [comment]
I also needed:

```shell
$ sudo apt-get install libjansson*
```

**Comment by arielb2** [comment]
fedora:
yum install libevent-devel
thanks.

**Comment by zhilevan** [comment]
I am on Centos 7 , after  yum install  libevent-devel  face `configure: error: no libreadline found
` how resolve it?

**Comment by zhilevan** [comment]
I resolve it with sudo yum install readline-devel
after that I face

configure: error: No libconfig found. Try --disable-libconfig
Error. Exiting.
:(

**Comment by arielb2** [comment]
Can you try yum install libconfig-devel ?

**Comment by authorized13** [comment]
libconfig-devel  ?

**Comment by mohammadmdp** [comment]
How can i get rid of this error in "WINDOWS"? not everyone uses linux you know? I'm using Git-Bash

**Comment by codefuhrer** [comment]
@mohammadmdp https://github.com/vysheng/tg/blob/master/README-Cygwin.md

**Comment by irisyasmeen** [comment]
I got this error
checking for library containing backtrace... none required
checking for event_base_new in -levent... no
configure: error: no libevent found
Error. Exiting.

**Comment by rogerionsouza** [comment]
On recent versions of Linux, if this doesn't work, then you may have to install the readline development libraries with a command like:

      yum install readline-devel         (RPM-based systems)
      apt-get install libreadline5-dev   (Debian-based systems)

**Comment by alastor81** [comment]
`mika@alastor:~/tg$ ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for library containing clock_gettime... none required
checking for library containing backtrace... none required
checking for event_base_new in -levent... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking event2/event.h usability... yes
checking event2/event.h presence... yes
checking for event2/event.h... yes
checking for pkg-config... /usr/bin/pkg-config
checking whether compiling and linking against OpenSSL works... yes
checking if zlib is wanted... yes
checking for inflateEnd in -lz... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for rl_save_prompt in -lreadline... no
configure: error: no libreadline found
mika@alastor:~/tg$ apt list --installed | grep libreadline

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libreadline-dev/kali-rolling,now 7.0-3 amd64 [installed]
libreadline5/kali-rolling,now 5.2+dfsg-3+b1 amd64 [installed,auto-removable]
libreadline7/kali-rolling,now 7.0-3 amd64 [installed]
mika@alastor:~/tg$`
