### ISSUE TITLE
Compiling problem on raspberry pi

### ISSUE THREAD

**Issue by Arrheniu2** [vysheng/tg#384]
Hi i have no problems compiling it on my cubietruck (debian arm), but it doesnt work on my raspberry pi

i can make 19 object files, but it seems auto.c cant be compiled, the "make" command never ends, i launched make with the -d option and i can see it launches a child and waits for the response but the PID of the child is dead with no return.

The data:
uname -a
Linux raspa 3.10.25+ #622 PREEMPT Fri Jan 3 18:41:00 GMT 2014 armv6l GNU/Linux

make -d
 Considering target file 'objs/auto/auto.o'.
       File 'objs/auto/auto.o' does not exist.
        Pruning file 'auto/auto.c'.
        Pruning file 'auto/constants.h'.
        Pruning file 'auto/auto-header.h'.
       Finished prerequisites of target file 'objs/auto/auto.o'.
      Must remake target 'objs/auto/auto.o'.
gcc -I. -I. -g -O2  -I/usr/local/include -I/usr/include -I/usr/include -I/usr/include/lua5.2   -DHAVE_CONFIG_H -Wall -Wextra -Werror -Wno-deprecated-declarations -fno-strict-aliasing -fno-omit-frame-pointer -ggdb -Wno-unused-parameter -fPIC -iquote ./tgl -c -MP -MD -MF dep/auto/auto.d -MQ objs/auto/auto.o -o objs/auto/auto.o auto/auto.c
Putting child 0xc71c40 (objs/auto/auto.o) PID 1049 on the chain.
Live child 0xc71c40 (objs/auto/auto.o) PID 1049

How can i detect the problem? i dont know the command to compile just the auto.c file (i dont know how to pass the compiler the dependencies an so..

thanks in advance

**Comment by vysheng** [comment]
It just requires to much RAM to compile (not sure, why). Try to ./configure --disable-extf

**Comment by Arrheniu2** [comment]
Finally i made it, thanks!
