### ISSUE TITLE
Non verbose mode in group chats

### ISSUE THREAD

**Issue by Kazaii** [vysheng/tg#386]
Hey there,

This is a feature request. I love the way this client functions; However, I find it annoying to use in a group chat. I just had many of my friends migrate to Telegram a few days ago, and now when I join the chat group of 8-12 people, I find myself extremely distracted by the following prompts, in a typical chat:
- Chat marked as read 0 outbox 3 inbox messages
-James is online
-James is typing (for 5 lines)
James: ayyy lmao
-James is offline
-Liza is online
-Liza is offline
-Liza is online
-Liza is typing (for another 3 lines)
-Liza: hehe
-Liza is offline

so on and so forth. By this point, I just close the terminal window and go back to the desktop app. Perhaps this is a limitation, or I just don't understand that I could tweak a config file to fix this; Yet, I find it as a deal breaker, when it comes to group chats. I would love if someone could help me out with this. Or perhaps a silent mode could be added, when focusing on chats.

**Comment by vysheng** [comment]
try to set log_level (-l 0 at startup, for example)

**Comment by Kazaii** [comment]
That did the trick, thanks!! ~ Issue resolved.

Now if I can get everyone to stop sending stickers for 30 lines straight T.T

**Comment by gwangjinkim** [comment]
Can you please add this to the general explanations of the commands? In my view this is very important piece of information for users! I had to search around a while to get it. This belongs to basic instructions how to use telegram-cli!
