### ISSUE TITLE
Multiple accounts or from number

### ISSUE THREAD

**Issue by anishmenon** [vysheng/tg#396]
How can i run telegram instance from multiple numbers

/bin/telegram-cli -k tg-server.pub

uses one of the registered number . But is there any tweak to switch to another from_number ? . i'm using Ubuntu

**Comment by danielberlin** [comment]
Configure profiles as shown in filee ```config.sample``` (but don't use binlog). For each number, you need an identical profile subfolder. Then run it with

```telegram-cli -p profile2```

You can omit ```-k server.pub``` if you put the key in ```/etc/telegram-cli/server.pub```.

**Comment by anishmenon** [comment]
can you gimme the template for  profile2 ?

**Comment by danielberlin** [comment]
Do you have a working installation? Then just rename that profile dir to profile1. Then start ```telegram-cli``` to create a fresh profile with your new number, and finally move that new profile to profile2.

**Comment by anishmenon** [comment]
profile2 = {
  config_directory = "conf/profile";
  test = true;
  msg_num = true;
};


i've created conf/profile dir
and 

telegram-cli -p profile2 -k server.pub  -p profile2


it didint  asked me for the new number verification

**Comment by vysheng** [comment]
please, show contents of ~/.telegram-cli/config

**Comment by anishmenon** [comment]
# This is an empty config file
# Feel free to put something here


profile2 = {
  config_directory = "pathto/conf/profile2";
  test = true;
  msg_num = true;
};

**Comment by vysheng** [comment]
delete 'test = true' line.

**Comment by danielberlin** [comment]
I don't understand https://github.com/vysheng/tg/issues/396#issuecomment-70368672

Just create a fresh profile somewhere, maybe as a different user who doesn't have .telegram-cli directory yet, and then use that profile as your profile2 (rename accordingly).

Then you can use ```telegram-cli -p profile1``` or ```telegram-cli -p profile1``` simultaneously to use either one or the other number. Store the server.pub key file in /etc/telegram-cli or in the local folder to avoid typing ```-k server.pub``` all the time.

**Comment by anishmenon** [comment]
Now the problem is fixed .. thank you .

**Comment by ymys** [comment]
I was confuse how to use multi-account telegram. But then, I tried this:
1. Edit config file (located at .telegram-cli). This is the sample:
newprofilename1 = {
config_directory = ".telegram-cli/foldername";
msg_num = true;
};

Note: I tried to use number as myprofile name, but it was error on that line. So I assume, profile name couldn't start with number. Foldername can.

2. ./telegram-cli -k server.pub -p newprofilename1
This command should create new folder called "foldername" located at ./telegram-cli (the path as in config).

3. Wait for a couple secs. My connection was good, but always have to wait patiently before it asked for number to be authenticated. 

Thanks for thread starter!

**Comment by nimix3** [comment]
Hi,

I want to Open both two profile in TCP socket mode (as daemon) separately, I tried :

/usr/src/tgcli/bin/telegram-cli -p Profile1 -k /usr/src/tgcli/server.pub -p Profile1 -U root -dWP 7778 --json &
/usr/src/tgcli/bin/telegram-cli -p Profile2 -k /usr/src/tgcli/server.pub -p Profile2 -U root -dWP 7777 --json &

But when I use it in my code , with sending message : "msg User_Name blah blah" User receive message from Profile1 two times !!!

How Can I do?

**Comment by nimix3** [comment]
Problem solved by removing the option "U root" :)
Thanks...

**Comment by alimousavi84** [comment]
is this way limited in number of account ?
