### ISSUE TITLE
I need the List of options.

### ISSUE THREAD

**Issue by abosami2000** [vysheng/tg#409]
Hi guys ,

I need the list of options like -k ..etc

can any one write /explain?

for example I didn't want to showing the status if the user change photo .. Like:
User XXX updated photo

thanks

**Comment by danielberlin** [comment]
Type `telegram-cli -h` to get all options with brief explanation.

The status is updated by the backend, currently not possible to hide that and may be not possible in general unless they enable that in the backend.

**Comment by abosami2000** [comment]
yes , it works.
Thank you
