### ISSUE TITLE
Few important requests

### ISSUE THREAD

**Issue by Somepony** [vysheng/tg#415]
I'm writing some kind of telegram-cli wrapper and API in PHP.

Example code (without OOP and other cool things)
```php
$descriptorspec = [
    '0' => ['pipe', 'r'], # stdin
    '1' => ['pipe', 'w'], # stdout
    '2' => ['file', 'error-output.txt', 'a'] # stderr
];

$process = proc_open('/home/ubuntu/workspace/bot/src/tg/bin/telegram-cli -k /home/ubuntu/workspace/bot/src/tg/tg-server.pub -I -C', $descriptorspec, $pipes, realpath('./'), array());

stream_set_blocking($pipes[0], 0);
stream_set_blocking($pipes[1], 0);

if (!is_resource($process))
{
	throw new \Exception('An error occurred');
}

$status = proc_get_status($process);

while ($status['running'])
{
    while ($output = fgets($pipes[1]))
    {
        if (strpos($output, '>>>'))
        {
            if (preg_match('/\[(\d{2}:\d{2})\]\s{2}?(chat#\d+)\s(user#\d+).{5}(.*)/', $output, $matches))
            {
               if (preg_match('/^!say\s+(.*)$/', $matches[4], $text))
               {
                    fwrite($pipes[0], "msg {$matches[2] '{$text[1}}'" . PHP_EOL);
               }
            }
        }
    }
}
```

It works fine until i'm try to send some cyrillic symbols [а-яёА-ЯЁ]: cli just ignores them and sends nothing, but msg {$matches[2]} (chat#id) lefts in STDIN. And then it sticks to next message like that:
![nah](https://cloud.githubusercontent.com/assets/3610163/5989786/f8692202-a9a3-11e4-8925-6e5d14319df9.png)

And another one thing where development stuck.
I'm reading STDOUT line-by-line so i'm able to read only first line of incomming text (message, chat/user information, etc).
Could you please add something like command-line argument (-N) that will replace newlines by some char at output for easily parsing (like \n or #n).

And sorry for my English of course.

**Comment by Tit6ka** [comment]
```
Could you please add something like command-line argument (-N) that will replace newlines by some char at output for easily parsing (like \n or #n).
```
It could be very useful.

**Comment by VasNesterov** [comment]
I too like idea to make a new cli argument for disable text wrapping.

**Comment by Somepony** [comment]
To send cyrillic you should disable readline library (-R cli argument).
Use stream_get_contents() instead of fgets()

**Comment by jack-peterson1** [comment]
الان اشکان کونی میاد کپی میزنه اینو چچچچچچچچچچچچچچچ

**Comment by jack-peterson1** [comment]
@بهروزیاقی
