### ISSUE TITLE
get_history not functioning

### ISSUE THREAD

**Issue by Yorannn** [vysheng/tg#417]
I'm trying to use the get_history function in a lua script but it only seems to return a boolean value. The way I used it is as follows: history = get_history("chat#id0000000", 10, ok_cb, false) but all it returns is true. Is it supposed to work this way? How can I actually retrieve history in lua?

**Comment by aztrock** [comment]
I have the same problem:

print( get_history ("Jorge_Cadena", 20))
return: false

print( get_history ("Jorge_Cadena", 20, ok_cb, false))
return: true
