### ISSUE TITLE
Typelib file for namespace 'Notify' (any version) not found

### ISSUE THREAD

**Issue by realtebo** [vysheng/tg#424]
Executing this 

```
 /tg/bin/telegram-cli -k /tg/tg-server.pub -s /tg/test.lua -P 3333
```

I got this error

```
HI, this is lua script
*** lua: /usr/share/lua/5.2/lgi/namespace.lua:149: Typelib file for namespace 'Notify' (any version) not found
```

how to fix it? I'm on ubuntu 10.04

I've previously used

```
apt-get install git libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev libevent-dev make lua-lgi glib-2.0 
```

Please, note that I've added lua-lgi and glib-2.0 to suggested installation to avoid other 'not found' errors, but I'm not able to fix this one.

And please update the read.me to include these 2 packages, because they're often missing on ubuntu

**Comment by realtebo** [comment]
I followed this guide (in German !!!!) 

    http://www.tutorials-raspberrypi.de/webserver/ueber-telegram-messenger-raspberry-pi-steuern/

So I removed all code inside this

    -- Notification code {{{
    }}}

But now when I run and try to send 'ping'  I got this 

     *** lua: /tg/test.lua:54: attempt to call global 'get_title' (a nil value)

**Comment by saragojo** [comment]
In order to make the script work,
i removed the lines you see in the diff output below.
test.lua is the modified version of test.lua.orig.  Lua version 5.2 on debian wheezy:

```
root@kirkberry:~/tg# diff test.lua test.lua.orig
59a60,68
> local lgi = require ('lgi')
> local notify = lgi.require('Notify')
> notify.init ("Telegram updates")
> local icon = os.getenv("HOME") .. "/.telegram-cli/telegram-pics/telegram_64.png"
> 
> function do_notify (user, msg)
>   local n = notify.Notification.new(user, msg, icon)
>   n:show ()
> end
69a79
>   do_notify (get_title (msg.from, msg.to), msg.text)
```

**Comment by realtebo** [comment]
@saragojo I'll try, but... how can I 'install' the missing typeLib? 
I must tell I've no idea of what a typeLib is

**Comment by Goty** [comment]
from raspbian you need libnotify-bin

**Comment by realtebo** [comment]
@Goty: thanks a lot, I'll try ASAP

**Comment by Ernillew** [comment]
Same error at Ubuntu 14.04 TLS. Need libnotify-dev to install for fix it.
