### ISSUE TITLE
Authenticate phone number in daemon mode

### ISSUE THREAD

**Issue by pfcgarcia** [vysheng/tg#443]
Hello,

I've done everything as per the instructions how to run telegram-cli daemonized. achat service is working now but I can't do anything as it shows me error:

    *** error for query #6125390819437034496: #401 AUTH_KEY_UNREGISTERED (HANDLED)
    *** error for query #6125390819666553856: #401 AUTH_KEY_UNREGISTERED (HANDLED)

Also I can see "phone number: " prompt in logs. Is tg trying to request phone number from me in daemon mode? How to login using phone number via socket, is there any special function? Or is there any way to use some .telegram-cli directory with already authenticated user?

Thanks.

**Comment by obetools** [comment]
Hi, are you get solution for this issue ? because i have the sama issue, its happen after i remove config file in .telegram-cli folder and recompile, is there any function for re-register ?
