### ISSUE TITLE
Connect width PHP to daemon

### ISSUE THREAD

**Issue by FerX** [vysheng/tg#450]
**congratulations, great program.**
I was able to get it started in **daemon mode**.
In the shell telnet works.
In **PHP** I tested socket connection, but do not know the parameters, and how to write and read.
Can anyone help me?

**Comment by dgazotto** [comment]
Maybe, it can help you.. https://github.com/zyberspace/php-telegram-cli-client

**Comment by FerX** [comment]
Thanks.
