### ISSUE TITLE
How to send image from Lua script

### ISSUE THREAD

**Issue by Epowerj** [vysheng/tg#462]
How do you send an image from a lua script?

Here is what I'm doing right now:
I have a bot.lua file with the following code -

    function on_msg_receive (msg)
       if msg.text == "/sendimage" then
          print("sending image")
          send_photo(msg.from.print_name, '/home/epowerj/image.jpg')
       end
    end

Then I run tg with 

    ./tg/bin/telegram-cli -k tg/tg-server.pub -s ./bot.lua -l 1

This doesn't work. I am sure that the function is launched because the "sending image" message shows up in the cosole, but I don't receive any images.

Any help would be appreciated, and thanks in advance.

**Comment by yagop** [comment]
This may help you:

```lua
function get_receiver(msg)
  if msg.to.type == 'user' then
    return 'user#id'..msg.from.id
  end
  if msg.to.type == 'chat' then
    return 'chat#id'..msg.to.id
  end
  if msg.to.type == 'encr_chat' then
    return msg.to.print_name
  end
end

function on_msg_receive (msg)
   local receiver = get_receiver(msg)
   if msg.text == "/sendimage" then
      print("sending image")
      local file_path = '/home/epowerj/image.jpg'
      send_photo(receiver, file_path, ok_cb, false)
   end
end
```
