### ISSUE TITLE
Configuration: "./telegram-cli -k tg-server.pub" is not asking for any phone number

### ISSUE THREAD

**Issue by Maverick-GH** [vysheng/tg#468]
Hi,
I've already installed Telegram CLI several times without problem. But, this time, I can't configure Telegram with my phone number. That's because CLI is not asking me about a phone number. It is just showing the CLI command prompt, where I can for instance type "show_license" but nothing else works. How can I "force" CLI to configure itself ?

Thanks

**Comment by yagop** [comment]
Wait a while

**Comment by Maverick-GH** [comment]
I have tried majn workaround, in issue #440, but yet no success. That's what I see from log (-vvvvv):

Telegram-cli version 1.2.0, Copyright (C) 2013-2015 Vitaly Valtman
Telegram-cli comes with ABSOLUTELY NO WARRANTY; for details type `show_license'.
This is free software, and you are welcome to redistribute it
under certain conditions; type `show_license' for details.
Telegram-cli uses libtgl version 1.2.0
I: config dir=[/home/user/.telegram-cli]
 *** public key 'tg-server.pub' loaded successfully
 *** Couldn't open public key file: /etc/telegram-cli/server.pub
 *** Can not load key /etc/telegram-cli/server.pub
 *** public key 'tg-server.pub' loaded successfully
 *** DC1 '' update: 149.154.175.50:443
 *** DC2 '' update: 149.154.167.51:443
 *** DC3 '' update: 149.154.175.100:443 (majn workaroung #440)
 *** DC4 '' update: 149.154.167.91:443
 *** DC5 '' update: 149.154.171.5:443
 *** fail connection: reason: ping timeout
 *** Lost connection to server... 149.154.167.91:80
 *** fail connection: reason: ping timeout
 *** Lost connection to server... 149.154.167.51:80
 *** fail connection: reason: ping timeout
 *** Lost connection to server... 149.154.175.100:80
 *** fail connection: reason: ping timeout
 *** Lost connection to server... 149.154.171.5:80
 *** fail connection: reason: ping timeout
 *** Lost connection to server... 149.154.175.50:80
 *** fail connection: reason: ping timeout
 *** Lost connection to server... 149.154.171.5:25
 *** fail connection: reason: ping timeout
 *** Lost connection to server... 149.154.167.51:25
 *** fail connection: reason: ping timeout
 *** Lost connection to server... 149.154.175.100:25
 *** fail connection: reason: ping timeout
 *** Lost connection to server... 149.154.167.91:25
 *** fail connection: reason: ping timeout
 *** Lost connection to server... 149.154.175.50:25
 *** fail connection: reason: ping timeout
 *** Lost connection to server... 149.154.175.100:443
 *** fail connection: reason: ping timeout
 *** Lost connection to server... 149.154.167.51:443

But... I 'CAN' ping any of those servers. 
I'm afraid I'm lost here. Please help.
Thanks

**Comment by Maverick-GH** [comment]
@yagop,

I've been waiting for quite a long time now. I'm not sure it will ever work.

**Comment by Maverick-GH** [comment]
I'm stuck here. Please help.

**Comment by majn** [comment]
@Maverick-GH 
If you've made sure that
1) You updated the tgl.h header and use the recompiled version
2) Deleted all your .telegram-cli files
I have no idea, what could cause this. I assume this bug report belongs to your comments in https://github.com/vysheng/tg/issues/440 , right?

**Comment by Maverick-GH** [comment]
@majn , I think I figured out what is going on. It is some kind of network problem. I'll close this issue because my problem is not Telegram CLI related.
Thank you very much for your time. Thanks to everyone who helped.

**Comment by oniyou** [comment]
> I have tried @majn workaround, in issue #440, but yet no success. That's what I see from log (-vvvvv):
> 
> Telegram-cli version 1.2.0, Copyright (C) 2013-2015 Vitaly Valtman
> Telegram-cli comes with ABSOLUTELY NO WARRANTY; for details type `show_license'. This is free software, and you are welcome to redistribute it under certain conditions; type`show_license' for details.
> Telegram-cli uses libtgl version 1.2.0
> I: config dir=[/home/user/.telegram-cli]
> *** public key 'tg-server.pub' loaded successfully
> *** Couldn't open public key file: /etc/telegram-cli/server.pub
> *** Can not load key /etc/telegram-cli/server.pub
> *** public key 'tg-server.pub' loaded successfully
> *** DC1 '' update: 149.154.175.50:443
> *** DC2 '' update: 149.154.167.51:443
> *** DC3 '' update: 149.154.175.100:443 (@majn workaround #440)
> *** DC4 '' update: 149.154.167.91:443
> *** DC5 '' update: 149.154.171.5:443
> *** fail connection: reason: ping timeout
> *** Lost connection to server... 149.154.167.91:80
> *** fail connection: reason: ping timeout
> *** Lost connection to server... 149.154.167.51:80
> *** fail connection: reason: ping timeout
> *** Lost connection to server... 149.154.175.100:80
> *** fail connection: reason: ping timeout
> *** Lost connection to server... 149.154.171.5:80
> *** fail connection: reason: ping timeout
> *** Lost connection to server... 149.154.175.50:80
> *** fail connection: reason: ping timeout
> *** Lost connection to server... 149.154.171.5:25
> *** fail connection: reason: ping timeout
> *** Lost connection to server... 149.154.167.51:25
> *** fail connection: reason: ping timeout
> *** Lost connection to server... 149.154.175.100:25
> *** fail connection: reason: ping timeout
> *** Lost connection to server... 149.154.167.91:25
> *** fail connection: reason: ping timeout
> *** Lost connection to server... 149.154.175.50:25
> *** fail connection: reason: ping timeout
> *** Lost connection to server... 149.154.175.100:443
> *** fail connection: reason: ping timeout
> *** Lost connection to server... 149.154.167.51:443
> 
> But... I 'CAN' ping any of those servers.
> I'm afraid I'm lost here. Please help.
> Thanks

unfortunately，in above ips，I can ping successfully two of them. Because my server is in China where many abroad ips have been baned by Gov, So I tried to make a proxy to access these ips that I can curl these ips sucessfully. But ping is still not successful.  Proxy server can only proxy http,https and socks but icmp. How can I do? looking forward to your reply~
