### ISSUE TITLE
Error on OSX 10.10.3, xCode 6.3

### ISSUE THREAD

**Issue by roman-kosov** [vysheng/tg#475]
main.c:836:5: error: '**builtin___snprintf_chk' will always overflow destination
      buffer [-Werror,-Wbuiltin-memcpy-chk-size]
    snprintf (serv_addr.sun_path, 108, "%s", unix_socket);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/secure/_stdio.h:57:3: note: expanded from macro 'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS**)
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: **\* [objs/main.o] Error 1

any ideas?

**Comment by arielyang** [comment]
yes, the same with me.

**Comment by d0xin** [comment]
have a same bug on os x 10.10.3

**Comment by oldmanpushcart** [comment]
how to fix it?

**Comment by matti** [comment]
I have no idea, but as a lolcode experiment I just commented that line out. works.

**Comment by d0xin** [comment]
You may turn off the check while compiler build it in Makefile.in.
Just replace "-Wbuiltin-memcpy-chk-size" by "-Wno-builtin-memcpy-chk-size".

it works for me.

**Comment by matti** [comment]
Thanks, that works.

**Comment by i-like-a-boss** [comment]
Yes. Works!

**Comment by alekseysotnikov** [comment]
Couldn't find string "-Wbuiltin-memcpy-chk-size" in Makefile.in

**Comment by alekseysotnikov** [comment]
Workaround:
1. Need add "-Wbuiltin-memcpy-chk-size" to the Makefile.in
3. ./configure
4. make

**Comment by bb010g** [comment]
@i-like-a-boss You don't need to mark it as "FIX !!"; the closing of the issue shows that the issue was resolved. However, you may want to reopen and wait to close it until it's been fixed in the repo and not through a manual hack.

**Comment by i-like-a-boss** [comment]
@bb010g np
