### ISSUE TITLE
dialog_list() call doesn't work from LUA

### ISSUE THREAD

**Issue by SyRenity** [vysheng/tg#484]
The dialog_list() function call doesn't do anything when called from LUA (it does works when typed in CLI

**Comment by LukeLR** [comment]
It does return false in my case, see #480. But yes, it does not do what it should.

**Comment by Requilence** [comment]
get_dialog_list() is async function. Use first param to specify callback function and parse the result inside

**Comment by SyRenity** [comment]
Thanks!

Same for contact_list?

**Comment by Requilence** [comment]
As far as I remember, yes. The same Telegram account can work on different devices simultaneously. Because of this, these requests are async. You can cache results by yourself when the LUA script is started.

**Comment by SyRenity** [comment]
@Requilence thanks, will give it a try

**Comment by SyRenity** [comment]
@Requilence Thanks, I confirm that get_dialog_list(cb, value) works fine, at least in the test branch.

get_contact_list, unfortunately does not.

**Comment by sargashteh** [comment]
@Requilence what is (cb, value)  for get_dialog_list() ???
