### ISSUE TITLE
Command line Arguments

### ISSUE THREAD

**Issue by LukeLR** [vysheng/tg#494]
Hey folks,
I wonder if there's a list with all possible command line arguments together with an explaination for each. Would be nice to get an overview on what's possible, and could be research basis for using tg-cli. I think there is no, or have I missed something?

**Comment by vysheng** [comment]
bin/telegram-cli -h?

**Comment by LukeLR** [comment]
Okay, thanks!

**Comment by LukeLR** [comment]
For later reference: I created a wiki page in this repository listing all the available command line options. You can find it here: https://github.com/vysheng/tg/wiki/Telegram-CLI-Arguments Therefore this is closed now. Closes #494.
