### ISSUE TITLE
Refusing incoming netcat-connections

### ISSUE THREAD

**Issue by LukeLR** [vysheng/tg#495]
Hi, I have some kind of weird bug right now I can't solve.
Running tg-cli on my Rasberry Pi, I don't have access to the server console all the time, so I want to control the tg-cli-daemon over network. Therefore, I added the "-p 1234" command to my telegram startup script, sending commands via "nc localhost 1234" works. Next step was to send from a remote computer to the Raspberry Pi, as well via "nc 192.168.xxx.xxx 1234", but the Connection is refused. There is no firewall or anything on that Pi that is blocking the incoming connection, as proved by listening manually on the Pi with "nc -l 1234" and sending a message from my remote computer works. Any ideas?
![screen shot 2015-04-27 at 15 00 27](https://cloud.githubusercontent.com/assets/3177243/7348039/4f4ddb5c-ecee-11e4-96bf-eb8904ae231e.png)
![screen shot 2015-04-27 at 15 00 42](https://cloud.githubusercontent.com/assets/3177243/7348041/4f503e4c-ecee-11e4-9eef-da6222aa217d.png)
![screen shot 2015-04-27 at 15 00 59](https://cloud.githubusercontent.com/assets/3177243/7348038/4f4d9f0c-ecee-11e4-8e17-b914586539b0.png)
![screen shot 2015-04-27 at 15 01 11](https://cloud.githubusercontent.com/assets/3177243/7348040/4f4e3430-ecee-11e4-9c5b-db265426a9f7.png)

**Comment by vysheng** [comment]
For safety reasons I listen only loopback port. I'll add some key to change this behavour. You can now make temp fix:
change 
```serv_addr.sin_addr.s_addr = htonl (0x7f000001);```
to
```serv_addr.sin_addr.s_addr = INADDR_ANY;```
at main.c:812 (or maybe some line around).

**Comment by LukeLR** [comment]
Okay, thanks! I'll give it a try!

**Comment by LukeLR** [comment]
Did you add some key to change this behavior? Behause I'm still using the custom code in my Main.c

**Comment by LukeLR** [comment]
A key `--accept-any-tcp` was added to the telegram cli. When passing this key, the telegram cli doesn't just answers tcp connections from localhost, but from the network too. Thanks! This closes #495
