### ISSUE TITLE
Dialog_list

### ISSUE THREAD

**Issue by ViriatoOundil** [vysheng/tg#512]
For some reason, when i use it to display a list of all dialogs it will show me up to 100 registers(when i know that i have even more), it's like there is a limit on query somewhere. Why? And how can I delete that limit? (if i can)

**Comment by vysheng** [comment]
in test branch you can type 'dialog_list <limit>'.

**Comment by ViriatoOundil** [comment]
thx!! And the last question. Any idea about how to get chat id?

**Comment by vysheng** [comment]
chat_info?

**Comment by ViriatoOundil** [comment]
Yes, I know the theory, but, how can I get the parameter <chat>? I want to get it from telegram cli exactly like i can do with user_info and contact_list or dialog_list

**Comment by vysheng** [comment]
I don't understand.  What's wrong with ```chat_info <chat_title>``` ?

**Comment by ViriatoOundil** [comment]
That I have no way to get "<"chat_title">"

**Comment by LukeLR** [comment]
I think you get Chat_title from the dialog list ;) Or you know it before, since it usually doesn't change ;)

**Comment by ViriatoOundil** [comment]
Ou yes, sorry, i'm dumb. sorry vor everythign and thx for replies!
