### ISSUE TITLE
trouble with tg when compiling

### ISSUE THREAD

**Issue by ordinaryegi** [vysheng/tg#523]
hi
after cloning git repo and then ./configure i don't find any mistakes but when execute make it's failed and showing error 
make: *** No rule to make target 'tgl/scheme.tl', needed by 'auto/scheme.tl'
it's something wrong?

i'm using ubuntu 15.04

**Comment by vysheng** [comment]
did you use --recursive key to git clone? if not run ```git submodule update --recursive --init```

**Comment by ordinaryegi** [comment]
it works, thanks

2015-05-15 16:56 GMT+07:00 vysheng <notifications@github.com>:

> did you use --recursive key to git clone? if not run git submodule update
> --recursive --init
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/vysheng/tg/issues/523#issuecomment-102351209>.
>



-- 
ubuntu user # 30968
