### ISSUE TITLE
How to send message to zabbix from tg-cli?

### ISSUE THREAD

**Issue by MillerMax** [vysheng/tg#526]
Hello guys. I have some problem with sending from Telegram to Zabbix.
I use this guideline - http://tobias.ws/blog/zabbix-com-notificacoes-pelo-telegram/. 
Nothing to help.
When i test it, give this. http://higgs.rghost.ru/8fHSFZnRr/image.png
I use another solution for example http://paste2.org/H89yw59z.
This is solutions is work, but not work with zabbix. I dont know, why.
Request for solutions. 
Best Regards.

**Comment by luckydonald** [comment]
Your command is ```msg <peer> "message"``` right?

**Comment by MillerMax** [comment]
luckydonald: Sure.

**Comment by gnumoksha** [comment]
@MillerMax I wrote the guideline, but it was in portuguese, because my english its bad.

I have a look into your screenshot and commands isn't correct. You can translate the article for your language?

For now, see https://github.com/vysheng/tg/issues/518#issuecomment-101931971

Note: today more early i tried compile the project and i received error, try use the same commit that in article (eg. git checkout -b gozabbix 01f5d9a3b671edc15a5cff285601115845489985)

**Comment by MillerMax** [comment]
Yes, i can translate this article on Russian. My English is bad too.

It is doesent work.
I experimented, with key -e

    telegram -k /etc/telegram-cli/tg-server.pub -WR -I -e "msg user#XXXXXXXX Hello"
   
  Thats not work. I dont  understand why does not it work.
  Just not sent message.
  ScreenShoot: http://plasmon.rghost.ru/6RhfbnLGs/image.png

**Comment by gnumoksha** [comment]
@MillerMax I can send message with the version 1.2.0 (the same as yours). I have write a resume here https://gist.github.com/gnumoksha/a95f237d82733ce1f748

Try send a message over telegram desktop https://desktop.telegram.org/

**Comment by MillerMax** [comment]
From telegram desktop or web version is ok.
I get this. 
http://higgs.rghost.ru/8pggbCmTg/image.png

**Comment by gnumoksha** [comment]
@MillerMax I just perform the procedure in the ubuntu 14.04.2 LTS with success. Did you install the required packages?

Eg.
```
apt-get install libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev libevent-dev libjansson-dev make git -y
```

Is "normal" get some error in first execution

**Comment by MillerMax** [comment]
Ok. Checkout thats all.
I l do from this instructions https://gist.github.com/gnumoksha/a95f237d82733ce1f748
And i get this : http://tau.rghost.ru/7s5h7qnyC/image.png
What am i doing wrong ? :)

**Comment by gnumoksha** [comment]
@MillerMax I can't see error. That is ok. The contact does not received the message?

**Comment by MillerMax** [comment]
@gnumoksha No errors man. But message dont sent.

**Comment by gnumoksha** [comment]
@MillerMax try:
```
./telegram-cli -k tg-server.pub -c telegram.config -vvvv
[...]
> msg user#12345678 "please, go"
 *** reply_id=0, disable=0
[08:11]  user#12345678 <<< please, go
User user#12345678 is deleting typed message
```

And paste here

**Comment by MillerMax** [comment]
@gnumoksha You know, first run be successful. Message has been sent.
But, second attempt not.
http://paste2.org/kwpjsDaN

**Comment by gnumoksha** [comment]
@MillerMax you have many faults in communication and finally you got #400 PEER_ID INVALID. See https://github.com/vysheng/tg/issues/534#issuecomment-103839128

**Comment by MillerMax** [comment]
@gnumoksha 
Man this problem is resolve. 
Thank you very much.

**Comment by MillerMax** [comment]
But i still cant send this to telegram from zabbix. :(

**Comment by luckydonald** [comment]
For the commandline issue see #414 or #406, i think they might be related.

**Comment by luckydonald** [comment]
@gnumoksha  The user change failes:
> ``` change_user_group: can't find the user telegramd to switch to```

(which seems related to this trick: https://github.com/vysheng/tg/issues/414#issuecomment-100908038)
You probably just have to create the user.

**Comment by MillerMax** [comment]
@luckydonald Thats is not problem. I can send message from cli. But notifications not send from zabbix.

**Comment by gnumoksha** [comment]
@millermax ser this http://tobias.ws/blog/zabbix-com-notificacoes-pelo-telegram/#comment-14649 paste The outuput here

@luckydonald this warning is acceptable, but i think that error is in zabbix user

**Comment by luckydonald** [comment]
What is the exact command you use for zabbix?

**Comment by MillerMax** [comment]
@gnumoksha 
Hmm. The problem beginning to be understood a little bit.
Log from tailf /var/log/zabbix-server/zabbix_server.log | tee /tmp/telegram_debug.log | grep -ni telegram : 
http://paste2.org/6Cb9z6Zn

**Comment by MillerMax** [comment]
@gnumoksha I resolve a problem, man. 
I restarted on new server, from @gnumoksha guide line, and all works correctly. 
Thank you for resolve this issues.
