### ISSUE TITLE
Not sending messages with -e from crontab

### ISSUE THREAD

**Issue by andreaskoelsch** [vysheng/tg#530]
Hi,
I just downloaded the most recent version of telegram, hoping it would work now... I just want to send messages via crontab. When I execute a script it works. When I execute it from crontab it does not work. However, it used to work in older versions, since I did not change the script.
Here the script:

    #!/bin/bash
    /home/user/tg/bin/telegram-cli -p cron -k /home/user/tg/tg-server.pub -W -e "msg contact text"

works when executed, but if I run it via crontab it behaves like there are no "" in the end
Any ideas?

For now I will stick with the old version where it works, but I want to upgrade, since the old one produces a memory leak which I hope is fixed already.

**Comment by LukeLR** [comment]
You should check in which users name cron executes telegram, because this could cause problems when loading the configuration file which is by default located in the corresponding user's home directory (had the same problem when I started working with telegram via cron)

**Comment by andreaskoelsch** [comment]
I run it from the same user's cron which I use to run it from bash so I think it should be the same user. And as said before, exactly this worked in older versions
Cheers

Am 18. Mai 2015 00:42:15 MESZ, schrieb Lukas Rose <notifications@github.com>:
>You should check in which users name cron executes telegram, because
>this could cause problems when loading the configuration file which is
>by default located in the corresponding user's home directory (had the
>same problem when I started working with telegram via cron)
>
>
>
>> On 17 May 2015, at 11:57 pm, andreaskoelsch

**Comment by gnumoksha** [comment]
@andreaskoelsch see https://github.com/vysheng/tg/issues/518#issuecomment-101931971

**Comment by andreaskoelsch** [comment]
Okay,
so the trick was to enable -R. Don't know why that became necessary, but it works now.
Thanks!
