### ISSUE TITLE
Videos sent as files

### ISSUE THREAD

**Issue by cosmonawt** [vysheng/tg#538]
When sending a video, either from CLI or LUA script, it shows up in a chat as a file, not an actual video.
There is no preview there, and no play button.
Am I maybe doing something wrong?

**Comment by LukeLR** [comment]
You probably should add a screenshot of how the video looks like when sent by the cli. There is a known issue that file extensions are lost when sending files from tg-cli, don't know if it got fixed some time. Probably it's that what is causing your problem? As always, I recommend to check if the problem persists on the test branch, or if it maybe got fixed there (you need to clone the test branch, of course, probably delete your old download of the master branch, just in case, and then recompile your client. Furthermore, deleting the configuration from ~/.telegram-cli might help, if any bugs occur).

**Comment by luckydonald** [comment]
Is the new ```send_*``` function the same for every ```*``` , decided only by ending?
Maybe there is an error? [interface.c:743-761](https://github.com/vysheng/tg/blob/3ced7bbb27b7ec2f8005b298c95289aba12dffb7/interface.c#L743-L761)

**Comment by schossel** [comment]
https://github.com/vysheng/tg/issues/457

At the 4th or 5th comment is a explanation how to get it working.

**Comment by evantreborn** [comment]
The issue I have is not related to that, though. I am using the newest version (1.3.1).
Videos are sent fine, with extension and a name.
However, Telegram has two different types of sending video: as a video or as a file.
When sent as a video, it shows up in the chat on other clients with a play button and can be played directly from within the app.
When sent as file, it is not shown that way. It looks like a regular file (name, suffix and filesize).

This screenshot shows the difference of both types. 
It is the same video, sent first as video, later as file. 

![image](https://cloud.githubusercontent.com/assets/10501668/7749024/56d9a8ee-ffca-11e4-9c5c-2a429d8026da.jpg)

**Comment by jonnywilliamson** [comment]
@evantreborn Yes - I know what you are talking about and I have the same issue. With latest commit (in Master - as it's ahead of TEST at the moment) I get an Error 38 when trying to SEND_VIDEO instead of using DOCUMENT

```shell
> send_document Jonathan_Williamson /home/vagrant/fileuploads/small.mp4
1181 [22:39]  Jonathan Williamson <<< [document small.mp4: type=video/mp4 size=374KiB]

User Jonathan Williamson offline (was online [2015/05/20 22:39:53])
User Jonathan Williamson online (was online [2015/05/20 22:44:54])

> send_video Jonathan_Williamson /home/vagrant/fileuploads/small.mp4
FAIL: 38: can not parse string arg #2
```

**Comment by schossel** [comment]
Sorry if I misunderstood your problem. Then I can't help.

**Comment by evantreborn** [comment]
I got the same error 38. I could avoid it by adding a caption as a third argument.

**Comment by jonnywilliamson** [comment]
@evantreborn Ahh - yes indeed, I get the same. If I add a caption, the video is now sent, BUT still arrives as if I sent a document...ie no preview like there is if you use SEND_PHOTO

```shell
> send_video Jonathan_Williamson /home/vagrant/fileuploads/small.mp4 caption
1186 [13:20]  Jonathan Williamson <<< [video small.mp4: type=video/mp4 size=100x100 duration=100 size=374KiB]
```

**Comment by luckydonald** [comment]
Until it gets fixed, just supply an empty caption (empty quotes):
```hurr
send_video luckydonald /path/to/video.mp4 ""
```
![screenshot_2015-05-21_um_15_52_13](https://cloud.githubusercontent.com/assets/2737108/7749946/7b6da2f8-ffd1-11e4-91a8-46a2c7ce89cc.png)

**Comment by jonnywilliamson** [comment]
@luckydonald yes - but that's only 50% of the issue. The actual send_video function seems to be duplicating the send_document function when in fact it should be very subtlety different. 

Note @evantreborn images above - they show the two differences perfectly.

**Comment by luckydonald** [comment]
@jonnywilliamson You are talking about the ``` send_video``` CLI command or lua?
The CLI commands sets a diffenent parameter while calling ```_do_send_file```:
[interface.c:743-761](https://github.com/vysheng/tg/blob/3ced7bbb27b7ec2f8005b298c95289aba12dffb7/interface.c#L743-L761):
![3ced7bbb27b7ec2f8005b298c95289aba12dffb7 interface.c:743-761](https://cloud.githubusercontent.com/assets/2737108/7750734/282607fc-ffd6-11e4-9876-4bdcf51ef4c7.png)
(as of commit 3ced7bbb27b7ec2f8005b298c95289aba12dffb7)

**Comment by jonnywilliamson** [comment]
For me definitely it happens when using CLI. Haven't tested with lua.

**Comment by luckydonald** [comment]
Also the parsing error is because of the file parameter before that string. 
**Edit:** Found the bug.

**Comment by tchabaud** [comment]
Is there a fix when using lua API ?

**Comment by DmitrySkripunov** [comment]
Hi, guys! I'm still have the issue. I send video file, but receive a document. 
I use docker container weibeld/ubuntu-telegram-cli
May be there is any updates about the bug, or, some new version of the container?

**Comment by Paulchen232** [comment]
Which command you use in Telegram-CLI?

**Comment by Paulchen232** [comment]
Work it with smaller videos?

**Comment by DmitrySkripunov** [comment]
Yes it works with files until 10mb (I only tested them).
Command I use:
`send_video username /path-to-file ""`

**Comment by Paulchen232** [comment]
Perhaps it works with kenorb-contrib/tg.
Is a forg from telegram-cli and is not dead.
https://github.com/kenorb-contrib/tg

**Comment by DmitrySkripunov** [comment]
Ok, thank you, I will check!
