### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ilteoood** [vysheng/tg#545]
Hi, I'm trying to compile this client on a Raspberry PI, first model.
This is the output of ./configure:
http://pastebin.com/xmFWS6Rb
While this is the makefile:
http://pastebin.com/Nf9LEsQU
After 45 minutes, and without any type of error, I can find the telegram-cli executable inside the /bin directory but I can't execute it because of segmentation fault. This is the only output that the program give to me.
I've tried to use ./configure --disable-extf, but in this case I've some problems with the makefile, this is the output:
http://pastebin.com/vwUX0HjF

There is a way to fix it? Is possible to cross compile it using an x86 PC?

**Comment by flagrandall** [comment]
Hi, I have exactly the same problem.

**Comment by kenniki** [comment]
Post the build log.

**Comment by ilteoood** [comment]
This is the build log:
http://pastebin.com/SCg4gefz

**Comment by flagrandall** [comment]
Hi, how can I take the build log?

**Comment by flagrandall** [comment]
ilteoood,
 have you solved the problem somehow? 
 how can I take the build log?
thanks and bye!

**Comment by LukeLR** [comment]
The build log is basically printed on screen in your console when building. You should, indeed, give passing the verbosity-argument to your compiler a try.

**Comment by vysheng** [comment]
Do you have enougth RAM?

**Comment by ilteoood** [comment]
Yes, I think..
Anyway, I made a fresh install of Raspbian and now it works!
One question: is it possible to run a new instance of telegram-cli with the "-e" argument without kill the other one?

**Comment by LukeLR** [comment]
When you're running them from different configurations it should not be a problem :) You can, of course, set up a second instance of tg-cli, log in with the same account as in the first, but save that to a different configuration file. Then you can use two instances simultaneously, I guess ;)

**Comment by flagrandall** [comment]
I still have the segmentation fault problem. Here my build log:
http://pastebin.com/6i74fiAe

**Comment by vysheng** [comment]
please, show me backtrace

**Comment by flagrandall** [comment]
how? :)

**Comment by vysheng** [comment]
it should be printed to stdout on crash

**Comment by flagrandall** [comment]
![segmentation](https://cloud.githubusercontent.com/assets/12561748/7860615/dea3f236-054a-11e5-84e5-1a73915bde95.PNG)

**Comment by flagrandall** [comment]
Is it right?
p.s.: I'm working on OSMC
thankyou very much

**Comment by vysheng** [comment]
How much free RAM do you have?

**Comment by flagrandall** [comment]
![mem](https://cloud.githubusercontent.com/assets/12561748/7861205/fae78e0e-054e-11e5-8fd0-d48666278506.PNG)

**Comment by flagrandall** [comment]
![mem2](https://cloud.githubusercontent.com/assets/12561748/7861283/83c6a2e6-054f-11e5-8950-46c8cf2c6d22.PNG)

**Comment by vysheng** [comment]
and memory overcommit?

**Comment by flagrandall** [comment]
how can I enable it in raspberry ?

**Comment by vysheng** [comment]
```echo 1 > /proc/sys/vm/overcommit_memory```

**Comment by flagrandall** [comment]
![overc](https://cloud.githubusercontent.com/assets/12561748/7861954/55724d42-0553-11e5-8efe-071a4815e8ab.PNG)

**Comment by vysheng** [comment]
use sudo or su

**Comment by vysheng** [comment]
use su

**Comment by vysheng** [comment]
or echo 1 | sudo tee /proc/sys/vm/overcommit_memory

**Comment by flagrandall** [comment]
solved typing :
- su
- echo 1 > /proc/sys/vm/overcommit_memory

Thank you very much!
