### ISSUE TITLE
Stuck to 'Connecting..' until program is restarted when connection is reset.

### ISSUE THREAD

**Issue by earendil02** [vysheng/tg#547]
When my connection is reset Telegram is no longer able to reconnect, the message "Connecting.." is displayed in the bottom left corner, and obviously it doesn't update anymore. It remains stuck in this condition until I quit (via the menu on the indicator panel) and restart it. Simply closing the window doesn't help.
An option to manually force a reconnection maybe could help.

**Comment by Walkman100** [comment]
Sounds exactly like you made the issue in the wrong repo, this is the repo for `telegram-cli`, a command line interface client that cannot have any menus or indicator panels.

**Comment by earendil02** [comment]
sorry, my fault, I followed the wrong link.
