### ISSUE TITLE
FAIL: 38: can not parse arg #1

### ISSUE THREAD

**Issue by ortreum** [vysheng/tg#548]
Hello,

I had a contact "Ich".

I renamed it with
rename_contact Ich p x12345

I've tried to send a message
msg p x123456 blahh
FAIL: 38: can not parse arg #1

I've tried to delete the contact
del_contact p x123456 blahhh
FAIL: 38: can not parse arg #1

I've tried to delete it the linux way
del_contact "p x123456" blahhh
Then I've listed the contacts
contact_list
p x123456

The contact is still there.

**Comment by MerlinElMago** [comment]
Can confirm the bug.
I'm unable to find out what the reason is. I use the tool from a Bash script and I am unable to reproduce the problem, it's randomly there (but unfortunately most of the time).
I am calling: telegram-cli -k tg-server.pub -U root -RD -e "msg user text"

**Comment by nleo** [comment]
`msg p_x123456` or try tab completion

**Comment by Walkman100** [comment]
The name you put as name to rename to at this command:
```
rename_contact Ich p x12345
```
is not the same as the name you put here:
```
msg p x123456 blahh
```
Two problems:
- there is a 6 at the end of your `msg` to-name
- spaces must be replaced by underscores (`_`) for `msg`

so your `msg` command should be (if the contacts name is `p x12345`):
```
msg p_x12345 blahh
```

**Comment by LukeLR** [comment]
If you miss out the underscores, your command might be interpreted, that you want to message "x123456" to your contact "p", so therefore spaces in arguments are (as usual) not allowed, since they split the arguments.

**Comment by ortreum** [comment]
First, thank you for this helpful answer.
Second, the 6 at the end was because I worte p12345 as an example.
Third, please add examples to the readme like 
firstname lastname
user = firstname_lastname

or better:
change the contact_list output to the username with underscores so that people allways know what to do.

Fourth, the help list is sooo ling that I have to scroll upwards in putty but it allways jumps back down after less than a minute. How should anyone be able to read the to of this list?

Thank you :)

**Comment by jweslley** [comment]
+1 @ortreum

**Comment by Mugen4** [comment]
I have this bug too :(

```
Telegram-cli version 1.3.1, Copyright (C) 2013-2015 Vitaly Valtman
Telegram-cli comes with ABSOLUTELY NO WARRANTY; for details type `show_license'.
This is free software, and you are welcome to redistribute it
under certain conditions; type `show_license' for details.
Telegram-cli uses libtgl version 2.0.1
I: config dir=[/root/.telegram-cli]
>
FAIL: 38: can not parse modifier
>
```

**Comment by PavelApostol** [comment]
Ребята, вот такой фикс!
> msg Pavel_Belyaev "hello world!"
FAIL: 38: can not parse arg #1
> contact_list
Pavel Belyaev
> msg Pavel_Belyaev "hello world!"
[08:47]  Pavel Belyaev <<< hello world!

Нужно сперва получить контакт-лист, а потом отправлять сообщения, тогда будет адекватно отрабатывать имя отправителя.

**Comment by LukeLR** [comment]
Hey, I don't understand russian, but this looks like the feature that you need to call contact list before the chat names are loaded. This is not an issue or a bug but a wanted functionality, and it has been asked quite often until now. Please check #251, #267, #274, #346, #355, #397, #399, #406, #411, #414, #483, #518, #534, #625, #700, #707 for more details.

And there are not many people here reading this issues, so you should always write English to ensure that the others are able to understand your problem, since there won't be many people speaking Russian here ;)

**Comment by PavelApostol** [comment]
Hi, The sender and receiver have the same name, and msg command return error:)
> 1 авг. 2015 г., в 15:46, Lukas Rose <notifications@github.com> написал(а):
> 
> Hey, I don't understand russian, but this looks like the feature that you need to call contact list before the chat names are loaded. This is not an issue or a bug but a wanted functionality, and it has been asked quite often until now. Please check #251, #267, #274, #346, #355, #397, #399, #406, #411, #414, #483, #518, #534, #625, #700, #707 for more details.
> 
> And there are not many people here reading this issues, so you should always write English to ensure that the others are able to understand your problem, since there won't be many people speaking Russian here ;)
> 
> 
>

**Comment by DenisVS** [comment]
> Hi, The sender and receiver have the same name, and msg command return error:)
Hi, same behavior.
_ Writen on English, although Russian is my first language)) _

**Comment by rbadillarx** [comment]
Hi guys:
As you may guess I have the same error message; but I this may help. 
By the way this have worked for me on interactive mode.
as soon I loggin 
telegram -k /etc/telegram/server.pub -C -v -l ./telegram-cli/misesion.wri
I: config dir=[/trabajo/monitor/.telegram-cli]
 *** Couldn't open public key file: tg-server.pub
 *** Can not load key tg-server.pub
 *** adjusting CLOCK_MONOTONIC delta to -0.683616
 *** adjusting CLOCK_MONOTONIC delta to -0.675012
 *** adjusting CLOCK_MONOTONIC delta to 0.491828
 *** adjusting CLOCK_MONOTONIC delta to -0.188051
I send the dialog_list
them I can send image; docs and msg to the user or chat that I need.

If I logged and send commands the error FAIL: 38: can not parse arg #1
happens to almost any command.

So my solution is issue dialog_list command before anything and must work fine. Hope that helps you!

**Comment by rebroad** [comment]
I am also getting this issue. Not sure why this issue has been closed.
