### ISSUE TITLE
broadcast-command is not working

### ISSUE THREAD

**Issue by theArch2** [vysheng/tg#561]
Hi,

i'm testing this wonderful piece of art. 
At the moment i'm struggling with the broadcast command. I use it like:
```
> broadcast Contact_Name1 Contact_Name2 "message"
```
but there are no outgoing messages. If i write a broadcast at the same time over the official app at my smartphone, i get this output on the console:
```
[22:34] Contact_Name1 <<< message
[22:34]  Contact_Name2 <<< message
[22:34]  Contact_Name3 <<< message
```

Is it not implemented yet?

**Comment by vysheng** [comment]
thx, fixed that

**Comment by bidak** [comment]
This command is not working for me.

**Comment by theArch2** [comment]
Update to latest version and build again, its working fine :)
