### ISSUE TITLE
Compilation in RHEL

### ISSUE THREAD

**Issue by querquobad** [vysheng/tg#568]
Hello I am trying to compile in Red Hat Enterprise Linux AS release 4 (yes... I know it is old but it is my production server and I cannot update it :-{| )

I ran into some problems and some I have fixed. Here is what I have done:
Configure did not find readline libraries... looking at config.log it was that termcap wasn't being loaded solved it by adding LIBS=-ltermcap to configure command.
Make complained about -iquote argument missing in gcc, yes... that is because the compiler is too old so since it is only the compiler I installed gcc4 alongside with the binary name gcc4 and putting n the configure command CC=gcc4

Now I get this error:

gcc4 objs/tl-parser.o objs/tlc.o objs/crc32.o -ltermcap -L/usr/local/lib -L/usr/lib -L/usr/lib -L/usr/kerberos/lib -L/usr/kerberos/lib64   -rdynamic -ggdb -levent -lz -levent -lrt -lm   -lreadline -lssl -lcrypto -lgssapi_krb5 -lkrb5 -lcom_err -lk5crypto -lresolv -ldl -lz   -o bin/tl-parser
objs/tl-parser.o(.text+0x14bc): En la función `new_tree_node_tl_field':
tgl/tl-parser/tl-parser.c:914: undefined reference to `rpl_malloc'
objs/tl-parser.o(.text+0x15ec): En la función `new_tree_node_var_value':
tgl/tl-parser/tl-parser.c:911: undefined reference to `rpl_malloc'
objs/tl-parser.o(.text+0x176c): En la función `new_tree_node_tl_var':
tgl/tl-parser/tl-parser.c:901: undefined reference to `rpl_malloc'
objs/tl-parser.o(.text+0x189c): En la función `new_tree_node_tl_constructor':
tgl/tl-parser/tl-parser.c:897: undefined reference to `rpl_malloc'
objs/tl-parser.o(.text+0x19cc): En la función `new_tree_node_tl_type':
tgl/tl-parser/tl-parser.c:894: undefined reference to `rpl_malloc'
objs/tl-parser.o(.text+0x216b):tgl/tl-parser/tl-parser.c:982: more undefined references to `rpl_malloc' follow
objs/tl-parser.o(.text+0x66f3): En la función `tl_add_constructor':
tgl/tl-parser/tl-parser.c:1169: undefined reference to `rpl_realloc'
objs/tl-parser.o(.text+0x6771):tgl/tl-parser/tl-parser.c:1156: undefined reference to `rpl_malloc'
objs/tl-parser.o(.text+0x67df):tgl/tl-parser/tl-parser.c:1130: undefined reference to `rpl_malloc'
objs/tl-parser.o(.text+0x79ca): En la función `tl_parse':
tgl/tl-parser/tl-parser.c:2704: undefined reference to `rpl_malloc'
objs/tl-parser.o(.text+0x7af8): En la función `tl_init_parse_file':
tgl/tl-parser/tl-parser.c:340: undefined reference to `rpl_malloc'
collect2: ld devolvió el estado de salida 1
make: *** [bin/tl-parser] Error 1

Looking at:
https://github.com/vysheng/tg/issues/320
https://github.com/vysheng/tg/issues/144

For me it seems that adding "ac_cv_func_malloc_0_nonnull=yes ac_cv_func_realloc_0_nonnull=yes" to th configure command should make the trick but...

gcc4 -I. -I. -I./tgl -g -O2  -I/usr/local/include -I/usr/include -I/usr/include -I/usr/kerberos/include   -DHAVE_CONFIG_H -Wall -Wextra -Werror -Wno-deprecated-declarations -fno-strict-aliasing -fno-omit-frame-pointer -ggdb -Wno-unused-parameter -fPIC -iquote ./tgl -c -MP -MD -MF dep/mtproto-common.d -MQ objs/mtproto-common.o -o objs/mtproto-common.o tgl/mtproto-common.c
cc1: warnings being treated as errors
tgl/mtproto-common.c: In function ‘tgl_pad_aes_encrypt’:
tgl/mtproto-common.c:381: aviso: implicit declaration of function ‘AES_ige_encrypt’
make: *** [objs/mtproto-common.o] Error 1

Looking at 
https://github.com/vysheng/tg/issues/318
https://github.com/vysheng/tg/issues/315
I tried to disable the warnings being treated as errors with CFLAGS=-Wno-error but the same error popped so I tried CFLAGS=-w but...

gcc4 objs/main.o objs/loop.o objs/interface.o objs/lua-tg.o objs/json-tg.o libs/libtgl.a -ltermcap -L/usr/local/lib -L/usr/lib -L/usr/lib -L/usr/kerberos/lib -L/usr/kerberos/lib64   -rdynamic -ggdb -levent -lz -levent -lrt -lm   -lreadline -lssl -lcrypto -lgssapi_krb5 -lkrb5 -lcom_err -lk5crypto -lresolv -ldl -lz   -o bin/telegram-cli
libs/libtgl.a(queries.o)(.text+0x29da): En la función `encrypt_decrypted_message':
tgl/queries-encrypted.c:49: undefined reference to `AES_ige_encrypt'
libs/libtgl.a(queries.o)(.text+0x91ba): En la función `send_part':
tgl/queries.c:1555: undefined reference to `AES_ige_encrypt'
libs/libtgl.a(queries.o)(.text+0xb903): En la función `download_on_answer':
tgl/queries.c:2255: undefined reference to `AES_ige_encrypt'
libs/libtgl.a(queries.o)(.text+0xf7b2): En la función `tgl_do_act_set_password':
tgl/queries.c:3408: undefined reference to `SHA256'
libs/libtgl.a(queries.o)(.text+0xf8bf):tgl/queries.c:3429: undefined reference to `SHA256'
libs/libtgl.a(queries.o)(.text+0x1027b): En la función `tgl_pwd_got':
tgl/queries.c:3603: undefined reference to `SHA256'
libs/libtgl.a(structures.o)(.text+0x7fdb): En la función `decrypt_encrypted_message':
tgl/structures.c:1184: undefined reference to `AES_ige_encrypt'
libs/libtgl.a(mtproto-common.o)(.text+0x1582): En la función `tgl_pad_aes_encrypt':
tgl/mtproto-common.c:381: undefined reference to `AES_ige_encrypt'
libs/libtgl.a(mtproto-common.o)(.text+0x15e7): En la función `tgl_pad_aes_decrypt':
tgl/mtproto-common.c:389: undefined reference to `AES_ige_encrypt'
collect2: ld devolvió el estado de salida 1
make: *** [bin/telegram-cli] Error 1

this looks like openssl library but it IS installed...

[david@localhost tg]$ /sbin/ldconfig -p | grep ssl
	libxmlsec1-openssl.so.1 (libc6,x86-64) => /usr/lib64/libxmlsec1-openssl.so.1
	libxmlsec1-openssl.so.1 (libc6) => /usr/lib/libxmlsec1-openssl.so.1
	libxmlsec1-openssl.so (libc6,x86-64) => /usr/lib64/libxmlsec1-openssl.so
	libxmlsec1-openssl.so (libc6) => /usr/lib/libxmlsec1-openssl.so
	libssl3.so (libc6) => /usr/lib/libssl3.so
	libssl.so.4 (libc6,x86-64) => /lib64/libssl.so.4
	libssl.so.4 (libc6) => /lib/libssl.so.4
	libssl.so.2 (libc6) => /lib/libssl.so.2
	libssl.so (libc6,x86-64) => /usr/lib64/libssl.so
	libgnutls-openssl.so.11 (libc6,x86-64) => /usr/lib64/libgnutls-openssl.so.11
	libgnutls-openssl.so.11 (libc6) => /usr/lib/libgnutls-openssl.so.11
	libevent_openssl-2.0.so.5 (libc6,x86-64) => /usr/local/lib/libevent_openssl-2.0.so.5

So I got stuck here...
¿Any ideas?

**Comment by vysheng** [comment]
Do you have headers? (/usr/include/openssl/*.h) They are often included in *-devel or *-dev packages (can say how it should be in RHEL).

**Comment by querquobad** [comment]
Solved, the problem was that openSSL was too old and didn't implement the AES_ige_encrypt
Updating the OpenSSL library solved it. Be sure to have OpenSSL 1.x.
