### ISSUE TITLE
Get all values in msg (Python)

### ISSUE THREAD

**Issue by DevPGSV** [vysheng/tg#574]
How can I get all values in any message I receive (in python)?
In def on_msg_receive(msg) i've tried:

    pp.pprint(msg) # 
Got this error: http://pastebin.com/CUKxK5fN

I also tried:

    for k, v in msg.items():
      print (k)
With this code, every time I receive a message I get:
    
    AttributeError: 'tgl.Msg' object has no attribute 'items'

Then I tried:

    print (vars(msg))
And I got:

    TypeError: vars() argument must have __dict__ attribute

So... is there any way to loop through the message received?
And... what is the type of "msg"? I thought it was a dictionary, but

    type(msg)
prints nothing, and the erros show it's type is "tgl.Msg"

**Comment by DevPGSV** [comment]
I forgot:
I'm in Debian
I have Python 2.7.3

**Comment by DevPGSV** [comment]
if "text" in msg:
Gives this error:

    TypeError: argument of type 'tgl.Msg' is not iterable

**Comment by DevPGSV** [comment]
Found it.
I thought msg was a dict, but it's not.

**Comment by rnhmjoj** [comment]
It's an object. I still haven't figured out how to serialize it to a JSON object.

**Comment by DevPGSV** [comment]
I managed to do it.
Lets see if I find the code XD

**Comment by rnhmjoj** [comment]
@DevPGSV  Thank you

**Comment by DevPGSV** [comment]
Here it is:
https://github.com/DevPGSV/telegram-bot-plus/blob/master/bot/utils.py

msg2dict and peer2dict

The code has a lot of bugs, but it works.
The "rec" parameter... I had to use it to avoid parsing "user" inside "user" inside "user" infite times.

**Comment by rnhmjoj** [comment]
That's exactly my problem: it's seems to be a recursive structure.

**Comment by DevPGSV** [comment]
perhaps the solution is.... to avoid calling "peer2dict" inside "peer2dict" :)
If in peer2dict:


if type(v) == tgl.Peer:
    dict[k] = "not serialized peer"

Problem solved XDDD
