### ISSUE TITLE
Telegram-cli crashed after read an invalid image.

### ISSUE THREAD

**Issue by psycholyzern** [vysheng/tg#578]
As the title said, my telegram crashed with this error

![](http://s13.postimg.org/h6h8amsmf/Screenshot_2015_06_01_09_32_05.png)

Here I attach the message that crashing telegram-cli

![](http://s14.postimg.org/7u4hieqld/Pics_Art_1433123528963.jpg)

I hope you can fix this because it conpletely crashing telegram-cli and you cant start telegram-cli until you delete that message via telegram app.

**Comment by LukeLR** [comment]
What is the content of that Message? Just line breaks? Or is it even empty?

**Comment by psycholyzern** [comment]
Sorry. I couldn't help further. I had to delete those messages in order to start my telegram-cli again.
I tried to forward the message to backup it but it failed. The message marked with red "!" (In telegram android)

**Comment by LukeLR** [comment]
Mhh, I just read, you're calling it an "image" in your issues' title?
Btw: what are these plugins your cli is loading? Where are they from?

**Comment by psycholyzern** [comment]
Yah.. An image. Let me tell from the whole story.

I am using telegram bot (https://github.com/yagop/telegram-bot)

A bunch of people are using my bot in their group. They also put @jaconda (which is a bot too) in that group.

They queried "/img cake" and jaconda will return an image. Somehow, @jaconda returned message like I told earlier. I said it is an image because @jaconda returned that message after user queried /img

And I can confirm it is such a media because, in telegram android app, if you tap on the message,  it will open as image. But you cant save it to gallery.

You cant copy, forward, or view that image.

**Comment by vysheng** [comment]
can you forward this message to me?

**Comment by LukeLR** [comment]
I think he deleted the malicious message. But maybe this can be reproduced?

**Comment by vysheng** [comment]
It looks like some bad image that server sent as empty. It's strange, though, because server checks image.

**Comment by psycholyzern** [comment]
@vysheng can't be forwarded. It will show red "!" On the message. You can try chat telegram.me/jaconda and type in ```/img cake``` (cake is the one which gave me that message)
You cant get it instantly, need many retries because it happened randomly

**Comment by psycholyzern** [comment]
@vysheng please check your telegram. I invited you into a group and reproduced the message from jaconda.

**Comment by vysheng** [comment]
thx, will check now

**Comment by vysheng** [comment]
added temporary fix. Looks like server-side problem, since message states that message contains photo, but has constructor photo_empty.

**Comment by psycholyzern** [comment]
Thanks a lot @vysheng . I appreciate that :D

**Comment by noma4i** [comment]
Sorry about that. This is cached image but looks like it expired in server cache. *jaconda team*
