### ISSUE TITLE
Crash with Jaconda or Something

### ISSUE THREAD

**Issue by Jamuzb** [vysheng/tg#579]
SIGNAL received
h./bin/telegram-cli(print_backtrace+0x20)[0x468720]
./bin/telegram-cli(termination_signal_handler+0x64)[0x4687a4]
/lib/x86_64-linux-gnu/libc.so.6(+0x36d40)[0x7fd255b2dd40]
./bin/telegram-cli(print_media+0x3c)[0x4721fc]
./bin/telegram-cli(print_message+0x1fb)[0x4763db]
./bin/telegram-cli(print_message_gw+0x8d)[0x476f8d]
./bin/telegram-cli[0x49cc82]
./bin/telegram-cli[0x49d95e]
./bin/telegram-cli[0x4903cb]
./bin/telegram-cli(tglq_query_result+0x10f)[0x489c5f]
./bin/telegram-cli[0x482e92]
./bin/telegram-cli[0x4a397b]
/usr/lib/x86_64-linux-gnu/libevent-2.0.so.5(event_base_loop+0x754)[0x7fd256d4cf24]
./bin/telegram-cli(net_loop+0xa4)[0x469844]
./bin/telegram-cli(loop+0x17f)[0x46ab3f]
./bin/telegram-cli(main+0x291)[0x467091]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7fd255b18ec5]
./bin/telegram-cli[0x46718b]
8266981 [09:21]  Ц5 Jaconda >>> 

Anyone help on this?
Vysheng can you help me on this issue?

**Comment by yagop** [comment]
Seems the same as #578

**Comment by Jamuzb** [comment]
Thank yagop
