### ISSUE TITLE
ImportError in tg-test.py

### ISSUE THREAD

**Issue by idreamsi** [vysheng/tg#582]
Hi
When run "sudo python tg-test.py"  the following error appears :

File "tg-test.py" , line 1 , in <module>
import tgl
ImportError : No module named tgl

What is the problem ?

**Comment by dennydai** [comment]
you need run it with telegram-cli. run like this
./bin/telegram-cli -Z your-py-script-path

**Comment by idreamsi** [comment]
Thank You @dennydai .
