### ISSUE TITLE
Compilation Error Ubuntu 14.04

### ISSUE THREAD

**Issue by Jamuzb** [vysheng/tg#583]
interface.c: In function 'do_block_user':
interface.c:1023:3: error: implicit declaration of function 'tgl_do_block_user' [-Werror=implicit-function-declaration]
   tgl_do_block_user (TLS, args[0].P->id, print_success_gw, ev);
   ^
interface.c: In function 'do_unblock_user':
interface.c:1029:3: error: implicit declaration of function 'tgl_do_unblock_user' [-Werror=implicit-function-declaration]
   tgl_do_unblock_user (TLS, args[0].P->id, print_success_gw, ev);
   ^
cc1: all warnings being treated as errors
make: *** [objs/interface.o] Error 1

**Comment by vysheng** [comment]
did you run ```git submodule update --recursive``` after ```git pull```?

**Comment by Jamuzb** [comment]
Thanks vysheng. I really didn't run. Now it's ok.

**Comment by luckydonald** [comment]
Hmm, update in doc?
