### ISSUE TITLE
Python implementation is not completed.

### ISSUE THREAD

**Issue by rockneurotiko** [vysheng/tg#585]
Like we can see from line 880 to line 906 of [python-tg.c](https://github.com/vysheng/tg/blob/e3efc4f7980f5b8a7c7e27d60b0cc416c5245174/python-tg.c#L880), the functions to load files (all) are commented.

Warning the missing of implementation in the README-PY until it is should be really good, because I thinked that it was implemented, and didn't know why I was getting an error.

Thanks!

**Comment by Surye** [comment]
Oops, didn't notice they were in the readme, that was a bit of a rush job as I want to do much better docs for it. I will mention that and then add implementing them to my todo list since someone wants them :)

**Comment by rockneurotiko** [comment]
First of all, really thanks @Surye for the awesome work you are making with the python library :smile: 

Great news that you will implement it ^^ 

As a request for later, maybe you could implement something like the postpone function of the lua interface, I tried to do background functions with threads (and more things, but this is what works best), and execute, but the tg interactions are only exercuted when tg have some activity, which is normal, but should be really awesome to have something similar :)

Thanks!

**Comment by Surye** [comment]
https://github.com/vysheng/tg/commit/a06507d49ce6abc6ebe5c0afcde551d6db146b91

I had a similar issue, but I wanted to keep everything in python including managing timer threads. So I added a new call back that you can subscribe to that calls every time the internal loop is run. This ensures that python always gets a slice of time to manage threads, not just on activity.

**Comment by rockneurotiko** [comment]
Ou, that's really really nice, with `tgl.set_on_loop` (I guess that this will go in the improved documentation ^^)

I really like this, even with an empty function in the loop callback now my "delayed" decorator works as expected! =D

Really thanks!

**Comment by Surye** [comment]
btw, if you have questions about how to use parts of the api, https://github.com/datamachine/telegram-pybot is the driving force for development and will be using pretty much any new features I add (as it's why I add them most of the time)

**Comment by Surye** [comment]
Recommended usage of new load functions:
```
import tgl

def print_path(success, filename):
    print(filename)

def on_msg_receive(msg):
    # You can do checks here, but it'll just return None to filename in callback if it's got no photo.
    msg.load_photo(print_path)

tgl.set_on_msg_receive(on_msg_receive)
```

**Comment by rockneurotiko** [comment]
omg, so fast!
Really, really thanks! I'll try it this afternoon :smile:
