### ISSUE TITLE
FreeBSD 10.1: Make fails

### ISSUE THREAD

**Issue by hiway** [vysheng/tg#590]
Running on VPS, installed dependencies, ran configure - completed. When I run make, it fails with a rather unhelpful comment. What am I missing?

$ ./configure
...
$ make
make: don't know how to make objs/%.o:. Stop

make: stopped in /usr/home/harshad/dev/tg-1.3.1

**Comment by vysheng** [comment]
what version of make do you have?

**Comment by hiway** [comment]
@vysheng I have make version `20130904`.

Here's what I've tried so far:
 - installed gmake
 - tried gmake on master branch, failed
 - removed `-ldl` parameter from Makefile (which was causing the failure, FreeBSD provides the libraries elsewhere)
 - compilation went through fine
 - run `bin/telegram-cli` and now I get this output:

```
[/dev/tg/bin]$ ./telegram-cli
Telegram-cli version 1.3.1, Copyright (C) 2013-2015 Vitaly Valtman
Telegram-cli comes with ABSOLUTELY NO WARRANTY; for details type `show_license'.
This is free software, and you are welcome to redistribute it
under certain conditions; type `show_license' for details.
Telegram-cli uses libtgl version 2.0.2
Telegram-cli uses libpython version 2.7.9
I: config dir=[/home/harshad/.telegram-cli]
```

**Comment by vysheng** [comment]
Very strange. Since it was not a compilation error, but Makefile parse error

**Comment by hiway** [comment]
Since what I'm now seeing is another issue, I'm closing this one as it is solved. Cheers!
