### ISSUE TITLE
python code read my massages when sending in group

### ISSUE THREAD

**Issue by erfan-mehraban** [vysheng/tg#591]
hi
i connect cli to my account and  write simple bot eith python and run it with telegram-cli -Z code.py .
it listen to some specific massage and i write code in on_msg_receive(msg) function but when i send massage from my account this function doesnt call. Is there another function to call when massage sent OR recive any massage that is in group Regardless of who sent it??

**Comment by Surye** [comment]
The function should still call with msg.out == True. Are you filtering that out like in the test code?

**Comment by erfan-mehraban** [comment]
Yes.... Because there isnt any good documentation! 1. Is there????
2. where should i put this code? (msg.out == True)

**Comment by Surye** [comment]
Yes, I know documentation leaves a lot to be desired. I intend to work on that soon.

If you want all msgs to be processed in on_msg_receive(msg) regardless of who sent it, just don't check for msg.out.
```
def on_msg_receive(msg):
    print(msg.text)
```

**Comment by erfan-mehraban** [comment]
So where is the source code to read instead of ducuments?

**Comment by Surye** [comment]
All of the python bindings are in python-tg.c, python-tg.h, python-types.c and python-types.h. Things like the .out attribute come directly from tg, it is mostly a mirror of the c api, with the exception of msg.text and peer.src/peer.dest
