### ISSUE TITLE
LUA - import_chat_link()

### ISSUE THREAD

**Issue by psycholyzern** [vysheng/tg#595]
I cant make it work.

import_chat_link(hash_here)

It return 'false' to me.

**Comment by vysheng** [comment]
as every other lua function - you should pass two more args - callback and callback_extra

**Comment by psycholyzern** [comment]
Oh ok.. My bad.. It is working now. Thanks 😁😁😁

**Comment by psycholyzern** [comment]
It return 'true' even I used same hash over and over. Is there any way to return false or something, if I already a member of that group?

**Comment by psycholyzern** [comment]
And, from.id return 0 instead of my own id.. See green hightlighted part in image below

![](http://s21.postimg.org/nmh039047/Pics_Art_1433324721101.jpg)

**Comment by psycholyzern** [comment]
It is working nornal now.. Thanks
