### ISSUE TITLE
Join automatically via group link in python program

### ISSUE THREAD

**Issue by erfan-mehraban** [vysheng/tg#600]
Is there any way to join groups via links in python program? What is the function?

**Comment by Surye** [comment]
None yet, it's on my todo list!

**Comment by Surye** [comment]
https://github.com/datamachine/tg/commit/495d33e92a8d0ff686aa6296ec605ea7a3bffcbc

Implemented, waiting for PR to be pulled. Still not documented, I know, I know.

**Comment by erfan-mehraban** [comment]
tgl.import_chat_link(LINK)

**Comment by Andreswas** [comment]
Bacot deh

**Comment by Andreswas** [comment]
Arigatou gomaizu

**Comment by bobo24675** [comment]
Hii
