### ISSUE TITLE
Read Events - being sent from server instead of client?

### ISSUE THREAD

**Issue by jonnywilliamson** [vysheng/tg#601]
@luckydonald - Just wondering seeing as you implemented the read events could you look at this.

So I send a message FROM the cli server to MY phone.
I get a message event.
```
{#561
  +"event": "message"
  +"id": 1506
  +"out": true
  +"flags": 259
  +"text": "Hello Jonathan"
  +"unread": true
  +"from": {#571
    +"username": "williamsonserver"
    +"id": <snip>
    +"type": "user"
    +"first_name": "WilliamsonWeb"
    +"print_name": "WilliamsonWeb_Server"
    +"flags": 264
    +"phone": "<snip>"
    +"last_name": "Server"
  }
  +"to": {#564
    +"username": "jwilliamson"
    +"id": <snip>
    +"type": "user"
    +"first_name": "Jonathan"
    +"print_name": "Jonathan_Williamson"
    +"flags": 257
    +"phone": "<snip>"
    +"last_name": "Williamson"
  }
  +"service": false
  +"date": 1433421178
}
```

This makes sense.

I then open the app on my phone.

I get an online status message:

```
{#561
  +"user": {#564
    +"first_name": "Jonathan"
    +"phone": "<snip>"
    +"last_name": "Williamson"
    +"username": "jwilliamson"
  }
  +"event": "online-status"
  +"state": 1
  +"online": true
  +"when": "2015-06-04 12:38:14"
}
```
This also makes sense.

I finally open the message but I get a READ event FROM the webserver.

I would have assumed it should have been a READ event FROM my phone:

```
{#561
  +"event": "read"
  +"id": 1506
  +"out": true
  +"flags": 258
  +"text": "Hello Jonathan"
  +"unread": false
  +"from": {#564
    +"username": "williamsonserver"
    +"id": <snip>
    +"type": "user"
    +"first_name": "WilliamsonWeb"
    +"print_name": "WilliamsonWeb_Server"
    +"flags": 264
    +"phone": "<snip>"
    +"last_name": "Server"
  }
  +"to": {#571
    +"username": "jwilliamson"
    +"id": <snip>
    +"type": "user"
    +"first_name": "Jonathan"
    +"print_name": "Jonathan_Williamson"
    +"flags": 257
    +"phone": "<snip>"
    +"last_name": "Williamson"
  }
  +"service": false
  +"date": 1433421178
}
```

Why is the server sending out a READ event? (ie Out is true). It was my phone that READ the message, so should it not be sending a message back to the server to say "hey I read that message thanks".

Is this a bug?

**Comment by luckydonald** [comment]
Nope, as the message which got marked "read" still was send from your sever-cli.
The only difference from the original message event is that `unread` now is `false`, and the `event` being `message`. (to prevent parsing it as "new" message.)
If the message got send and read before the cli got the message at all, there will be no read event.

**Comment by jonnywilliamson** [comment]
@luckydonald OK. Thanks for the information - and for implementing that!
