### ISSUE TITLE
How to obtain group ID

### ISSUE THREAD

**Issue by mohsen** [vysheng/tg#602]
Hi,

How can I obtain a group ID. Currently only group name can be specified as parameter and this causes ambiguities when you have groups with same names.

I get user ID by user_info command (and it seems that [contact_list()](https://github.com/vysheng/tg/issues/48#issuecomment-33581402) doesn't return user ID anymore). I want to ask for a similar method for groups.

Thanks.

**Comment by bidak** [comment]
chat_info group_name

**Comment by mohsen** [comment]
Is it possible to send messages to groups just like sending them to users by using theire IDs? Currently ``msg user#12345 text`` only works for users not groups.

**Comment by bidak** [comment]
msg chat#group_id text

**Comment by mohsen** [comment]
Thanks again. Is there documented somewhere :-)?
