### ISSUE TITLE
make: *** No rule to make target `tgl/scheme.tl', needed by `auto/scheme.tl'

### ISSUE THREAD

**Issue by psycholyzern** [vysheng/tg#630]
```make: *** No rule to make target `tgl/scheme.tl', needed by `auto/scheme.tl'.  Stop.```

after ```./configure```, I run ```make``` then got that error.

**Comment by psycholyzern** [comment]
sorry, my bad. Forgot to use ```--recursive``` while cloning

**Comment by alexreg** [comment]
The release tarball doesn't include the recursively cloned sources, I'm afraid!
