### ISSUE TITLE
How send a message with Python script ?

### ISSUE THREAD

**Issue by idreamsi** [vysheng/tg#632]
Hi
The first question :
I've run the script tg-test.py. After a few seconds, Signal Received messages are displayed and python script will end.
![12](https://cloud.githubusercontent.com/assets/8011806/8156355/5dd0d29e-1361-11e5-85c1-ec576c50b5de.JPG)

The second question :
How can I send a photo message and text message in Python script?

my python script :
```python
import tgl

def on_msg_receive(msg):
    print(msg.id)
    #For example  >> if (msg == "!time") :
                      #send_msg_to_user(time.now)

tgl.set_on_msg_receive(on_msg_receive)
```

**Comment by idreamsi** [comment]
Problem solved.

**Comment by nevesleonardo** [comment]
Hi @idreamsi , I'm new on python and I'd like to know how I can write a code that send a simple msg in Pyhton using tg. Thanks!
