### ISSUE TITLE
Join a group via invitation links

### ISSUE THREAD

**Issue by omid** [vysheng/tg#648]
Join groups via invitation links, like:
https://telegram.me/joinchat/GROUP_UNIQUE_LINK_ID

**Comment by erfan-mehraban** [comment]
if you want to code in python : #600

**Comment by omid** [comment]
Thanks a lot, it works. But I cannot understand the relation between coding python or using CLI.
with this command I can connect a a group via link:
import_chat_link https://telegram.me/joinchat/GROUP_UNIQUE_LINK_ID

**Comment by jdiouioussma** [comment]
gooood site perfecf

**Comment by 0729004922** [comment]
Like sure tips to bet

**Comment by cherongos** [comment]
Heh

**Comment by nguyenvietlong2** [comment]
tôi đến đây từ telegram https://t.me/joinchat / HgrRTQ93gZQPq0XFuWU7ug .

**Comment by sandipnath198** [comment]
💠GREAT OPPORTUNITY💠
   🌏10 Minute Work Time🌏
          ⏳FREE FREE FREE⏳
🎗GOVERNMENT REGISTERED COMPANY🎗
     🎯LIFE TIME INCOME PLAN 🎯

👉COMPANY DETAILS👈
🔘 ​Name -JTS  trade mart pvt.ltd​
🔘 ​Head office -Lucknow 226021(UP India​
🔘 ​Pan card no-AADCJ2238B​

अपने मोबाइल से रोज 20 एड देखो और 10-20 लोगों की एक टीम बनाओ और हर महीना 15000-50000₹ घर बैठे कमाओ
.
घबराइए नहीं सिर्फ 10 लोगों को ज्वाइन करके आप करोड़ों लोगों की टीम बना सकते हो |


आप सोच भी नहीं सकते आपका महीने का कितना इनकाम हो सकता है 

ज्वाइन होने के लिए इस वेबसाइट पर जाइए👇👇
 http://www.socialaddworld.us.com/Registration.aspx?spnid=8811880733

👉  Refer code:- 8811880733
👉  Full Name...
👉  Mob. No...
👉  Email...
👉  Sex...
👉  D.O.B...   (Month/Date/Year)
👉  City...
Fir *Terms & Condition* accept kiziye or *Register* par click kiziye

​Note;- आपका पासवर्ड मोबाइल नंबर  पर आएगा​ और आपका मोबाइल नंबर ही आपका ID होगा |

उसके बाद Login पर क्लिक करके अपना ID और पासवर्ड डाल दे

आपके सामने कुछ task आएगा उसे कंप्लीट कर लो सिर्फ एक ही बार करना है |  

बहुत ही बढ़िया कंसेप्ट है समय ना गवा कर जल्दी ज्वाइन हो जाइए और अपने सपनों को सक्सेस कीजिए

My sponsor ID 👉 8811880733

For instant help Type "JOB" and send it on my whatsaap 👉8811880733
.

**Comment by chandagupta** [comment]
Great One

**Comment by sunny9046** [comment]
tg:join?invite=AAAAAFLt1eDxOC6XrniL0w

**Comment by reloxxxx** [comment]
Gia sas

**Comment by Angeli78** [comment]
tg:join?invite=L2GR31YKBJs50yUq7C32Sg

**Comment by tas77** [comment]
Through a comprehensive search for the most powerful companies that help you to make a sure and comfortable profit without time or effort
 If you were someone who wanted to enter the world of the stock market
 To know more about it, enter the group Telegram link :-
https://t.me/algolightinenglish

**Comment by tas77** [comment]
Algo Light for Arabs
اهلا وسهلا لكل زوارنا الكرام ومحبي الربح السهل والوفير على الانترنت واصحاب رؤوس الاموال للاستثمار - معكم المضيف جابر من شركة Algo Light!! هنا سنحاول جمع قدر هائل من المستفدين ومن ثم نبدأ النشر الجدي عن معلومات الشركه!! بقائكم واستماعكم سيفيدكم فالمستقبل!
https://t.me/algolightforarabs

Only for arabs

**Comment by altyeb778** [comment]
Link is closed

**Comment by Diallo-Boubaca** [comment]
Bonjour comment puis me rejoindre au groupe

**Comment by afzal6250** [comment]
Hi

**Comment by afzal6250** [comment]
I am afzal

**Comment by Fiangor** [comment]
I am inn.

Best Regards
Fiatefe Kuevor

**Comment by afzal6250** [comment]
Hi

**Comment by afzal6250** [comment]
Hello

**Comment by cerrajero** [comment]
Nft gratis. Consta tu wallet y te regalan 1$ por registrarte con lo que podrás comprar tu primer nft totalmente gratis y luego benderlo y jenerar ingresos todos los dias

**Comment by cerrajero** [comment]
Nft gratis visita esta pajina https://wnft.life/index/index.html

**Comment by Chintu1975** [comment]
7 people directly joined me

**Comment by Lingtang1** [comment]
Gabung

**Comment by empiretylh** [comment]
Hello, It still not working, I want to integrate with Deep Link in my react native app. That automatically join the telegram's private group chat. I create invite link and then use with telgram deep link. It not work.

my telgram group chat invite link
[https://t.me/+Itid34gk5vU4YzJl](https://t.me/+Itid34gk5vU4YzJl)

deep link in react-native
`tg://join?invite=++Itid34gk5vU4YzJ`

**Comment by pidrohr** [comment]
https://2cm.top/7oTVoG_mwhlom?i=copy
Ton free

**Comment by arsulkhan123** [comment]
Hello

**Comment by rayzen56** [comment]
tg:join?invite=2tH-ObMtEw1jNzE9

**Comment by 12131449** [comment]
Good

**Comment by dominiquepayet632-afk** [comment]
Bonjour c Dominique de la réunion

**Comment by alicevitoria223762-gif** [comment]
Eu queroooo
