### ISSUE TITLE
get_history,  get_contact_list & get_dialog_list not functioning

### ISSUE THREAD

**Issue by drunkwolfs** [vysheng/tg#669]
I'm trying to use the get_history function in a lua script but it only seems to return a boolean value. The way I used it is as follows: history = get_history("chat#id0000000", 10, ok_cb, false) but all it returns is true. Is it supposed to work this way? How can I actually retrieve history in lua? Please example.

print(get_dialog_list(ok_cb, false))
return: true

print(get_contact_list(ok_cb, false))
return: true

**Comment by drunkwolfs** [comment]
get_* is callback functions

**Comment by sargashteh** [comment]
@drunkwolfs how to use dialog_list() on lua script??
