### ISSUE TITLE
peer.send_msg() in tg-test.py error when replying

### ISSUE THREAD

**Issue by linxlunx** [vysheng/tg#678]
I always get this error when replying the message

```
TypeError: argument 3 must be impossible<bad format char>, not bool
```

The method is like this

```
peer.send_msg("pong", reply=msg.id, preview=False)
```

Anyone?

**Comment by JokerQyou** [comment]
Me too, when I reply using `peer.send_msg(text, reply=msg.id)` in `on_msg_receive` callback, I always get `RuntimeError: impossible<bad format char>: 'pi'` error. 
I'm using tg on raspberrypi, Raspbian with Python 2.7.3.

**Comment by Mattze96** [comment]
Same error as @linxlunx , but only on my debian server. removing preview=False, fixes it but thats not a solution.

**Comment by JuanPotato** [comment]
The error is with python 2 compatibility. (as I've tested with python 2 and 3 and only 2 receives the error)

**Comment by drunkwolfs** [comment]
send_msg() not work for Python 2.7.3
fix:
install python3-dev
make clean
./configure
make
