### ISSUE TITLE
Compiling on Centos fails....

### ISSUE THREAD

**Issue by jpaechnatz** [vysheng/tg#682]
After git pulling latest version, fhe following error occurs:

gcc -I. -I. -I./tgl -g -O2  -I/usr/local/include -I/usr/include -I/usr/include  -I/usr/include/python2.7   -DHAVE_CONFIG_H -Wall -Werror -Wextra -Wno-missing-field-initializers -Wno-deprecated-declarations -fno-strict-aliasing -fno-omit-frame-pointer -ggdb -Wno-unused-parameter -fPIC -c -MP -MD -MF dep/loop.d -MQ objs/loop.o -o objs/loop.o loop.c
In file included from ./tgl/tools.h:25:0,
                 from ./tgl/auto.h:23,
                 from ./auto/auto-types.h:3,
                 from ./tgl/tgl-fetch.h:23,
                 from ./tgl/tgl-structures.h:25,
                 from interface.h:21,
                 from loop.c:62:
loop.c: In Funktion »write_dc«:
loop.c:364:35: Fehler: »struct tgl_dc« hat kein Element namens »options«
   assert (write (auth_file_fd, &DC->options[0]->port, 4) == 4);
                                   ^
loop.c:365:21: Fehler: »struct tgl_dc« hat kein Element namens »options«
   int l = strlen (DC->options[0]->ip);
                     ^
In file included from ./tgl/tools.h:25:0,
                 from ./tgl/auto.h:23,
                 from ./auto/auto-types.h:3,
                 from ./tgl/tgl-fetch.h:23,
                 from ./tgl/tgl-structures.h:25,
                 from interface.h:21,
                 from loop.c:62:
loop.c:367:34: Fehler: »struct tgl_dc« hat kein Element namens »options«
   assert (write (auth_file_fd, DC->options[0]->ip, l) == l);
                                  ^
loop.c: In Funktion »loop«:
loop.c:706:5: Fehler: Implizite Deklaration der Funktion »tgl_enable_bot« [-Werror=implicit-function-declaration]
     tgl_enable_bot (TLS);
     ^
cc1: Alle Warnungen werden als Fehler behandelt
make: *** [objs/loop.o] Fehler 1

Any Idea/Solution to this?

Thanks!

**Comment by Mattze96** [comment]
Have you pulled recursively?

    git submodule foreach git pull

**Comment by LukeLR** [comment]
Or use the ’--recursive’ flag when cloning:
’git clone --recursive https://github.com/vysheng/tg-cli’

**Comment by jpaechnatz** [comment]
I removed the checkout, and did a fresh git clone --recursive.... that worked, adding this information to the documentation would be nice ;-)

Thanks!

**Comment by Surye** [comment]
https://github.com/vysheng/tg#installation It is ;)
