### ISSUE TITLE
Get_message in Lua

### ISSUE THREAD

**Issue by siyanew** [vysheng/tg#703]
i want Get_message work in lua , how i can do it ?

**Comment by LukeLR** [comment]
What is this method supposed to do?

**Comment by psycholyzern** [comment]
get_message is to get message text from msg id
I need it too.

**Comment by siyanew** [comment]
@psycholyzern you can do it by define a function in lua-tg.c in vysheng/tg.

**Comment by psycholyzern** [comment]
yep I know @siyanew, but I dont know a thing about C language. Can you do that for us?

**Comment by siyanew** [comment]
i add some new function and pull request on #848

**Comment by psycholyzern** [comment]
This is really cool @siyanew !! I'll test it out. Thanks.

**Comment by psycholyzern** [comment]
I tried. Somehow it only give me "false" from the callback.

```
local function cb_cust(extra, success, result)
  vardump(result) --false
end

local function run(msg, matches)
  vardump(get_message("16193667", cb_cust, cb_extra)) --true
end
```

**Comment by siyanew** [comment]
I use it that way : 
```` 
local function get_message_callback(extra, success, result)
  if result.to.type == 'chat' then
      local chat = 'chat#id'..result.to.id
      return "Your Chat id : " .. chat
  else
    return 'you're not in a group'
  end
end
if type(msg.reply_id)~="nil" then
    msgr = get_message(msg.reply_id,get_message_callback, false)
end
````
get message reply id by msg.reply_id

**Comment by psycholyzern** [comment]
nice.. it is working.. thanks for the sample @siyanew :)
