### ISSUE TITLE
Get block on code. my phone can't recieve the code. 

### ISSUE THREAD

**Issue by imyoka** [vysheng/tg#732]
change_user_group: can't find the user telegramd to switch to
Telegram-cli version 1.3.3, Copyright (C) 2013-2015 Vitaly Valtman
Telegram-cli comes with ABSOLUTELY NO WARRANTY; for details type `show_license'.
This is free software, and you are welcome to redistribute it
under certain conditions; type`show_license' for details.
Telegram-cli uses libtgl version 2.0.3
Telegram-cli includes software developed by the OpenSSL Project
for use in the OpenSSL Toolkit. (http://www.openssl.org/)
I: config dir=[/root/.telegram-cli]
15601099833
register (Y/n): Y
first name: Schwarz
last name: Tom
code ('CALL' for phone code):
#### this phone number && first name, last name i've registered on telegram app. But when i get back to cli interface, I come accross to this error~

```
Looking for ur reply.thx~
```

**Comment by LukeLR** [comment]
Why do you register your phone number in tg-cli if you have registered elsewhere before?

**Comment by imyoka** [comment]
But if i run `./bin/telegram-cli -k server.pub -W -D -P 7777 -d -s ../tg_raspberrypi.lua` directly, error still throw __*change_user_group: can't find the user telegramd to switch to *__

when i run `./bin/telegram-cli -k tg-server.pub`, the phone number alert to press me to enter sth.

change_user_group: can't find the user telegramd to switch to
Telegram-cli version 1.3.3, Copyright (C) 2013-2015 Vitaly Valtman
Telegram-cli comes with ABSOLUTELY NO WARRANTY; for details type `show_license'.
This is free software, and you are welcome to redistribute it
under certain conditions; type `show_license' for details.
Telegram-cli uses libtgl version 2.0.3
Telegram-cli includes software developed by the OpenSSL Project
for use in the OpenSSL Toolkit. (http://www.openssl.org/)
I: config dir=[/root/.telegram-cli]
phone number: [what's this?]

when i enter my phone number. then `register (Y/n):`
__i choose n  __  after enter my first name && last name
it still ask for my phone number

####here is the log
for use in the OpenSSL Toolkit. (http://www.openssl.org/)
I: config dir=[/root/.telegram-cli]
phone number: 15601099833
register (Y/n): n
first name: Schwarz
last name: Tom
phone number:

#### Even boring

	phone number: 15601099833
	register (Y/n): n
	first name: schwarz
	last name: tom
	phone number: 15601099833
	register (Y/n): n
	first name: Schwarz
	last name: Tom
	phone number: 15601099833
	register (Y/n): n
	first name: Schwarz
	last name: Tom
	phone number:

**That's why i have to choose register**

**Comment by LukeLR** [comment]
Yes, but already the fact that it asks you to register is a malfunction, because it should not if you had registered the account before, you know? If the account is registered, it will not ask you for your name, but just send you a verification code and then authenticate the existing account. so that's the main problem. Are you sure the account is registered? If you choose n it is obvious that it will ask you again and again because you need to be logged in in order to use tg-cli, and if you don't want to register this account it will ask you again until you are logged in.

**Comment by jansenicus** [comment]
I got this looping phone registration problem once, and was solved by adding country calling code in front of the phone number, i.e. +6281317609943 as an example where +62 is the country calling code for Indonesia. 

CMIIW there are country calling code starting with +13, +14 but I guess there is no country code starting with +15 and therefore you should add the right country code prefix.

**Comment by LukeLR** [comment]
Yes, of course. Didn't notice the missing "+"-sign or the wrong country code. Thanks!

**Comment by truthskr5** [comment]
I am having the same problem that telegram is sending the code to my other devices and I don't have other devices logged on and I am using the desktop version. I have been without my telegram for a while now and I really need to get back on. What am I suppose to do?

**Comment by Paulchen232** [comment]
If you are having registration or login problems, you can contact Telegram using [this form.](https://telegram.org/support)
