### ISSUE TITLE
How detect group chat LUA?

### ISSUE THREAD

**Issue by vk496** [vysheng/tg#737]
I use the example of ping-pong lua script. 
```
if (string.match(string.lower(msg.text), "ping")) then
        send_msg (msg.from.print_name, "pong", ok_cb, false)
    end
```
When someone text on group chat "ping", Telegram send him private message "pong"

How detect if someone send me "ping" in private msg or group chat?

**Comment by siyanew** [comment]
```
if (string.match(string.lower(msg.text), "ping")) then
  if ( msg.to.type == "chat" ) then
     send_msg ("chat#id"..msg.to.id, "pong", ok_cb, false)
  else
     send_msg ("user#id"..msg.from.id, "pong", ok_cb, false)
  end
end
```

**Comment by vk496** [comment]
Thnks @siyanew, works perfect!

Where do you get the documentation?

**Comment by siyanew** [comment]
i just 
    vardump(msg)
and this will show you a json that get you more information

**Comment by vk496** [comment]
Thnks!
