### ISSUE TITLE
Unable to install Telegram: no makefile found

### ISSUE THREAD

**Issue by EliaComputers** [vysheng/tg#759]
hello, I am trying to install telegram on my Raspberry Pi with Raspbian, I followed this guide precisely: http://www.instructables.com/id/Telegram-on-Raspberry-Pi/ but when sending the command 'make' everything stops, saying no makefile found. I would be very happy to install telegram on my raspberry, Has someone had the same problem? Thanks to all :)

**Comment by LukeLR** [comment]
Did you ./configure?

**Comment by EliaComputers** [comment]
Yes, I followed the tutorial. I've installed the libraries, downloaded the repo, ./configure and at the commando make it fails. :(

**Comment by LukeLR** [comment]
What does ./configure say? Does it run successfully, or are there any errors? If there is no make file after configuring, then it should be clear to you that configuring failed. Is "." the repository directory of tg when configuring?

**Comment by EliaComputers** [comment]
OK, here is the output of the "./configure":


root@raspberrypi:/home/pi/tg# ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for sqrt in -lm... yes
checking for library containing clock_gettime... -lrt
checking for library containing backtrace... none required
checking for event_base_new in -levent... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking event2/event.h usability... yes
checking event2/event.h presence... yes
checking for event2/event.h... yes
checking for pkg-config... /usr/bin/pkg-config
checking whether compiling and linking against OpenSSL works... yes
checking if zlib is wanted... yes
checking for inflateEnd in -lz... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for rl_save_prompt in -lreadline... yes
checking for libconfig... enabled
checking for config_init in -lconfig... yes
checking for liblua... enabled
checking for lua... /usr/bin/lua
checking if /usr/bin/lua is a Lua interpreter... yes
checking for lua version... 5.2
checking for lua platform... unknown
checking for lua script directory... ${prefix}/share/lua/5.2
checking for lua module directory... ${exec_prefix}/lib/lua/5.2
checking if LUA_VERSION is defined... yes
checking lua.h usability... no
checking lua.h presence... no
checking for lua.h... no
checking lualib.h usability... no
checking lualib.h presence... no
checking for lualib.h... no
checking lauxlib.h usability... no
checking lauxlib.h presence... no
checking for lauxlib.h... no
checking luaconf.h usability... no
checking luaconf.h presence... no
checking for luaconf.h... no
checking for Lua headers in... /usr/include/lua5.2
checking lua.h usability... yes
checking lua.h presence... yes
checking for lua.h... yes
checking lualib.h usability... yes
checking lualib.h presence... yes
checking for lualib.h... yes
checking lauxlib.h usability... yes
checking lauxlib.h presence... yes
checking for lauxlib.h... yes
checking luaconf.h usability... yes
checking luaconf.h presence... yes
checking for luaconf.h... yes
checking for Lua header version... 5.2
checking if Lua header version matches 5.2... yes
checking if LUA_VERSION is defined... yes
checking for library containing exp... none required
checking for library containing dlopen... -ldl
checking for library containing lua_load... -llua5.2
checking for python... enabled
checking for python build information... 
checking for python3.4... no
checking for python3.3... no
checking for python3.2... python3.2
checking for main in -lpython3.2... no
checking for main in -lpython3.2m... no
checking for main in -lpython3.2mu... no
checking for python3.1... no
checking for python3... python3
checking for main in -lpython3... no
checking for main in -lpython3m... no
checking for main in -lpython3mu... no
checking for python2.7... python2.7
checking for main in -lpython2.7... yes
  results of the Python check:
    Binary:      python2.7
    Library:     python2.7
    Include Dir: /usr/include/python2.7
checking for libjansson... enabled
checking for json_array_set_new in -ljansson... no
configure: error: No libjansson found. Try --disable-json
root@raspberrypi:/home/pi/tg# 



And here is the output of the command ls:


root@raspberrypi:/home/pi/tg# ls
ax_lua.m4      LICENSE.h	       README-Cygwin.md
ax_python.m4   loop.c		       README.es
bootstrap      loop.h		       README-LUA
CHANGELOG      lua-tg.c		       README.md
config.h.in    lua-tg.h		       README-PY.md
config.log     m4_ax_check_openssl.m4  rpm
config.sample  m4_ax_check_zlib.m4     server.pub
configure      m4-ax_gcc_builtin.m4    start-telegram-daemon
configure.ac   main.c		       telegram-cli-cygwin.patch
debian	       Makefile.in	       telegram-cli.spec
event-old.h    Makefile.tgl	       telegram-daemon
gentoo	       Makefile.tl-parser      telegram.h
interface.c    mime.types	       test.lua
interface.h    python-tg.c	       tgl
json-tg.c      python-tg.h	       tg-server.pub
json-tg.h      python-types.c	       tg-test.py
LICENSE        python-types.h
root@raspberrypi:/home/pi/tg#

**Comment by scsnip** [comment]
It clearly states 
configure: error: No libjansson found. Try --disable-json

**Comment by EliaComputers** [comment]
Ok, so i must install this library. Right?
Il 03/set/2015 20:33, "scsnip" <notifications@github.com> ha scritto:

**Comment by scsnip** [comment]
Or pass configure disable flag as noted in output.

**Comment by LukeLR** [comment]
But you should install it if it's possible ;) try the package manager of your system with the package name as given in the readme;)

**Comment by EliaComputers** [comment]
Thanks, It works! :)

**Comment by Semo** [comment]
Sorry bothering. I have the same issue. After calling ./configure I get after a long trace this output:
```
checking for python build information... 
checking for python3.5... no
checking for python3.4... python3.4
checking for main in -lpython3.4... no
checking for main in -lpython3.4m... no
checking for main in -lpython3.4mu... no
checking for python3.3... no
checking for python3.2... no
checking for python3.1... no
checking for python3... python3
checking for main in -lpython3... no
checking for main in -lpython3m... no
checking for main in -lpython3mu... no
checking for python2.7... python2.7
checking for main in -lpython2.7... no
checking for main in -lpython2.7m... no
checking for main in -lpython2.7mu... no
checking for python2.6... no
checking for python2... python2
checking for main in -lpython2... no
checking for main in -lpython2m... no
checking for main in -lpython2mu... no
checking for python... python
checking for main in -lpython... no
checking for main in -lpythonm... no
checking for main in -lpythonmu... no
  results of the Python check:
    Binary:      python
    Library:     no
    Include Dir: no 
configure: error: No supported python lib version found. Try --disable-python
```
This is false. When checking my system of course python is installed. Here please see after hitting TAB while entering the command:
```
admin@mars:~/telgram-cli/tg$ py
py3clean      pybuild       pydoc         pydoc3.4      pygettext3    python        python3       python3m      pyversions    
py3compile    pyclean       pydoc2.7      pygettext     pygettext3.4  python2       python3.4     pythontex     
py3versions   pycompile     pydoc3        pygettext2.7  pyhtmlizer    python2.7     python3.4m    pythontex3   
```
So, how to solve it, without breaking the ./configure program? I can't install python, because it's already installed and in various flavours, too. :tada: :

Regards, Semo

**Comment by scsnip** [comment]
Ooops. Sorry did not mentino question email =(
Is question is still actual?

2015-11-25 10:52 GMT+03:00 Sebastian Morkisch <notifications@github.com>:

**Comment by mirismaili** [comment]
`yum install jansson-devel`

**Comment by ArturoArreola** [comment]
thamk you @mirismaili 
`yum install jansson-devel` works for me :)
