### ISSUE TITLE
How to install for Synology?

### ISSUE THREAD

**Issue by iruyanka** [vysheng/tg#761]
Can you make for spk on synology?

I want to use on synology. Thank you.

**Comment by LukeLR** [comment]
Why don't you try it for yourself?
https://amigotechnotes.wordpress.com/2014/05/17/how-to-create-a-spk-for-synology-dsm-to-distribute-your-lamp/
https://www.synology.com/en-us/support/developer
http://forum.synology.com/wiki/index.php/Synology_package_files
Or build via command line and ipkg.
