### ISSUE TITLE
Error: change_user_group: can't find the user telegramd to switch to

### ISSUE THREAD

**Issue by iambillywilly** [vysheng/tg#764]
I have this error. Please, help

root@click-telegram:~/tg# bin/telegram-cli -k bin/tg-server.pub -w
change_user_group: can't find the user telegramd to switch to
Telegram-cli version 1.3.3, Copyright (C) 2013-2015 Vitaly Valtman
Telegram-cli comes with ABSOLUTELY NO WARRANTY; for details type `show_license'.
This is free software, and you are welcome to redistribute it
under certain conditions; type `show_license' for details.
Telegram-cli uses libtgl version 2.0.3
Telegram-cli includes software developed by the OpenSSL Project
for use in the OpenSSL Toolkit. (http://www.openssl.org/)
Telegram-cli uses libpython version 2.7.3
I: config dir=[/root/.telegram-cli]

**Comment by psycholyzern** [comment]
Don't worry, it doesn't affect anything. It tried to run telegram-cli as user telegramd, if the user is not exists, it will throw that error, but nothing need to worry about.
To remove that error, you need to create a user named as "telegramd"

**Comment by iambillywilly** [comment]
Thank u! :)
