### ISSUE TITLE
Register a new number without telegram-cli

### ISSUE THREAD

**Issue by bidak** [vysheng/tg#767]
I want to register a new number without telegram cli.
Can i create auth file out of telegram cli and copy to tg files as a new number?
I want to manually create auth files.

**Comment by LukeLR** [comment]
Why would you want to do this? There's nothing bad about the integrated authentication process for telegram. And I'm pretty sure there's no way to manually authorize keys with your telegram account, you'd have to use the application's authorisation…

**Comment by bidak** [comment]
Because i already registered number on telegram app(mobile) so i need to re-register on telegram-cli.<br>
I don't want to re-register account.

**Comment by LukeLR** [comment]
That's exactly the point. If you're already using telegram on the number you're passing telegram, than it won't ask you to re-register, but it will send you a code to all your existing telegram instances, that you will have to enter in the client you want to add. That's it. After that, both clients are connected to the same account. Everything regarding authorisation keys and ids and so on is done by the client automatically. That's exactly what I meant by integrated authorisation progress of telegram. You don't have to worry about anything. Just use it.
