### ISSUE TITLE
has anyone tested this on raspberry pi armhf?

### ISSUE THREAD

**Issue by rtulke** [vysheng/tg#770]
```
root@m45:/home/pi/# apt-get install libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev libevent-dev python-all-dev libjansson-dev

root@m45:/home/pi/# git clone https://github.com/vysheng/tg.git && cd tg

root@m45:/home/pi/tg#./configure
..
..
onfigure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
config.status: config.h is unchanged

root@m45:/home/pi/tg# make
make: *** No rule to make target 'tgl/scheme.tl', needed by 'auto/scheme.tl'.  Schluss.
```

**Comment by LukeLR** [comment]
Yes, it works on the Raspberry Pi very well. There are many folks around here using telegram on a Raspberry Pi, including me. The mistake you made, and the reason it doesn't work (yet), is, that you didn't clone recursively. Many people are running in this issue.

And nice to meet some German people on here :)

**Comment by rtulke** [comment]
Thx! that works for me :)

sudo apt-get install libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev libevent-dev python-all-dev libjansson-dev
git clone --recursive https://github.com/vysheng/tg.git && cd tg
./configure
make

**Comment by LukeLR** [comment]
Jep! That’s how the installation process usually looks like. You got it right ;)
