### ISSUE TITLE
support for new broadcast

### ISSUE THREAD

**Issue by nullifye** [vysheng/tg#779]
hi vysheng. first and foremost thank for the great tg & lua implementation on it.

when you will be including new broadcast with unlimited users that released yesterday? appreciate it if it available in lua.

really need that new broadcast method.

thank you for your hardwork.

**Comment by psycholyzern** [comment]
+1

**Comment by salimionnet** [comment]
+1

**Comment by h4ppysmile** [comment]
+1

**Comment by mjota** [comment]
+1

**Comment by GabrielRF** [comment]
Go to #781

**Comment by ronromer** [comment]
+1
