### ISSUE TITLE
Telegram Channels - Post command

### ISSUE THREAD

**Issue by GabrielRF** [vysheng/tg#784]
I know I might be going faster them I should, but here goes my question:

I'm trying to use branch test to send messages to channels.
When I run ```bin/telegram-cli -k tg-server.pub``` and then
```
channel_list
post channelName msg
```
everything runs without problems.

The problem (and my question) is: Is it possible to send everything like I send messages using, for example, `bin/telegram-cli -k tg-server.pub -e msg user#id msg`?
I'm obliged to run `channel_list` before sending message to channels. I would like to run `channel_list`and `post` on a single line. Is it possible?

**Comment by GabrielRF** [comment]
```
bin/telegram-cli -k tg-server.pub -W -e "post ChannelName Message"
```
Now works perfectly! Thanks @vysheng

**Comment by prografr** [comment]
Great Gabriel.. when your branch will merge? we do need posting to channels..
is there anyway that we can use this feature now?

**Comment by GabrielRF** [comment]
The branch is not mine. If you click on the commit I said you will see it.

**Comment by rasool083** [comment]
Hi, I start using ubuntu just now and using telegram cli . 
could you please help me post on channel and add member on channel step by step
I just install it so I think it must had some requirement
thanks
