### ISSUE TITLE
Test branch make error

### ISSUE THREAD

**Issue by behnammby** [vysheng/tg#787]
I was about to make test branch. firstly I got the branch using this command:
git clone --recursive -b test https://github.com/vysheng/tg.git
 then:
./configure 
make
but I had the following error while making:

interface.c: In function ‘our_id_gw’:
interface.c:2742:5: error: incompatible type for argument 1 of ‘lua_our_id’
     lua_our_id (id);
     ^
In file included from interface.c:65:0:
lua-tg.h:27:6: note: expected ‘int’ but argument is of type ‘tgl_peer_id_t’
 void lua_our_id (int id);
      ^
interface.c:2745:5: error: incompatible type for argument 1 of ‘py_our_id’
     py_our_id (id);
     ^
In file included from interface.c:25:0:
python-tg.h:30:6: note: expected ‘int’ but argument is of type ‘tgl_peer_id_t’
 void py_our_id (int id);
      ^
Makefile:48: recipe for target 'objs/interface.o' failed
make: *** [objs/interface.o] Error 1

**Comment by behnammby** [comment]
ok I found the problem. Since json, lua and python does not work yet we should disable them while configuring:

./configure --disable-python --disable-json --disable-liblua

**Comment by Tak-MK** [comment]
Thanks! It works for me!

**Comment by avineha** [comment]
Hi,

I did the same however Its not working for me,issue as below.

gcc -I. -I. -I./tgl -g -O2 -I/usr/local/include -I/usr/include -I/usr/include -I/usr/include/python3.4m -DHAVE_CONFIG_H -Wall -Werror -Wextra -Wno-missing-field-initializers -Wno-deprecated-declarations -fno-strict-aliasing -fno-omit-frame-pointer -ggdb -Wno-unused-parameter -fPIC -c -MP -MD -MF dep/interface.d -MQ objs/interface.o -o objs/interface.o interface.c
interface.c: In function ‘our_id_gw’:
interface.c:3090:5: error: incompatible type for argument 1 of ‘py_our_id’
py_our_id (id);
^
In file included from interface.c:25:0:
python-tg.h:30:6: note: expected ‘int’ but argument is of type ‘tgl_peer_id_t’
void py_our_id (int id);
^
Makefile:48: recipe for target 'objs/interface.o' failed
make: *** [objs/interface.o] Error 1

Please do needful help
