### ISSUE TITLE
No public keys found

### ISSUE THREAD

**Issue by waynerobinson** [vysheng/tg#796]
This feels like a stupid question and I'd like to apologise in advance for it.

I currently use Telegram with native clients on my Mac/iPhone. I've just installed the `tg` client and have no idea how to actually start using it.

When I run it all I get is:

```
Telegram-cli version 1.3.3, Copyright (C) 2013-2015 Vitaly Valtman
Telegram-cli comes with ABSOLUTELY NO WARRANTY; for details type `show_license'.
This is free software, and you are welcome to redistribute it
under certain conditions; type `show_license' for details.
Telegram-cli uses libtgl version 2.0.3
Telegram-cli includes software developed by the OpenSSL Project
for use in the OpenSSL Toolkit. (http://www.openssl.org/)
Telegram-cli uses libpython version 2.7.10
I: config dir=[/Users/waynerobinson/.telegram-cli]
 *** No public keys found
```

I understand that I probably need to generate keys for this client (or use the same ones used in the GUI client on my Mac), but I can't seem to see how/where to create these.

Is anyone able to help?

**Comment by beMoD** [comment]
Hi Wayne,

the client needs the public key of the telegram serverinfrastracture. The keyfile is beeing shiped within this package as server.pub. You have to run telegram with `-k /path/to/server.pub`. You should also include the `-W` parameter, to load the contact list on startup.

HTH,
beMoD

**Comment by waynerobinson** [comment]
Thanks for this. Knew I missed something somewhere.
