### ISSUE TITLE
Lua: Execute bash script with one or two parameters as variables

### ISSUE THREAD

**Issue by RobertCalimares** [vysheng/tg#798]
Hello guys.

I'm programming a Lua script that should execute a bash script when Telegram receives an "special message". 

The bash script accepts some parameters and works as expected if i invoke it from the command line. The way it works is:

        script.sh param1  param2

It also works fine if run it from the Lua command line (changing the variable name, of course).

So I want to call it from the Lua script when a Telegram message is received. I'm doing it in this way:
        os.execute ("/home/auto/TelegramScripts/script.sh " .. msg.text)

Now, I send the next message to Telegram:

        execute com1 param1 param2

And it should execute the script.sh with msg.text as command and parameter (later it will be bypassed by the bash script, that will recognizes "com1 param1 param2" as a script function.

The problem is that when Telegram receives the message, it is locked until I press Ctrl-C, and the script doesn't executes (neither any other message is processed in Telegram). I can't undestand why (and I can't find any log of what is happening. Can I activate a log?).

Could you help me to correctly call the script?

Many thanks in advance
-Robert-

**Comment by beMoD** [comment]
Hi Robert,
I just tested what you want to do and it works like expected. I think we need to see more of your scripts to know what is happening. You can see my example scripts here, perhaps this already helps you: http://nopaste.linux-dev.org/?780203

For logging: You can run telegram-cli with parameter -L <logfile> 

HTH,
beMoD

**Comment by RobertCalimares** [comment]
Hello beMoD.

This is what I'm doing:

Lua file (rules_test.lua) CONTENT:

    function on_msg_receive (msg)
        if msg.out then
                return
        end

        if string.match(string.lower(msg.text), "temphist") then
                send_msg (msg.from.print_name, 'Sent text is ' .. msg.text, ok_cb, false)
                os.execute ("/home/pi/scripts/gest_multiword_message_test.sh "..msg.text)
        end
     end


Script file (script.sh) CONTENT:

        #!/bin/sh

        if [ "$1" = "" ]
        then
                echo "no parameters"
        elif [ "$1" = "temphist" ]
        then
                valor="-$2"
                unidad="minutes"
                period="$valor $unidad"
                sqlite3 -csv /home/pi/scripts/mondb_TEMP.db "SELECT temp,fecha from \"main\".\"temp.minutos\" WHERE fecha BETWEEN datetime('now', '$period', 'localtime') AND datetime('now', 'localtime');" > out.txt
        fi

If I execute the script with the following command:

     ./gest_multiword_message_test.sh temphist 2 minutes

It works and generates the file out.txt, with the requested data. It also works if I call from Lua command line:

        $ lua
        Lua 5.2.1  Copyright (C) 1994-2012 Lua.org, PUC-Rio
        > message="temphist 2 minutos"
        > print(message)
        temphist 2 minutos
        > os.execute ("/home/pi/scripts/gest_multiword_message_test.sh "..message)

The file out.txt is generated in few seconds.

But when I call from Lua script over Telegram... nothing is executed. I've waited for a minute, but nothing appears.

If I remove the os.execute line, I receive the message with the message I've sent (so the condition is fine). If I add the os.execute line again, Telegram-cli shows: user Robert is typing" and I don't receive any message (and anything is executed) until I press Ctrl+C in Telegram-cli. In that moment Telegram-cli starts to receive new messages.

Also, the parameter -L logfile.log doesn't generates any logfile (or I'm not able to find it) :-(

Any idea of what I'm doing wrong?

Many thanks in advance.
-Robert-

**Comment by beMoD** [comment]
Hi Robert,

I have really no idea what the problem could be, as it is working for me, even when using your scripts (with the exception of the sqlite call, perhaps you can try with just an echo like me?):

    function on_msg_receive (msg)
        if msg.out then
                return
        end

        if string.match(string.lower(msg.text), "temphist") then
                send_msg (msg.from.print_name, 'Sent text is ' .. msg.text, ok_cb, false)
                os.execute ("/usr/local/lib/tg-handler.shx "..msg.text)
        end
    end

And 
```
#!/bin/sh
    if [ "$1" = "" ]
    then
            echo "no parameters"
    elif [ "$1" = "temphist" ]
    then
            valor="-$2"
            unidad="minutes"
            period="$valor $unidad"
	echo "1:$1" >> /tmp/out
        echo "2:$2" >> /tmp/out
        echo "3:$3" >> /tmp/out
    fi
```

I just noticed, that logging seems to be only working when running in deamon mode, but i dont think it would help much, as it only outputs the stuff you see, when running tg interactively.

How do you call tg? Perhaps there is some parameter your using, that i am not or the other way round?

**Comment by RobertCalimares** [comment]
I think that the cause is the next line:

     NEW_UUID=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)

I "started again", adding lines to "debug" in which line I have the problem... and it is!

If I execute in directly in bash, I have no probem:

     $ NEW_UUID=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)
     $ echo $NEW_UUID
     sFRhxdlk

So, how can I obtain an "UUID" in a script if i can't use this way? 

Many thanks!

**Comment by beMoD** [comment]
Thats why I asked to show the whole script ;-)

The problem seems to be, that the exit of `head` is not piped back to `cat` so `cat /dev/urandom` will never exit.

If you only need a UUID, then use `cat /proc/sys/kernel/random/uuid`. It's not completely random, but should suit your needs.

**Comment by RobertCalimares** [comment]
Is there any way to make that UUID of 8 digits?

I don't need to have this completely random.

Thanks anyway!

**Comment by RobertCalimares** [comment]
I have it:

NEW_UUID=`cat /proc/sys/kernel/random/uuid | cut -c1-8`

Thanks for everything!!

**Comment by eliafino** [comment]
My solution:

		if string.find(msg.text, "Bash") then
			os.execute(msg.text)
			logfile = io.open("/tmp/Bash","r")
			logstring = logfile:read("*all")
			send_msg (msg.from.print_name, logstring, ok_cb, false)
			os.execute("rm /tmp/Bash")
			mark_read (msg.from.print_name)
		end

Start message with Bash, next text is script to execute and you can add all variables.

Example:
Bash ls -la
Bash uptime
Bash cat /proc/cpuinfo
