### ISSUE TITLE
problem in install test branch

### ISSUE THREAD

**Issue by salimionnet** [vysheng/tg#799]
after run command make : make: *** [objs/interface.o] Error 1

please help me

**Comment by RobertCalimares** [comment]
Hello salimionnet.

Could you paste all result of the command "make"?

**Comment by iambillywilly** [comment]
Same problem with me, here result after run make:

gcc -I. -I. -I./tgl -g -O2  -I/usr/local/include -I/usr/include -I/usr/include -I/usr/include/lua5.2 -I/usr/include/python2.7   -DHAVE_CONFIG_H -Wall -Werror -Wextra -Wno-missing-field-initializers -Wno-deprecated-declarations -fno-strict-aliasing -fno-omit-frame-pointer -ggdb -Wno-unused-parameter -fPIC -iquote ./tgl/tl-parser -c -MP -MD -MF dep/tl-parser.d -MQ objs/tl-parser.o -o objs/tl-parser.o tgl/tl-parser/tl-parser.c
gcc -I. -I. -I./tgl -g -O2  -I/usr/local/include -I/usr/include -I/usr/include -I/usr/include/lua5.2 -I/usr/include/python2.7   -DHAVE_CONFIG_H -Wall -Werror -Wextra -Wno-missing-field-initializers -Wno-deprecated-declarations -fno-strict-aliasing -fno-omit-frame-pointer -ggdb -Wno-unused-parameter -fPIC -iquote ./tgl/tl-parser -c -MP -MD -MF dep/tlc.d -MQ objs/tlc.o -o objs/tlc.o tgl/tl-parser/tlc.c
gcc objs/tl-parser.o objs/tlc.o -L/usr/local/lib -L/usr/lib -L/usr/lib   -rdynamic -ggdb -levent -ljansson -lconfig -lz -levent -lrt   -lreadline -llua5.2  -lm -ldl -lpython2.7 -lssl -lcrypto   -ldl -lpthread -lutil -o bin/tl-parser
objs/tl-parser.o: In function `tl_count_combinator_name':
/root/tg/tgl/tl-parser/tl-parser.c:1409: undefined reference to `compute_crc32'
collect2: error: ld returned 1 exit status
make: *** [bin/tl-parser] Error 1

**Comment by RobertCalimares** [comment]
Be sure that you have the next utilities installed:
     $ sudo apt-get update
     $ sudo apt-get install bc telnet libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev libevent-dev make libjansson-dev

Then, clone the Github repo:

     $ git clone --recursive https://github.com/vysheng/tg.git && cd tg

Configure:
     $ ./configure

And make:
     $ make

**Comment by iambillywilly** [comment]
I did everything that you said, but still same error. How to switch to test branch after cloning? I did the following

<pre>git branch -a</pre>

<pre>* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
  remotes/origin/test</pre>

then 

<pre>git checkout -b test origin/test</pre>

**Comment by psycholyzern** [comment]
1. go into any directory you want to install tg-cli test branch. It it recommended to make separate folder from tg-cli master brance.
2. ```git clone --recursive -b test https://github.com/vysheng/tg.git tg-test && cd tg-test```
3. ```./configure```
4. ```make```

Now your tg-cli will be installed in folder tg-test.

Note: I had to run ```./configure --disable-python``` on step 4 because I got python error.

**Comment by iambillywilly** [comment]
Thank you very much! It's help me!

**Comment by psycholyzern** [comment]
please close this issue if solved :)

**Comment by iambillywilly** [comment]
I can't, it's not my issue ))

**Comment by psycholyzern** [comment]
oops.. Silly me xD

**Comment by Zenexer** [comment]
For future reference: if you perform a checkout AFTER you've cloned master, you need to update the submodules.  For example:

``` bash
git clone --recursive ...
# Do some stuff, decide you want to switch to test branch
git checkout test
# These are the key steps:
git submodule init
git submodule update
```

**Comment by igorfraa** [comment]
> git submodule --recursive update

**exactly this is key.**

_It is frustratingly difficult to guess that a project uses nested submodules._
