### ISSUE TITLE
Download all photos from a contact

### ISSUE THREAD

**Issue by dlion** [vysheng/tg#808]
There is a way to download all photos from a contact media gallery ?
I shared with a contact many photos and I want to download all of them, there is a way to do it ?

**Comment by zerodwide** [comment]
i wanted that too, but in all command list as i searched, there was nothing like that! 
by the way in official telegram api that exist.

**Comment by coriumalpha** [comment]
[tvdstaaij/telegram-history-dump](https://github.com/tvdstaaij/telegram-history-dump/) solved it for me :)
Now I'm able to backup my full history to a JSON including the mediafiles.

**Comment by dlion** [comment]
> tvdstaaij/telegram-history-dump solved it for me :)
> Now I'm able to backup my full history to a JSON including the mediafiles.

Awesome, thanks!
