### ISSUE TITLE
problem in test branch

### ISSUE THREAD

**Issue by salimionnet** [vysheng/tg#809]
Telegram-cli version 1.4.1, Copyright (C) 2013-2015 Vitaly Valtman
Telegram-cli comes with ABSOLUTELY NO WARRANTY; for details type `show_license'.
This is free software, and you are welcome to redistribute it
under certain conditions; type `show_license' for details.
Telegram-cli uses libtgl version 2.1.0
Telegram-cli includes software developed by the OpenSSL Project
for use in the OpenSSL Toolkit. (http://www.openssl.org/)
I: config dir=[/home/telegramd/.telegram-cli]
> telegram-cli: tgl/queries.c:114: tree_insert_query: Assertion `c' failed.
SIGNAL received
tbin/telegram-cli(print_backtrace+0x20)[0x4671d0]
bin/telegram-cli(termination_signal_handler+0x64)[0x467254]
/lib64/libc.so.6(+0x326a0)[0x7fc3001856a0]
/lib64/libc.so.6(gsignal+0x35)[0x7fc300185625]
/lib64/libc.so.6(abort+0x175)[0x7fc300186e05]
/lib64/libc.so.6(+0x2b74e)[0x7fc30017e74e]
/lib64/libc.so.6(__assert_perror_fail+0x0)[0x7fc30017e810]
bin/telegram-cli[0x48a881]
bin/telegram-cli[0x48a7ac]
bin/telegram-cli[0x48a81b]
bin/telegram-cli[0x48c2c4]
/usr/lib64/libevent-1.4.so.2(event_base_loop+0x3e4)[0x7fc302087b44]
bin/telegram-cli(net_loop+0xbe)[0x46af2e]
bin/telegram-cli(loop+0x1c7)[0x46b1d7]
bin/telegram-cli(main+0x2d8)[0x468938]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x7fc300171d5d]
bin/telegram-cli[0x466f29]

please refer me how to resolve it,thank.

**Comment by psycholyzern** [comment]
remove folder .telegram-cli

**Comment by salimionnet** [comment]
Thank you, my problem is solved.
