### ISSUE TITLE
there is a way to see all members on channel?

### ISSUE THREAD

**Issue by iambillywilly** [vysheng/tg#816]
There is a way to see all members on channel?

**Comment by vysheng** [comment]
ok, added it. channel_get_members.

**Comment by nullifye** [comment]
nice

**Comment by iambillywilly** [comment]
Coool! )) One question, how many members can I get? I have more than 2k members but it showed me only 200

**Comment by vysheng** [comment]
@iambillywilly 

I don't have such big channels, can't check.

But API method name suggests that it is list of recent users. What does it really mean I don't know. Maybe it is list of last joined (with some limit) or maybe it means that they are sorted in join order.

**Comment by mallakimahdi** [comment]
I can't see the `channel_get_members` target in cli. where is it?
