### ISSUE TITLE
msg attributes in LUA

### ISSUE THREAD

**Issue by rettama** [vysheng/tg#825]
Hi, in order to explore the limits of this code, id like to know where i can read which "attributes" has msg.
I find in the code  msg.from.print_name or msg.text, but id like to see all to keep working.

Thank you so much, i hope i check all repository and the answer wouldnt be easy to find.

**Comment by beMoD** [comment]
Hey,

msg has following attributes:
[to] = (table)
.[print_name] = (string) be_Pi
.[flags] = (number) 267
.[type] = (string) user
.[access_hash] = (number) 1
.[last_name] = (string) Pi
.[phone] = (string) 4915254019666
.[first_name] = (string) be
.[id] = (number) 116885623
[service] = (boolean) false
[id] = (string) 1158
[flags] = (number) 257
[date] = (number) 1445370424
[text] = (string) Test
[out] = (boolean) false
[unread] = (boolean) true
[from] = (table)
.[print_name] = (string) be_handy
.[flags] = (number) 259
.[type] = (string) user
.[access_hash] = (number) 1
.[last_name] = (string) handy> 
.[phone] = (string) 4915701128896
.[first_name] = (string) be
.[id] = (number) 36134131

HTH,
beMoD

**Comment by rettama** [comment]
Thank you so much.
