### ISSUE TITLE
user_info command not show the last connection

### ISSUE THREAD

**Issue by mfuentesg** [vysheng/tg#831]
When the --json is set the result not has last connection

Example:

```json
{
  "phone": "1111111", 
  "type": "user", 
  "id": 1414, 
  "print_name":  "foo_bar", 
  "flags": 111, 
  "first_name": "foo", 
  "last_name": "bar"
}
```

**Comment by comtihon** [comment]
Hi, @mfuentesg , could you please help me with https://github.com/vysheng/tg/issues/844 
Simple question, and, if you are able to get info from user_info - you can solve it.

**Comment by mfuentesg** [comment]
You need pass the print_name, for example. 
If you add a contact with first name 'foo' and last name 'bar' the print name or <peer> will be 'foo_bar'.

Try to adding a user 

```
add_contact PHONE "foo" "bar"%
```
