### ISSUE TITLE
Telegram-cli crash

### ISSUE THREAD

**Issue by juanremi** [vysheng/tg#832]
hey guys,

i'm having the next problem, when i initialize telegram-cli, it crash

Telegram-cli version 1.3.3, Copyright (C) 2013-2015 Vitaly Valtman
Telegram-cli comes with ABSOLUTELY NO WARRANTY; for details type `show_license'.
This is free software, and you are welcome to redistribute it
under certain conditions; type `show_license' for details.
Telegram-cli uses libtgl version 2.0.3
Telegram-cli includes software developed by the OpenSSL Project
for use in the OpenSSL Toolkit. (http://www.openssl.org/)
Telegram-cli uses libpython version 2.6.6
I: config dir=[/home/notitg/.telegram-cli]
 *** Skipped 1 int out of 16 (type Config)
 *** 0x7ae432f5 0x13ce24bb
> telegram-cli: tgl/queries.c:428: tglq_query_result: Assertion `0' failed.
SIGNAL received
t/home/notitg/public_html/tgv1/tg133/bin/telegram-cli(print_backtrace+0x20)[0x46f6a0]
/home/notitg/public_html/tgv1/tg133/bin/telegram-cli(termination_signal_handler+0x64)[0x46f724]
/lib64/libc.so.6(+0x326a0)[0x7f59286756a0]
/lib64/libc.so.6(gsignal+0x35)[0x7f5928675625]
/lib64/libc.so.6(abort+0x175)[0x7f5928676e05]
/lib64/libc.so.6(+0x2b74e)[0x7f592866e74e]
/lib64/libc.so.6(__assert_perror_fail+0x0)[0x7f592866e810]
/home/notitg/public_html/tgv1/tg133/bin/telegram-cli(tglq_query_result+0x46c)[0x496fbc]
/home/notitg/public_html/tgv1/tg133/bin/telegram-cli[0x49499e]
/home/notitg/public_html/tgv1/tg133/bin/telegram-cli[0x4b6dab]
/usr/lib64/libevent-1.4.so.2(event_base_loop+0x3e4)[0x7f592a91db44]
/home/notitg/public_html/tgv1/tg133/bin/telegram-cli(net_loop+0xb5)[0x473395]
/home/notitg/public_html/tgv1/tg133/bin/telegram-cli(loop+0x1dc)[0x4736dc]
/home/notitg/public_html/tgv1/tg133/bin/telegram-cli(main+0x2c6)[0x470dd6]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x7f5928661d5d]
/home/notitg/public_html/tgv1/tg133/bin/telegram-cli[0x46f3f9]

sometimes it initialize fine, but the command "contact_list" dont response and then it can crash too

Telegram-cli version 1.3.3, Copyright (C) 2013-2015 Vitaly Valtman
Telegram-cli comes with ABSOLUTELY NO WARRANTY; for details type `show_license'.
This is free software, and you are welcome to redistribute it
under certain conditions; type `show_license' for details.
Telegram-cli uses libtgl version 2.0.3
Telegram-cli includes software developed by the OpenSSL Project
for use in the OpenSSL Toolkit. (http://www.openssl.org/)
Telegram-cli uses libpython version 2.6.6
I: config dir=[/home/notitg/.telegram-cli]
> contact_list
> contact_list
> contact_list
> msg juan_telcel hola
FAIL: 38: can not parse arg #1
 *** Skipped 1 int out of 16 (type Config)
 *** 0x7ae432f5 0x13cbce4b
> telegram-cli: tgl/queries.c:428: tglq_query_result: Assertion `0' failed.
SIGNAL received
t/home/notitg/public_html/tgv1/tg133/bin/telegram-cli(print_backtrace+0x20)[0x46f6a0]
/home/notitg/public_html/tgv1/tg133/bin/telegram-cli(termination_signal_handler+0x64)[0x46f724]
/lib64/libc.so.6(+0x326a0)[0x7fad3abf36a0]
/lib64/libc.so.6(gsignal+0x35)[0x7fad3abf3625]
/lib64/libc.so.6(abort+0x175)[0x7fad3abf4e05]
/lib64/libc.so.6(+0x2b74e)[0x7fad3abec74e]
/lib64/libc.so.6(__assert_perror_fail+0x0)[0x7fad3abec810]
/home/notitg/public_html/tgv1/tg133/bin/telegram-cli(tglq_query_result+0x46c)[0x496fbc]
/home/notitg/public_html/tgv1/tg133/bin/telegram-cli[0x49499e]
/home/notitg/public_html/tgv1/tg133/bin/telegram-cli[0x4b6dab]
/usr/lib64/libevent-1.4.so.2(event_base_loop+0x3e4)[0x7fad3ce9bb44]
/home/notitg/public_html/tgv1/tg133/bin/telegram-cli(net_loop+0xb5)[0x473395]
/home/notitg/public_html/tgv1/tg133/bin/telegram-cli(loop+0x1dc)[0x4736dc]
/home/notitg/public_html/tgv1/tg133/bin/telegram-cli(main+0x2c6)[0x470dd6]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x7fad3abdfd5d]

**Comment by juanremi** [comment]
Telegram was down around 30 minuts
https://twitter.com/telegram/status/658475586088783872

but now is up
https://twitter.com/telegram/status/658485054142857216

**Comment by LukeLR** [comment]
There was no outage for me, I've been using telegram constantly without problems. And yes, I'm from Europe.
