### ISSUE TITLE
How to send a message to an existing chat group I'm already member of?

### ISSUE THREAD

**Issue by sohamakl** [vysheng/tg#835]
Hopefully someone can assist me. I do not understand how to send a message to a chat group that already exists and I'm a member of.

Creating a new chat with multiple users from within telegram-cli is working very well and I'm able to send messages imminently. After closing the client and restarting again I'm no longer able to send a message to the defined chat group (FAIL: 38: can not parse arg #1). I noticed that I can send again after I have received a group chat message before. 

Any idea what's going wrong?

**Comment by sohamakl** [comment]
It was my fault using the wrong dash in front of the W parameter.

/tg/bin/telegram-cli -k tg-server.pub -W

**Comment by LukeLR** [comment]
You need to fetch the list of all your chats once each time tg-cli starts. Only after that is done, you can access chats that are already existing, no matter if individual or group chats. This is done by
a) passing the -W flag to the tg-cli binary
b) manually executing dialog_list after startup before sending any messages

This is not a bug, it's a wanted behaviour, and it was asked around 20 times before :) It's difficult if you don't know that fact…

**Comment by LukeLR** [comment]
Ah, sorry, didn't notice that you already solved your issue when checking my GitHub mails :)
