### ISSUE TITLE
how to call user_info

### ISSUE THREAD

**Issue by comtihon** [vysheng/tg#844]
Hi!
I run telegram_cli this way : `telegram-cli --json -C -R`
Than add some user: `add_contact PHONE 0 0 \n`
and got some info:

    [{\"id\": ID, \"type\": \"user\", \"phone\": \"PHONE\", \"print_name\": \"\", \"flags\": 257}]
Than I want to get user's info with user_info cmd.
As far, as I understand - I should use id as an argument, but calling `user_info ID` cause:

    FAIL: 38: can not parse arg #1
Also, passing json object `{"id" : ID}` not works.
What should I pass to get user_info?

**Comment by Kampring** [comment]
same with me, command user_info not work

**Comment by ledazinha** [comment]
For me it works with either of these:

```
user_info user#ID
```

(must prefix the ID with "user#"), or:

```
user_info PRINT_NAME
```

**Comment by mfuentesg** [comment]
You can use:

```bash
#show your contacts, with the print name
contact_list

#get the user information
user_info <print_name>
```

**Comment by Kampring** [comment]
confirm, work with underscore <firstname_lastname>
thanks

**Comment by comtihon** [comment]
Thanks!
`user_info user#ID` is suitable for me.
