### ISSUE TITLE
Can I bind -P not to local interface only

### ISSUE THREAD

**Issue by korjavin** [vysheng/tg#854]
I run telegram_cli inside a docker container.
I started tg with -P 1234 and it listens to 
```
# netstat -4na
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 127.0.0.1:1234          0.0.0.0:*               LISTEN  
```

I need to communicate with it from my another docker container, and it looks like impossible to do it.
I can't forward this port outside.
I tried it with docker's -P, but it doesn't work
![_001](https://cloud.githubusercontent.com/assets/148765/11221825/f9212e5a-8d88-11e5-8154-5329db54f46b.png)

-P0.0.0.0:1234 will solve my problem.

Is it possible to use it?

**Comment by beMoD** [comment]
I think `--accept-any-tcp` is what you want.

**Comment by korjavin** [comment]
Oh, yes, it is.
Thank you a lot.
