### ISSUE TITLE
Support for new supergroups

### ISSUE THREAD

**Issue by ticoti** [vysheng/tg#870]
Can you add support for new supergroups?
It doesn't work with them now

**Comment by nullifye** [comment]
already implemented.
https://github.com/vysheng/tg/commit/c61c8ba9faec23c7604a78b8c254ffced47ab617

**Comment by buzz3rs** [comment]
when i try upgrading my tg i get this error anyone knows why ?
No rule to make target `interface.c', needed by `objs/interface.o'.  Stop.
