### ISSUE TITLE
error #400: AUTH_BYTES_INVALID

### ISSUE THREAD

**Issue by leandrosouza** [vysheng/tg#895]
I just dowloaded the tg, but always return error 400 after I put the login code

bin/telegram-cli -k /etc/telegram-cli/server.pub -W -vvvv
Telegram-cli version 1.3.3, Copyright (C) 2013-2015 Vitaly Valtman
Telegram-cli comes with ABSOLUTELY NO WARRANTY; for details type `show_license'.
This is free software, and you are welcome to redistribute it
under certain conditions; type `show_license' for details.
Telegram-cli uses libtgl version 2.0.3
Telegram-cli includes software developed by the OpenSSL Project
for use in the OpenSSL Toolkit. (http://www.openssl.org/)
Telegram-cli uses libpython version 2.7.6
I: config dir=[/home/telegramd/.telegram-cli]
 *** public key '/etc/telegram-cli/server.pub' loaded successfully
 *** public key '/etc/telegram-cli/server.pub' loaded successfully
 *** public key 'tg-server.pub' loaded successfully
 *** DC1 '' update: 149.154.175.50:443
 *** DC2 '' update: 149.154.167.51:443
 *** DC3 '' update: 149.154.175.100:443
 *** DC4 '' update: 149.154.167.91:443
 *** DC5 '' update: 149.154.171.5:443
 *** outbound rpc connection from dc #1 becomed ready
 *** outbound rpc connection from dc #3 becomed ready
 *** outbound rpc connection from dc #2 becomed ready
 *** outbound rpc connection from dc #4 becomed ready
 *** outbound rpc connection from dc #5 becomed ready
 *** adjusting CLOCK_MONOTONIC delta to -0.618781
 *** DC1 '' update: 2001:0b28:f23d:f001:0000:0000:0000:000a:443
 *** DC2 '' update: 2001:067c:04e8:f002:0000:0000:0000:000a:443
 *** DC3 '' update: 2001:0b28:f23d:f003:0000:0000:0000:000a:443
 *** DC4 '' update: 2001:067c:04e8:f004:0000:0000:0000:000a:443
 *** DC4 '' update: 149.154.165.120:443
 *** DC5 '' update: 91.108.56.165:443
 *** DC5 '' update: 2001:0b28:f23f:f005:0000:0000:0000:000a:443
 *** adjusting CLOCK_MONOTONIC delta to 0.275367
 *** adjusting CLOCK_MONOTONIC delta to 0.332919
 *** adjusting CLOCK_MONOTONIC delta to 0.240266
 *** adjusting CLOCK_MONOTONIC delta to -0.427034
phone number: +5521993883029
 *** error for query #6227920037489926144: #303 PHONE_MIGRATE_1 (HANDLED)
 *** Alarm query 6227920037489926144
code ('CALL' for phone code): 71175
 *** error for query #6227920079328264192: #400 AUTH_BYTES_INVALID
> error #400: AUTH_BYTES_INVALID
telegram-cli: tgl/queries.c:225: fail_on_error: Assertion `0' failed.
SIGNAL received
h/usr/share/telegram-daemon/bin/telegram-cli(print_backtrace+0x20)[0x46f740]
/usr/share/telegram-daemon/bin/telegram-cli(termination_signal_handler+0x64)[0x46f7c4]
/lib/x86_64-linux-gnu/libc.so.6(+0x36d40)[0x7fc0b327cd40]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x39)[0x7fc0b327ccc9]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x148)[0x7fc0b32800d8]
/lib/x86_64-linux-gnu/libc.so.6(+0x2fb86)[0x7fc0b3275b86]
/lib/x86_64-linux-gnu/libc.so.6(+0x2fc32)[0x7fc0b3275c32]
/usr/share/telegram-daemon/bin/telegram-cli[0x493898]
/usr/share/telegram-daemon/bin/telegram-cli(tglq_query_error+0x155)[0x4a1985]
/usr/share/telegram-daemon/bin/telegram-cli[0x492b8a]
/usr/share/telegram-daemon/bin/telegram-cli[0x4b4b8b]
/usr/lib/x86_64-linux-gnu/libevent-2.0.so.5(event_base_loop+0x754)[0x7fc0b4c1df24]
/usr/share/telegram-daemon/bin/telegram-cli(net_loop+0xa4)[0x470c74]
/usr/share/telegram-daemon/bin/telegram-cli(loop+0x195)[0x471f85]
/usr/share/telegram-daemon/bin/telegram-cli(main+0x2d3)[0x46dfe3]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7fc0b3267ec5]
/usr/share/telegram-daemon/bin/telegram-cli[0x46e0f3]

**Comment by ledazinha** [comment]
Same here, while trying to register a new phone

**Comment by ledazinha** [comment]
Solved. It was just a permission problem on the profile folder - it was created with my user account, instead of the telegramd:telegramd account.

**Comment by leandrosouza** [comment]
Thanks @ledazinha Its work for me
