### ISSUE TITLE
Reply message using user_id

### ISSUE THREAD

**Issue by RobertCalimares** [vysheng/tg#898]
Hello.

I'm trying to reply messages to users using ther "user_id"; not their "Name".

In my Lua script, this is what i'm trying:

	if string.lower(msg.text)=='test' then
		send_msg (user_id, 'test back', ok_cb, false)
	end

I'ts not working. But the following one does:

	if string.lower(msg.text)=='test' then
		send_msg (msg.from.print_name, 'test back', ok_cb, false)
	end

But I don't like to use "msg.from.print_name" to identify users; I need to reply the using their "user_id"; not their names. 

If I know the user_id, i can do it using this code:

	send_photo user#XX /path/to/photo "photo description"

But without knowing, I can't find how to do it.

Could anybody help me to accomplish this?

Thank you and best regards
-Robert-

**Comment by LukeLR** [comment]
user_id is NOT the field containing the sender's id - how could it? It has no relation to the msg-table being passed to the on_msg_received-function. You find any information you need inside the msg-table, like you did for print name :) Just have a look on it's fields, you'll find whatever you need ;)

**Comment by RobertCalimares** [comment]
Excuse me, but I don't know how to "see" inside the msg-table. Could you "guide" me a little bit?

Thank you!

**Comment by beMoD** [comment]
Hi,

I posted a var dump of the msg table here: #825

**Comment by RobertCalimares** [comment]
Thank you, beMoD,

I've tried this:

        if string.lower(msg.text)=='test' then
                send_msg (msg.from.id, 'test back', ok_cb, false)
        end

But still not working. 

And other thing: how can I obtain that dump (or others)?

I remember, some year ago, when I was "playing" with .NET IDE; I could enter "object_name." and the possible options appears with the corresponding help (something like "button.property.color"), but with this, 

Could you help me?

**Comment by beMoD** [comment]
Hi Robert,

I used the vardump function provided in the test.lua file https://github.com/vysheng/tg/blob/master/test.lua

hth,
beMoD

**Comment by RobertCalimares** [comment]
Perfect.

Thank you!

**Comment by LukeLR** [comment]
Exactly that vardump function I wanted to recommend… :)
