### ISSUE TITLE
Assertion failed: (0), function print_media, file interface.c, line 3446. SIGNAL received

### ISSUE THREAD

**Issue by vahidhashemi** [vysheng/tg#914]
Don't know why but I get following error this morning. the telegram-cli was working perfectly until last night.

Assertion failed: (0), function print_media, file interface.c, line 3446.
SIGNAL received
S0   telegram-cli                        0x000000010416f79a print_backtrace + 42
1   telegram-cli                        0x000000010416f8a7 termination_signal_handler + 199
2   libsystem_platform.dylib            0x00007fff8f7e95aa _sigtramp + 26
3   ???                                 0x0000000000000002 0x0 + 2
4   libsystem_c.dylib                   0x00007fff92ca4b1a abort + 125
5   libsystem_c.dylib                   0x00007fff92c6e9bf basename + 0
6   telegram-cli                        0x00000001041879cd print_media + 5325
7   telegram-cli                        0x00000001041820d3 print_message + 3555
8   telegram-cli                        0x0000000104183ed3 print_message_gw + 307
9   telegram-cli                        0x00000001041d710a fetch_comb_binlog_msg_update + 314
10  telegram-cli                        0x00000001041cec5b replay_log_event + 2235
11  telegram-cli                        0x00000001041cf1f5 add_log_event + 325
12  telegram-cli                        0x00000001041d060b bl_do_msg_update + 91
13  telegram-cli                        0x00000001041b841c get_difference_on_answer + 1356
14  telegram-cli                        0x00000001041aab20 tglq_query_result + 1232
15  telegram-cli                        0x00000001041a6cd6 work_rpc_result + 214
16  telegram-cli                        0x00000001041a65ae rpc_execute_answer + 734
17  telegram-cli                        0x00000001041a60dd process_rpc_message + 3037
18  telegram-cli                        0x00000001041a3bad rpc_execute + 829
19  telegram-cli                        0x00000001041de17a try_rpc_read + 1082
20  telegram-cli                        0x00000001041ddb59 try_read + 585
21  telegram-cli                        0x00000001041dd67d conn_try_read + 109
22  libevent-2.0.5.dylib                0x0000000111739784 event_base_loop + 1858
23  telegram-cli                        0x0000000104170779 net_loop + 185
24  telegram-cli                        0x0000000104173a2c loop + 956
25  telegram-cli                        0x000000010416ec4d inner_main + 13
26  telegram-cli                        0x000000010416fff5 main + 1429
27  libdyld.dylib                       0x00007fff8d1f25fd start + 1

**Comment by lucasberti** [comment]
See #904.
