### ISSUE TITLE
Telegram-cli used all my 16GB RAM

### ISSUE THREAD

**Issue by psycholyzern** [vysheng/tg#940]
- telegram-cli uptodate with master
- using with lua script

Today, I experienced a weird issue with telegram-cli. I was trying to upload a 900MB file then lua give "not enough memory" error. So I check the "top", this is what I got.
![](http://i.imgur.com/XcxGYD9h.jpg )

So I quit all running telegram cli (had 2 telegram-cli under 2 different username). But they still exist in process list. So I force killed them by running ```killall -9 telegram-cli```. What I got then are zombie processes
![](http://i.imgur.com/06scOqMh.jpg)

I tried several ways from the internet, but still can remove the zombie processes. I cant reboot my server for now, so I will bear with that issue.

The main point is, why telegram-cli ate my RAM? 
And, why telegram-cli keep failing uploading files? It send callback at random percent of uploading process, so lua "think" that the file was uploaded, then it delete the file.

**Comment by juanremi** [comment]
i think you are running bad the telegram cli, maybe you need to put a "sleep 1 sec" timer between the calls to telegram-cli and this can be the solution, or you can put here like a comment a piece of your code where you are running the service

**Comment by psycholyzern** [comment]
Hi. Thanks for the reply, and sorry for this late reply. I decided to use test branch and nosuch issue happened so far, yet.
