### ISSUE TITLE
create channel failed

### ISSUE THREAD

**Issue by PCodder** [vysheng/tg#960]
hi

when I want to create new channel receive this error:
"FAIL: 71: RPC_CALL_FAIL 400: INPUT_REQUEST_TOO_LONG"

used command :
"create_channel TestChannel aboutChannel hhhhh " // hhhh is a contact

group command work correctly with out any error:
"create_group_chat TestGroup  hhhhh " // hhhh is a contact

thanks

**Comment by PCodder** [comment]
before tried this way but it doesn’t work
https://github.com/vysheng/tg/issues/890#issuecomment-166259835

after many download and trying worked :+1:

**Comment by Exlord** [comment]
According to help the command is `create_channel <name> <about> <user>+`
Using it like `create_channel "MyChannel" "About" PeerName` results in the error `query 'forward messages' #6255879234897383176: #400 INPUT_REQUEST_TOO_LONG`
But `create_channel "MyChannel" "About"` works.
Also `create_channel "MyChannel" PeerName` works too.
But `create_channel "MyChannel" PeerName Peer2Name` doesn't work and gives the same error INPUT_REQUEST_TOO_LONG.
So how can we provide multiple users to the `<user>+` section ?

**Comment by yousofkakhki** [comment]
hi there ,
how can i add a contact to my channel or group
