### ISSUE TITLE
Error while compiling test on mac os x

### ISSUE THREAD

**Issue by mz1988** [vysheng/tg#996]
**i get this error
checking for uname... yes
checking for __builtin_bswap32... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
cat tgl/scheme.tl tgl/encrypted_scheme.tl tgl/binlog.tl tgl/append.tl tgl/mtproto.tl > auto/scheme.tl
gcc -I. -I. -I./tgl -g -O2  -I/usr/local/include -I/include   -DHAVE_CONFIG_H -Wall -Werror -Wextra -Wno-missing-field-initializers -Wno-deprecated-declarations -fno-strict-aliasing -fno-omit-frame-pointer -ggdb -Wno-unused-parameter -fPIC -iquote ./tgl/tl-parser -c -MP -MD -MF dep/tl-parser.d -MQ objs/tl-parser.o -o objs/tl-parser.o tgl/tl-parser/tl-parser.c
gcc -I. -I. -I./tgl -g -O2  -I/usr/local/include -I/include   -DHAVE_CONFIG_H -Wall -Werror -Wextra -Wno-missing-field-initializers -Wno-deprecated-declarations -fno-strict-aliasing -fno-omit-frame-pointer -ggdb -Wno-unused-parameter -fPIC -iquote ./tgl/tl-parser -c -MP -MD -MF dep/tlc.d -MQ objs/tlc.o -o objs/tlc.o tgl/tl-parser/tlc.c
gcc objs/tl-parser.o objs/tlc.o -L/usr/local/lib -L/lib  -rdynamic -ggdb -levent -ljansson -lconfig -lz -levent   -lreadline -llua  -lssl -lcrypto -lz  -ldl -lpthread -lutil -o bin/tl-parser
ld: warning: directory not found for option '-L/lib'
Undefined symbols for architecture x86_64:
  "_compute_crc32", referenced from:
      _tl_count_combinator_name in tl-parser.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/tl-parser] Error 1

**Comment by mz1988** [comment]
go into any directory you want to install tg-cli test branch. It it recommended to make separate folder from tg-cli master brance.
git clone --recursive -b test https://github.com/vysheng/tg.git tg-test && cd tg-test
./configure
make
Now your tg-cli will be installed in folder tg-test.

Note: I had to run ./configure --disable-python on step 4 because I got python error.
Note: for sure you get lua error use --disable-lualib

**Comment by luckydonald** [comment]
```
./configure --disable-lualib && make
```
```
lua-tg.c:664:27: error: unused function 'get_peer' [-Werror,-Wunused-function]
```
![ude  -I/usr/local/include -I/usr/include -I/usr/include   -DHAVE_CONFIG_H -Wall -Werror -Wextra -Wno-missing-field-initializers -Wno-deprecated-declarations -fno-strict-aliasing -fno-omit-frame-pointer -ggdb -Wno-unused-parameter -fPIC -c -MP -MD -MF dep/main.d -MQ objs/main.o -o objs/main.o main.c
gcc -I. -I. -I./tgl -I/usr/local/include -I/usr/local/Cellar/readline/6.3.8/include  -I/usr/local/include -I/usr/include -I/usr/include   -DHAVE_CONFIG_H -Wall -Werror -Wextra -Wno-missing-field-initializers -Wno-deprecated-declarations -fno-strict-aliasing -fno-omit-frame-pointer -ggdb -Wno-unused-parameter -fPIC -c -MP -MD -MF dep/loop.d -MQ objs/loop.o -o objs/loop.o loop.c
gcc -I. -I. -I./tgl -I/usr/local/include -I/usr/local/Cellar/readline/6.3.8/include  -I/usr/local/include -I/usr/include -I/usr/include   -DHAVE_CONFIG_H -Wall -Werror -Wextra -Wno-missing-field-initializers -Wno-deprecated-declarations -fno-strict-aliasing -fno-omit-frame-pointer -ggdb -Wno-unused-parameter -fPIC -c -MP -MD -MF dep/interface.d -MQ objs/interface.o -o objs/interface.o interface.c
gcc -I. -I. -I./tgl -I/usr/local/include -I/usr/local/Cellar/readline/6.3.8/include  -I/usr/local/include -I/usr/include -I/usr/include   -DHAVE_CONFIG_H -Wall -Werror -Wextra -Wno-missing-field-initializers -Wno-deprecated-declarations -fno-strict-aliasing -fno-omit-frame-pointer -ggdb -Wno-unused-parameter -fPIC -c -MP -MD -MF dep/lua-tg.d -MQ objs/lua-tg.o -o objs/lua-tg.o lua-tg.c
lua-tg.c:664:27: error: unused function 'get_peer' [-Werror,-Wunused-function]
static inline tgl_peer_t *get_peer (const char *s) {
                          ^
1 error generated.
make: *** [objs/lua-tg.o] Error 1](https://cloud.githubusercontent.com/assets/2737108/13273237/54043cc0-daa2-11e5-98dc-7d8423072fe1.png)

**Comment by ziban** [comment]
@luckydonald  I followed this from pytg and I am running into the same error

**Comment by luckydonald** [comment]
@ziban It seems I fixed that by commenting out the unused function. 
```diff
diff --git a/lua-tg.c b/lua-tg.c
index 454a0a6..70f1694 100644
--- a/lua-tg.c
+++ b/lua-tg.c
@@ -661,9 +661,9 @@ struct lua_arg {
 struct lua_arg lua_ptr[MAX_LUA_COMMANDS];
 static int pos;

-static inline tgl_peer_t *get_peer (const char *s) {
+/*static inline tgl_peer_t *get_peer (const char *s) {
   return tgl_peer_get_by_name (TLS, s);
-}
+}*/
```
After that I could use it with [pytg](https://github.com/luckydonald/pytg).

**Comment by luckydonald** [comment]
@mz1988 could you please reopen this issue, as it persistes for some users?

**Comment by sjug** [comment]
I still have this get_peer issue on OSX.

**Comment by ebarano** [comment]
Just to be clear, did you open the lua-tg.c file and comment out lines 664-666?

![screenshot 2016-06-06 15 40 12](https://cloud.githubusercontent.com/assets/13632941/15837003/011c3204-2bfd-11e6-95bc-048cf51ae795.png)

**Comment by luckydonald** [comment]
@ericbaranowski:
Yes, like stated [above, in the diff](https://github.com/vysheng/tg/issues/996#issuecomment-194475028).

**Comment by sammous** [comment]
thank you, you solved my problem @luckydonald

**Comment by Lohoris** [comment]
Uh? Why it's closed? The error is still there…

**Comment by ddanila** [comment]
Issue is still reproducible as for master cloned seconds ago.

**Comment by luckydonald** [comment]
Only @mz1988 or @vysheng can reopen this issue...

**Comment by iansowinski** [comment]
I just had the same problem, commenting out helped though.

**Comment by NanoBjorn** [comment]
The same problem here, I've tried commenting, testing other branches, recursive updates, deleting `-Werror` etc. 
I'm running with this command:

`./configure --disable-openssl --without-zlib --disable-json --disable-liblua && make` 

and getting error:

`gcc objs/tl-parser.o objs/tlc.o -L/usr/local/opt/openssl/lib -L/usr/local/lib  -rdynamic -ggdb -levent -lconfig -lgcrypt -levent   -lreadline  -ldl -lpthread -lutil -o bin/tl-parser
Undefined symbols for architecture x86_64:
  "_crc32", referenced from:
      _tl_count_combinator_name in tl-parser.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/tl-parser] Error 1`

**Comment by yangm97** [comment]
Still getting this issue on macOS.

**Comment by kpa6uu** [comment]
just got this error. Sierra 10.12.6

**Comment by kpa6uu** [comment]
fixed by

```
export CPPFLAGS="-I/usr/local/opt/openssl/include -I/usr/local/opt/readline/include"
export LDFLAGS="-L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib"
./configure --with-openssl=/usr/local/opt/openssl --disable-liblua
```
